### ISSUE TITLE
Environment-dependent error when linking OpenMP on M1 Macs

### ISSUE THREAD

**Issue by motiwari** [pypa/cibuildwheel#1019]
### Description

I'm trying to build our package for M1 Macs via `cibuildwheel` by cross-compiling for M1 Macs from a Github Mac Runner, as suggested in the [Tips and Tricks](https://cibuildwheel.readthedocs.io/en/stable/faq/#apple-silicon) of `cibuildwheel`'s documentation. The package is written in C++ and exposed to Python via `pybind11`.

Extremely weirdly, the package installs correctly on **all** M1 Macs but sometimes throws an error -- only on **specific** M1 Macs -- when `import`ing the installed package:

```
Traceback (most recent call last):
  File "ex1.py", line 1, in <module>
    from banditpam import KMedoids
ImportError: dlopen(/Users/frieda/miniconda3/envs/behavior/lib/python3.8/site-packages/banditpam.cpython-38-darwin.so, 0x0002): symbol not found in flat namespace '_omp_get_max_threads'
```

I believe the error is thrown because the target machine cannot find the OpenMP functions required on [this line](https://github.com/ThrunGroup/BanditPAM/blob/main/src/python_bindings/kmedoids_pywrapper.cpp#L21).

Do you know why this might be happening? `brew install libomp` does not resolve the issue. Unfortunately I don't have an M1 Mac myself, so am unable to determine the exact environment of target machines where the import fails. It's very weird that it works on some M1 Macs but not others.

I thought of statically linking OpenMP in our build, but that is [strongly discouraged](https://stackoverflow.com/questions/48359791/static-linking-against-openmp#comment83760204_48359791). Since it works on some M1 Macs but not others, might this be a `cibuildwheel` issue?

**Other things I've tried:**

- [This post](https://stackoverflow.com/questions/35006614/what-does-symbol-not-found-expected-in-flat-namespace-actually-mean/39519008#39519008) suggests that it might be in incompatibility with `clang`'s OpenMP vs. `gcc`'s OpenMP. I tried to statically link OpenMP in our `setup.py`, but couldn't get it to work, and even if I could, I'm not sure it would be the correct solution.

- I also thought to use `gcc` to compile the package, but from the `cibuildwheel` documentation, I don't think this is possible when cross-compiling for an M1 Mac via an Intel Mac Github runner.

For reference, [here](https://github.com/ThrunGroup/BanditPAM/blob/main/setup.py#L343-L377) is the relevant code in our [`setup.py`](https://github.com/ThrunGroup/BanditPAM/blob/main/setup.py)

**Other Questions:**

- Do I need to include the `-fPIC` flag? 
- What is the best way to statically link libraries in our `setup.py`? We have another library, `armadillo`, that someone [reported a bug with](https://github.com/ThrunGroup/BanditPAM/issues/167#issuecomment-1027647823) and may be resolved by statically linking it

Thank you for maintaining `cibuildwheel`, it's very helpful.

**Comment by Czaki** [comment]
You do not link to configuration. 
After a short review of your code, it looks like you do not do cross-compilation of OpenMP for M1 arm. The `brew install libomp` install version for current architecture (in this case x86_64). You may need to build libomp from source with cross-compilation [example](https://github.com/Czaki/imagecodecs_build/blob/master/build_utils/build_libomp.sh).    

> It's very weird that it works on some M1 Macs but not others.

Check OS version. As I remember it may happen that it could work on MacOS 12, and not work on MacOS 11.

**Comment by motiwari** [comment]
Thanks @Czaki ! 

Could you clarify what you mean by "You do not link to configuration"? Did you want a link to our [pyproject.toml](https://github.com/ThrunGroup/BanditPAM/blob/main/pyproject.toml), or did you mean to imply that static linking is not the correct thing to do?

I'll try the cross-compiling libomp for M1 arm; thanks for the reference. But I don't think this explains why it *works* on some M1 Macs but not others?

I don't think it's related to the OS version -- all of our users have been OSX 12 and it works on some but not others.

**Comment by henryiii** [comment]
Did some of them have `brew install libomp`? Possibly as a dependency with another brew package?

**Comment by motiwari** [comment]
I asked a user to run `brew install libomp` on their M1 Mac after they got that error, but the error persisted after the `libomp` installation :( 

Let me try cross-compiling for M1 Mac as per Czaki's comment, or at least getting to a reproducible situation. (It is a bit difficult as I don't have an M1 Mac myself so can't reproduce it locally and am working with a colleague)

**Comment by motiwari** [comment]
Oh, perhaps you meant that they already had a previous installation of libomp that conflicted with the one in our wheel; let me ask

**Comment by Czaki** [comment]
> Check OS version. As I remember it may happen that it could work on MacOS 12, and not work on MacOS 11.

@motiwari Did you try to verify if checking system version does not explain situation? M1 is only processor. There are big changes between Macos 11 and 12. Some of packages (for example scikit-image) does not provide support for MacOS 11 (arm) because of some errors in this version of system.

**Comment by motiwari** [comment]
Sorry for the delay here. After investigating this further, I don't believe our root error is related to `cibuildwheel` and is something else (exact diagnosis TBD).

Thank you for your help!

**Comment by axu2** [comment]
Did you ever figure out the issue? I'm getting something similar here: https://github.com/wanadev/mozjpeg-lossless-optimization/issues/5
