### ISSUE TITLE
Azure deprecating vs2017-win2016

### ISSUE THREAD

**Issue by larsoner** [pypa/cibuildwheel#1023]
### Description

See https://devblogs.microsoft.com/devops/hosted-pipelines-image-deprecation/#windows

They plan to have some brown-outs:

https://docs.microsoft.com/en-us/azure/devops/release-notes/2021/sprint-196-update#brownout-schedule-for-windows-2016-hosted-images

It would be good to update CIBUILDWHEEL to support this change. If it's as easy as just changing the entry in `azure-pipelines.yml`, then that would be great (and should be done to this repo's azure-pipelines.yml to make it clear other repos can do the same)! If it is that easy, I'm happy to open a PR to do it, though I'm not sure if `'windows-2019'`, `'windows-2022'`, or `'windows-latest'` would be the best option.

**Comment by henryiii** [comment]
Yes, it should be that easy. We had the oldest supported one in there, but it's about time to update it. We use newer images in GHA (they are the same).

**Comment by henryiii** [comment]
This should be updated, certainly: https://github.com/pypa/cibuildwheel/blob/main/examples/azure-pipelines-minimal.yml

**Comment by henryiii** [comment]
And for users, our FAQ has a section on a possible side affect of using MSVC 2019+ and how to avoid it in your setup.py if you need to.
