### ISSUE TITLE
GitLab CI tests failing

### ISSUE THREAD

**Issue by mayeut** [pypa/cibuildwheel#1025]
### Description

GitLab CI tests are starting to fail with a "No Space Left" error:
- https://gitlab.com/joerick/cibuildwheel/-/pipelines/469281208
- https://gitlab.com/joerick/cibuildwheel/-/pipelines/469589079

**Comment by joerick** [comment]
Sigh. They're now failing with

> ERROR: Job failed: execution took longer than 2h0m0s seconds

I'll look at running a subset of tests on there.
