### ISSUE TITLE
macos-11 run fails with FileExistsError

### ISSUE THREAD

**Issue by gliptak** [pypa/cibuildwheel#1028]
### Description

v2.3.1 fails with

```
    FileExistsError: [Errno 17] File exists: '/Users/runner/work/python-snappy/python-snappy/.eggs/cffi-1.15.0-py3.7-macosx-10.7-x86_64.egg'
```

### Build log

https://github.com/gliptak/python-snappy/runs/5192258820?check_suite_focus=true

### CI config

https://github.com/gliptak/python-snappy/actions/runs/1843982419/workflow

**Comment by henryiii** [comment]
Looks like it's making CFFI (dependency) twice, once for CPython 3.7, and once for PyPy 3.7, and they are colliding. I'd recommend using pyproject.toml and the PEP 517 build process, I don't think this would happen if you did that.

**Comment by gliptak** [comment]
@henryiii thank you for the pointer. I review the dependencies
