### ISSUE TITLE
PyPy has released bug fixes and a python3.9

### ISSUE THREAD

**Issue by mattip** [pypa/cibuildwheel#1032]
### Description

PyPy released version v7.3.8. It would be nice to be able to use it in cibuildwheel, including the newly released python3.9

**Comment by mayeut** [comment]
Bug fixes are included in #1027 (for macOS/Windows).
PyPy 3.9 is addressed in #1031 (for macOS/Windows). 
manylinux is on hold for both c.f. https://github.com/pypa/manylinux/pull/1288#issuecomment-1046322172
