### ISSUE TITLE
Provide {install} variable to stand in for yum/apt-get/apk

### ISSUE THREAD

**Issue by reynoldsnlp** [pypa/cibuildwheel#1034]
Since there are now multiple linux distros with different package managers, it would really convenient if `cibuildwheel` provided a variable (much like `{package}`, `{wheel}`, `{dest_dir}`, etc.), that contains the package managers name. This would allow you to do `before-all` with something like `{install} bison` and it would resolve to `yum install bison` or `apt-get install bison` or `apk install bison`, depending on the distro.

**Comment by henryiii** [comment]
This was discussed originally, but since the libraries often have different names (-dev vs -devel), and you have different ways of updating the cache, it’s much better to use overrides (which were partially designed to help solve this).

And it’s `apk add`, not install.

**Comment by reynoldsnlp** [comment]
@henryiii thanks for such a quick response! What you say makes good sense, so I'm closing the issue.

**Comment by joerick** [comment]
Indeed! Only other thing to note is that [config overrides](https://cibuildwheel.readthedocs.io/en/stable/options/#overrides) are intended to be useful for this kind of situation.
