### ISSUE TITLE
Optionally use existing installations of tools

### ISSUE THREAD

**Issue by altendky** [pypa/cibuildwheel#104]
https://github.com/joerick/cibuildwheel/blob/9372e37b1886be448ca6b67a14dc6708657ac4a8/README.md#L35
> It will try to install packages globally; this is no good.

I haven't looked and this isn't any priority for me but...  couldn't this installation be optional?  I might tend towards having it disabled by default but I get there will be arguments both ways.

**Comment by joerick** [comment]
Well, on Mac, cibuildwheel installs MacPython, and upgrades setuptools, wheel, delocate globally (not in a virtualenv). On Windows it assumes the existence of the interpreters, but still installs things like pip, setuptools globally.

What would the use-case be for disabling these installs? running a test build on your mac/windows dev machine?

**Comment by altendky** [comment]
I didn't dig into the details, just read the docs, but yes.  As I said this is of no urgency to me to me but I think software is generally better when it doesn't need warnings like this. Is there some need to install these globally rather than in an env?

**Comment by joerick** [comment]
> Is there some need to install these globally rather than in an env?

MacPython can only be installed globally. But other than that, the python bits could install into a venv. I guess that running cibuildwheel locally could be helpful for debugging. In which case, maybe we could have something like `cibuildwheel --local`, which would look for existing installs of MacPython (or Windows local installs) and use a virtualenv for the python dependencies.

**Comment by altendky** [comment]
I would tend to default to not trying to fuss with the system.  Requiring that people type `--install-deps` or whatever once in a tox.ini doesn't seem particularly onerous.  or even a separate subcommand (are there any?  i forget...).

**Comment by HDembinski** [comment]
I am trying to use cibuildwheels for a non-trivial project, and - of course - it does not work, because I need to install certain dependencies that are missing in some docker images or not found by the CMake scripts in my project. Debugging these issues by adding small commits on a branch until the CI works is an incredibly painful process.

Long story short: it would be great if one could run cibuildwheels locally for testing/debugging of the build.

**Comment by YannickJadoul** [comment]
> Long story short: it would be great if one could run cibuildwheels locally for testing/debugging of the build.

It can be, right? If you're happy to have docker images downloaded and run, or Python versions installed on macOS/Windows, you can perfectly run cibuildwheel locally. Just skip the platform checks/detection by adding the correct `--platform` flag.
It's just really not meant to run locally, so we're not enabling that by default.

**Comment by hoffmang9** [comment]
> I am trying to use cibuildwheels for a non-trivial project, and - of course - it does not work, because I need to install certain dependencies that are missing in some docker images or not found by the CMake scripts in my project. Debugging these issues by adding small commits on a branch until the CI works is an incredibly painful process.

We had the same issues - the best way to debug the os/cmake problems is to run the pypa docker and get it building by hand there. 

Example CIBW_BEFORE_BUILD_LINUX here: https://github.com/Chia-Network/bls-signatures/blob/master/.github/workflows/build.yml
