### ISSUE TITLE
[Docs] Example may accidentally be encouraging users to write invalid `pyproject.toml` files

### ISSUE THREAD

**Issue by abravalheri** [pypa/cibuildwheel#1064]
### Description

Hi guys, first of all thank you for the amazing project (always good to remember).

While I was working on adding support for PEP 621 to setuptools, I noticed a series of users having problems with invalid `pyproject.toml` files. The common pattern seem to be a almost empty `[project]` table with only a `requires-python` field set, which is invalid according to PEP 621.

It took me some time to find the reason for this behaviour but I think it comes from:
https://cibuildwheel.readthedocs.io/en/stable/options/#requires-python

I suspect that the example and notes about the preferred way of setting the config has been encouraging users that are unaware of PEP 621 to write technically invalid `pyproject.toml` files.

Please note that this issue is not necessarily related to setuptools itself.
The existence of the `[project]` table in the `pyproject.toml` allows (according to the standard) the installer/builder/consumer program to treat the package differently (specially regarding `dynamic`).

I think it would be nice to at least add a note about this so users became aware of the implications of adding a `[project]` table.

**Comment by abravalheri** [comment]
(Obs.: I plan to add a (very) temporary workaround for this in setuptools)

**Comment by joerick** [comment]
Hey @abravalheri ! Thanks for letting us know, and apologies for the mistake! I'll take a look at the PR now.

**Comment by abravalheri** [comment]
Thank you very much @joerick for having a look.

I am very sure that this was just an unintended consequence, by no means I consider this a mistake. Given a large enough base of users everything might happen... And you guys do an awesome job in `cibuildwheel`.

I am just releasing a new version of setuptools anyway that is working around this issue (temporarily) and warning the users. I hope people it will be enough!
