### ISSUE TITLE
Why is *-manylinux_aarch64 build identifier filtered out?

### ISSUE THREAD

**Issue by Guillaume227** [pypa/cibuildwheel#1077]
### Description

I am attempting to run cibuildwheel on the following toml:
```
[tool.cibuildwheel.linux]
build = ["cp39-manylinux_aarch64", "cp39-manylinux_x86_64"]
```
using `--print-build-identifiers` I only see `cp39-manylinux_x86_64`

it does generate the wheel nicely for `cp39-manylinux_x86_64` but gives no reason why the aarch64 flavor was dropped from the list I specified. 
What am I missing here?

My setup.cfg has:
`python_requires='>=3.9',`
and I see `cp310` gets filtered out too.

I am running on ubuntu20.04(Windows11 + WSL2) in case that matters (`--platform linux`)

Note: looking at the [build-identifiers](https://cibuildwheel.readthedocs.io/en/stable/options/#build-skip), I picked aarch64 for the purpose of creating a wheel targeting a raspberry 3b+. 
In am not sure it's the right choice and I would be glad if someone could share their experience / an example of targeting the raspberry.

**Comment by henryiii** [comment]
You need to enable emulation for that arch. It's mentioned in the docs, or https://iscinumpy.dev/post/cibuildwheel-1-9-0/ covers it a bit. Basically, you need to manually ask for that arch with the `--archs` flag/var/option, and make sure you have enabled QEMU emulation beforehand.

**Comment by Guillaume227** [comment]
Thank you, I did skim the doc but should have looked closer. The build is progressing now, nice!
