### ISSUE TITLE
BUG: can't build wheel for CPython 3.10 on windows with cibuildwheel 2.4.0

### ISSUE THREAD

**Issue by neutrinoceros** [pypa/cibuildwheel#1078]
### Description

Hi, we're using cibuildwheel to compile wheels for https://github.com/yt-project/yt/

In upgrading cibuildwheel from 2.3.0 to 2.4.0, something breaks our builds on CPython 3.10 + Windows 32 bits

As far as I can tell, it looks like the runner is now trying to build a wheel for numpy 1.21.4 This wasn't the case with cibuildwheel 2.3.0.

### Build log

https://github.com/neutrinoceros/yt/actions/runs/2140271185

### CI config

https://github.com/yt-project/yt/pull/3891/files#diff-91b9b589616af36da34e6a0314171ea68cc16b399915d9630a20ea04eb8e99f5

**Comment by Czaki** [comment]
On the main branch, there is also a build of numpy from the source: 
https://github.com/neutrinoceros/yt/runs/5828582534?check_suite_focus=true
```
Collecting numpy==1.21.4
      Downloading numpy-1.21.4.zip (10.6 MB)
      Installing build dependencies: started
      Installing build dependencies: finished with status 'done'
      Getting requirements to build wheel: started
      Getting requirements to build wheel: finished with status 'done'
      Preparing metadata (pyproject.toml): started
      Preparing metadata (pyproject.toml): finished with status 'done'
    Building wheels for collected packages: numpy
      Building wheel for numpy (pyproject.toml): started
      Building wheel for numpy (pyproject.toml): still running...
      Building wheel for numpy (pyproject.toml): still running...
      Building wheel for numpy (pyproject.toml): finished with status 'done'
      Created wheel for numpy: filename=numpy-1.21.4-cp310-cp310-win32.whl size=4974600 sha256=b8d15efb86bb8cc12c10168f732da59dc85c2e054ca8894df66dd645b58efcf7
      Stored in directory: c:\users\runneradmin\appdata\local\pip\cache\wheels\20\84\89\1ac0b39e05b3bb43964fdc23c5a934e3edf4194e9c5f671ffe
    Successfully built numpy
```

The only numpy version that have win32 wheels, ath thism moment, is 1.22.3. 

After read the stacktrace it looks like to modern version of setuptools. @henryiii  I think that maintainers of `oldest-supported-numpy` should review this problem. I think that bes option could be upload `numpy==1.21.4` wheels to pypi to save hundreds or even thousands to CI hours.

**Comment by henryiii** [comment]
X-ref: https://github.com/scipy/oldest-supported-numpy/issues/45

**Comment by matham** [comment]
Something must have changed in the latest cibuildwheel releases to make numpy building from source fail, when it didn't before. I'm guessing something in the way it sets up the virtualenv in which it builds the wheel now prevents numpy from building!? Because until recently there was no issue (even though numpy was still built from source).

I initially thought `oldest-supported-numpy` was the issue. But actually, there's no changes there in the recent releases that would cause this, so it's something in this repo or its deps that changed that is preventing numpy from building now.

**Comment by Czaki** [comment]
`setuptools` version was bumped and `numpy.distutils` is not compatible with new setuptools version.

**Comment by Czaki** [comment]
I could confirm that it also affects building wheels for pypy 3.7 https://github.com/4DNucleome/PartSegCore-compiled-backend/runs/5972857498?check_suite_focus=true#step:4:708

**Comment by henryiii** [comment]
They are going to release a new NumPy 1.21 release with Windows 32-bit wheels. The other thing that needs fixing (you can't specify bitness in requirements) might also get fixed, but that's a longer timescale.

**Comment by henryiii** [comment]
See https://github.com/numpy/numpy/pull/21323 for status.

**Comment by neutrinoceros** [comment]
Thanks @henryiii for the pointers, I confirm that the issue was resolved with the new releases of numpy and oldest-supported-numpy.
