### ISSUE TITLE
Authenticating inside image 

### ISSUE THREAD

**Issue by katetsu** [pypa/cibuildwheel#1080]
### Description

I am trying to find out why my build is failing. 

I have a project that needs to access protected resources and for that reason im using a .netrc file to allow that. 

when using the `quay.io/pypa/manylinux2014_x86_64` image, i can build my project w/o any issues. but using ciBuildWheels, I am getting authentication errors. is there some special configuration used for launching the image that skips using the netrc file ?

**Comment by joerick** [comment]
> is there some special configuration used for launching the image that skips using the netrc file ?

The great thing about open source, is you can check yourself! here is where we launch the docker container: https://github.com/pypa/cibuildwheel/blob/main/cibuildwheel/docker_container.py called from here: https://github.com/pypa/cibuildwheel/blob/main/cibuildwheel/linux.py#L338
