### ISSUE TITLE
build started failing on macOS on Github Action

### ISSUE THREAD

**Issue by dvarrazzo** [pypa/cibuildwheel#1101]
### Description

Building on Github Action on macOS started failing recently with:
```
Error: Command ['pkgutil', '--pkgs'] failed with code -9. 
```
found with cibuildwheel 2.3.1, but upgrading to 2.5 [didn't fix the problem](https://github.com/psycopg/psycopg/runs/6251037383?check_suite_focus=true).

- [working run](https://github.com/psycopg/psycopg/runs/6235963207?check_suite_focus=true), triggered at 2022-04-29T22:39:48Z
- [failing run](https://github.com/psycopg/psycopg/runs/6245401702?check_suite_focus=true), triggered at 2022-05-01T07:36:01Z

I can't spot any difference between the runners.

### Build log

https://github.com/psycopg/psycopg/runs/6245401702?check_suite_focus=true

### CI config

https://github.com/psycopg/psycopg/blob/96cb1253cd15fec1d0ea88a7192884285d40dd30/.github/workflows/packages.yml#L145-L177

**Comment by mayeut** [comment]
@dvarrazzo, did you end up changing anything ? I see https://github.com/psycopg/psycopg/actions/runs/2288920271 is passing now.

**Comment by dvarrazzo** [comment]
I see. No, I didn't change anything. As it broke, it fixed itself, it seems, looking a [the last jobs](https://github.com/psycopg/psycopg/actions/workflows/packages.yml).

To complete the log above, the passing workflow run at 2022-05-08T07:35:49Z

![image](https://user-images.githubusercontent.com/199429/167308489-96010cf0-60c8-434a-9e87-c82f2ae06108.png)

Closing this here. Will keep you informed if something changes. Thank you!
