### ISSUE TITLE
MacOS builds have a dependency on /DLC which doesn't exist

### ISSUE THREAD

**Issue by jonathanunderwood** [pypa/cibuildwheel#1103]
### Description

When building macOS wheels with extension modules with cibuildwheel (on Github actions runners), the resulting wheels have a dependency on files under /DLC which don't exist. See https://github.com/python-lz4/python-lz4/issues/244 for more detailed information.

**Comment by mayeut** [comment]
Answered in https://github.com/python-lz4/python-lz4/issues/244 & https://github.com/matthew-brett/delocate/issues/150 
Not an issue.
