### ISSUE TITLE
Setting different options for manylinux vs musllinux

### ISSUE THREAD

**Issue by astrofrog** [pypa/cibuildwheel#1112]
### Description

For a package I maintain, I need to set:

```
[tool.cibuildwheel.linux.environment]
CC = "gcc"
```

for manylinux builds, and:

```
[tool.cibuildwheel.linux]
before-build = "apk update && apk add clang"

[tool.cibuildwheel.linux.environment]
CC = "clang"
```

for musllinux builds, but I can't figure out if it's possible to do this based on the current documentation?

(for anyone curious, the issue is that gcc<10 has a bug in it that affects my package, and I don't think it's easy to install gcc-10 on the musllinux image so clang is the next best option).

**Comment by Czaki** [comment]
please read about overrides:
https://cibuildwheel.readthedocs.io/en/latest/options/#overrides

**Comment by astrofrog** [comment]
Perfect, thanks!
