### ISSUE TITLE
Can't find msbuild with 2.4.0+

### ISSUE THREAD

**Issue by QuLogic** [pypa/cibuildwheel#1118]
### Description

I'm trying to [update Matplotlib](https://github.com/QuLogic/matplotlib/pull/16) into the latest cibuildwheel. However, I'm running to the problem on Windows that it cannot find `msbuild`. This fails with cibuildwheel [2.4.0](https://github.com/QuLogic/matplotlib/runs/6603973220?check_suite_focus=true), [2.5.0](https://github.com/QuLogic/matplotlib/runs/6587812098?check_suite_focus=true), or [2.6.0](https://github.com/QuLogic/matplotlib/runs/6599982054?check_suite_focus=true), but works with [2.3.1](https://github.com/QuLogic/matplotlib/runs/6603265520?check_suite_focus=true).

Bisecting points me to e5c210c0863bc7970b76a3958a9f8360baa69135 ([broken build](https://github.com/QuLogic/matplotlib/runs/6604628328?check_suite_focus=true) vs [previous commit](https://github.com/QuLogic/matplotlib/runs/6604514513?check_suite_focus=true)).

### Build log

https://github.com/QuLogic/matplotlib/runs/6604628328?check_suite_focus=true

### CI config

https://github.com/QuLogic/matplotlib/blob/ba16d002d5bc55a5145589662a81b3ba22ba9503/.github/workflows/cibuildwheel.yml

**Comment by QuLogic** [comment]
Looking through that change, I see that there is a major upgrade of `setuptools` from 59.6.0 to 60.2.0, which includes the change:

> [#2896](https://github.com/pypa/setuptools/issues/2896): Setuptools once again makes its local copy of distutils the default. To override, set `SETUPTOOLS_USE_DISTUTILS=stdlib`.

and indeed, if I add `CIBW_ENVIRONMENT_WINDOWS: SETUPTOOLS_USE_DISTUTILS=stdlib`, then [the build passes](https://github.com/QuLogic/matplotlib/runs/6605152494?check_suite_focus=true).

However, I do not understand why this is necessary with `cibuildwheel`. We unfortunately do not have tests running on GitHub Actions for Windows, but do run tests on AppVeyor for Windows. However, in that case, we have `setuptools-62.3.2` installed and do _not_ need to use stdlib distutils.

**Comment by henryiii** [comment]
Also your CI is using conda, I believe, which will be very different as far as compiler configuration.

**Comment by QuLogic** [comment]
No, it does not pass with [3.9](https://github.com/QuLogic/matplotlib/runs/6617704647?check_suite_focus=true) or [3.8](https://github.com/QuLogic/matplotlib/runs/6617763075?check_suite_focus=true).

I managed to cut away most the tests into a GitHub Action that only builds on Windows: https://github.com/QuLogic/matplotlib/actions/runs/2393780852
This fails on all versions with the same error.

I forgot about this, but we do some crazy hack to get the compiler search path:
https://github.com/matplotlib/matplotlib/blob/6296e500cfbf6c5a9247a016a059505b9330bc9f/setupext.py#L528-L548
So I guess it's on us to fix...
