### ISSUE TITLE
Expose cache stats

### ISSUE THREAD

**Issue by abitrolly** [pypa/cibuildwheel#1122]
### Description

I found this CI scenario that passes cache to dir to `cibuildwheel` through environment variables.

https://github.com/facebook/prophet/blob/84132a29eb8c54976033128965a8d6426831aa4c/.github/workflows/wheel.yml#L142

However, I am not sure it works. Builds are taking consistent 50 minutes. https://github.com/facebook/prophet/runs/6575717161?check_suite_focus=true

Exposing stats about cache hits and misses could save a lot of time troubleshooting build performance issues.

### Build log

https://github.com/facebook/prophet/runs/6575717161?check_suite_focus=true

### CI config

https://github.com/facebook/prophet/blob/84132a29eb8c54976033128965a8d6426831aa4c/.github/workflows/wheel.yml#L142

**Comment by joerick** [comment]
That would be an option/feature of pip, not cibuildwheel. You can supply pip options using environment variables through CIBW_ENVIRONMENT.

**Comment by abitrolly** [comment]
@joerick but how do you know that `pip` can correctly use cache when wrapped into several layers of CI jobs, containers and virtual environments?

**Comment by joerick** [comment]
Fair question, it's tricky. But what can cibuildwheel do to help? The cache is a feature of pip, not cibuildwheel.

**Comment by abitrolly** [comment]
If `cibuildwheel` can expose cache stats, it can at least warn when no cache was hit. It would be nice if `cibuildwheel` action could take care of the cache somewhat automatically, for the above reasons.
