### ISSUE TITLE
Allow using custom python installs optionally

### ISSUE THREAD

**Issue by ankith26** [pypa/cibuildwheel#1130]
It's great that cibuildwheel abstracts away handling builds on multiple python versions. So first of all, thanks to everyone here helping maintain this project! 🥳 

On Windows and MacOS, cibuildwheel takes care of installing the python versions needed for builds. While this is a convenient and portable solution, I propose that cibuildwheel should (optionally) be able to pick up python installs from the CI VMs (if supported) and/or allow users to specify their own python installs.

### Why?

I have used cibuildwheel mostly on Github Actions and AppVeyor. Both of these have many versions of python installed, and Github Actions have many versions of PyPy installed right into the VM base itself.

#### Relevant docs/references

- https://www.appveyor.com/docs/macos-images-software/
- https://www.appveyor.com/docs/windows-images-software/
- https://github.com/actions/virtual-environments/blob/main/images/win/Windows2019-Readme.md
- https://github.com/actions/virtual-environments/blob/main/images/macos/macos-11-Readme.md

It would save CI minutes if cibuildwheel could somehow use these directly. For instance, CPython installs on MacOS (Github Actions) take around 30 seconds. This does not sound like a lot, but when there are multiple python versions to install, this can add up and become more significant.

### Proposal

This addition should be completely opt-in and experimental for now: the default behaviour should stay the same as before to not break workflows of any existing cibuildwheel user.

Users should be able to control it with something like `CIBW_PYTHON_INSTALL` (with Windows and MacOS specific overrides allowed in `CIBW_PYTHON_INSTALL_WINDOWS` and `CIBW_PYTHON_INSTALL_MACOS`  respectively) which should take the options:
- `install`/`auto`: cibuildwheel installs python (default)
- `ci`: Try to pick up pythons from CI if supported (maybe falling back to default if not possible)
- `custom`/`manual`: allow users to manually specify paths to python/pypy somehow if they need to (advanced usage: most people probably don't need this)

### Potential de-merit of the proposal

Slightly increased maintenance burden on cibuildwheel

### Implementation

I opened this issue to get some opinions/ideas from others. If the maintainers like this proposal, I want to give a shot at tackling this one myself.

**Comment by henryiii** [comment]
Different compiles of Python are not interchangeable on macOS. To build redistributable wheels, you really need the official CPython compiled version, others are not compiled to be compatible. For example, GHA is compiled with min macOS 10.14, while the official binaries are compiled with 10.9. So you'd not be able to target anything older than 10.14 with GHA Python. Also, I'm pretty sure GHA Python is not compiled with ARM support too, so you'd not be able to produce Universal2/ARM cross-compiled binaries. For Homebrew, that's usually exactly the version of macOS you are running, and I'm sure there's no cross-compile support.

So supporting this on macOS would really require good user knowledges of compiling for macOS, and usually wouldn't be very useful, and would discourage rather than encourage Apple Silicon & older macOS support.

Windows is actually the "easy" one, any binary works AFAIK. But it's also pretty fast on Windows, and we lock exact minor versions, and we allow beta versions, so there's not much to be gained, I'd think.

**Comment by ankith26** [comment]
Hi, thanks for the quick reply.

I had expected that Github Actions used official CPython 10.9 support binaries, unfortunate that it's not the case.

I might still try to experiment with how much gain this can give on Windows even though I see the gains here might not be as high as it would be if it was possible on macs

**Comment by ankith26** [comment]
To add per-build customisation support, I have a proposal but I don't think it's super elegant. But it's the best idea I have ATM:

The current "build identification" (the ones that are passed to `CIBW_BUILD`) tags should have optional meta-data that should be allowed after a `::`, which can be chained so that there is room for future expansion here. The part before the first `::` should represent the tag part, and there can be subsequent `key:value` pairs separated by a `::` (open to different suggestions for the separator here. I only chose `:` because it's the default pathsep on unix platforms, and an invalid character for a windows path)

Examples:
`cp310-win_amd64` - python installation completely opaque to the user, cibuildwheel handles it. For most users, this should be the recommended and default usage of cibuildwheel.

`cp311-win32::install:preinstalled` - This should be the way to tell cibuildwheel to just use whatever `virtualenv` finds that is already installed on a system. This should be allowed on mac and windows only. Also there should be a fair warning about the usage of this option on macs. Here, `glob`ing should only be allowed in the tag part.

`cp38-macosx_x86_64::path:/absolute/path/to/python/bin` - user specified a custom path, this should be allowed on all platforms. Here, `glob`ing should not be allowed anywhere in the tag

Passing both `path` and `install` should result in the `path` being tried first (inline with virtualenvs `--try-with-first` option) and then falling back to default discovery.

**Comment by joerick** [comment]
Maybe I'm missing something, but what is the use-case for such a feature? As henryiii mentioned, the specific Python binaries used are quite important, so you'd probably end up needing to install them specifically anyway.

**Comment by ankith26** [comment]
The idea is to save python install time (on windows atleast) because most CI runners have many python versions pre-installed. I think this can also be useful for people testing a particular build configuration with cibuildwheel locally.

**Comment by Czaki** [comment]
Maybe this issue should be about better support cache? For example on macos pks could be cached between runs?

**Comment by henryiii** [comment]
We could cache the directory they get downloaded to in the Action, perhaps?

**Comment by ankith26** [comment]
I'm up for that, as long as it can provide a lil speedup :)

**Comment by abhinavbandaru** [comment]
Folks, so most enterprise software build their software in isolation. So, is there a way I can point cibuildwheel to use python on my build machine? I think adding this support to use local / custom python will benefit to the industry.

**Comment by joerick** [comment]
I'm still -1 on such a feature, tbh. Building wheels in arbitrary environments would open up a large surface area for bugs, I think it would complicate maintenance too much to make it worth it.

It would be fairly simple for you to use a task manager like tox/nox to set this up.

e.g.

**noxfile.py**
```
@nox.session(python=["3.7", "3.8", "3.9", "3.10", "3.11", "3.12"])
def build_wheels(session: nox.Session) -> None:
    session.install("build")
    session.run(
        "build",
        "--wheel",
    )
    # call delocate/auditwheel here if required
```

**Comment by ankith26** [comment]
Just chiming in here as the OP that I don't mind this issue being closed. I think the caching approach suggested above is a better solution than what I had proposed almost two years ago, but that's probably for a separate issue.

**Comment by Czaki** [comment]
Based on the current state. We do not install python on macos if it is alredy installed on default path. 
On linux we use docker images, where the industry could easily reconfigure docker to pull them from their own mirror of the docker register. 
As far as I also understand, nuget used on Windows could be pre-set up. 

So it should be possible, but for clear reasons, we could not support officially such workflows as such things will require access to infrastructure for testing, etc. (and maybe some NDA and tons of formalities).
