### ISSUE TITLE
Empty long description will not create "UNKNOWN" as before, which breaks `twine check`

### ISSUE THREAD

**Issue by hzhangxyz** [pypa/cibuildwheel#1131]
### Description

When I use github action to build my package, the wheel file fail to upload to pypi.
because cibuildwheel create metadata like
```
Metadata-Version: 2.1
Name: PyTAT
Version: 0.2.14
Summary: python binding for TAT(TAT is A Tensor library)
Home-page: https://github.com/hzhangxyz/TAT
Author: Hao Zhang
Author-email: zh970205@mail.ustc.edu.cn
License: GPLv3
License-File: LICENSE.md
Requires-Dist: numpy

```

But this is what it output before
```
Metadata-Version: 2.1
Name: PyTAT
Version: 0.2.13
Summary: python binding for TAT(TAT is A Tensor library)
Home-page: https://github.com/hzhangxyz/TAT
Author: Hao Zhang
Author-email: zh970205@mail.ustc.edu.cn
License: GPLv3
Platform: UNKNOWN
License-File: LICENSE.md
Requires-Dist: numpy

UNKNOWN

```

Without the sentence "UNKNOWN", `twine check` raise an error saying
```
ERROR    `long_description` has syntax errors in markup and would not be rendered on PyPI.
         No content rendered from RST source.
```

### Build log

https://github.com/hzhangxyz/TAT/actions/runs/2479911857

### CI config

https://github.com/hzhangxyz/TAT/actions/runs/2479911857/workflow

**Comment by henryiii** [comment]
I expect this is a change in Setuptools and probably a bug in twine.

**Comment by hzhangxyz** [comment]
> I expect this is a change in Setuptools and probably a bug in twine.

You are right, PEP 566 says "In addition to the Description header field, the distribution’s description may instead be provided in the message body".
