### ISSUE TITLE
Tests are skipped on pre-release Pythons

### ISSUE THREAD

**Issue by nitzmahone** [pypa/cibuildwheel#1137]
### Description

On cibuildwheel==2.6.1, when running with `CIBW_PRERELEASE_PYTHONS=1`, any configured test command is always skipped when targeting a pre-release Python version. A quick glance at the code makes me think it's an unintended consequence of having `TestSelector` inherit the prerelease exclusion behavior from `IdentifierSelector`.

### Build log

https://github.com/rolpdog/cffi-mirror/runs/6867587654?check_suite_focus=true

### CI config

https://github.com/rolpdog/cffi-mirror/commit/b7a01156bafba52bd2bfedc1222c9eb8d36491c7#diff-944291df2c9c06359d37cc8833d182d705c9e8c3108e7cfe132d61a06e9133dd

**Comment by joerick** [comment]
Thanks for submitting this. It does indeed look like a bug.
