### ISSUE TITLE
MacOS / ARM / native == auto, whilst should just build `arm64` and skip `x86_64`

### ISSUE THREAD

**Issue by amunra** [pypa/cibuildwheel#1176]
### Description

`cibuildwheel.__version__ == '2.8.0'`

When running on Apple Silicon, `cibuildwheel` also builds the `x86_64`, despite specifying `--archs native` on the command line.

This differs from the documentation https://cibuildwheel.readthedocs.io/en/stable/options/#archs where `native` is supposed to be the same as `platform.machine()`.

**Comment by amunra** [comment]
Installed with `python3 -m pip install cibuildwheel`.

```
% python3 -m platform
maxOS-12.4-arm-64bit
```

**Comment by joerick** [comment]
What is maxOS?

**Comment by joerick** [comment]
that's unexpected, I get this on my M1:

```
$ python3 -m platform
macOS-12.4-arm64-arm-64bit
```
 
Other things to try:

```
$ python3 -c 'import platform; print(platform.machine())'
```

And could you paste a log of the build, including how you invoked it and the header at the top that cibuildwheel produces?

**Comment by joerick** [comment]
feel free to reopen with responses to the above.
