### ISSUE TITLE
How to build wheels with shared object?

### ISSUE THREAD

**Issue by ringsaturn** [pypa/cibuildwheel#1192]
### Description

I want to release a packages with `.so` files, but get error like this:

<img width="1292" alt="image" src="https://user-images.githubusercontent.com/13536789/180630187-34d27404-85dd-47ae-9b5a-32dfe185a08f.png">

### Build log

https://github.com/ringsaturn/tzf/runs/7484996455?check_suite_focus=true

### CI config

https://github.com/ringsaturn/tzf/blob/main/.github/workflows/deploy.yml

**Comment by joerick** [comment]
The real error is in the section above that error:


```
RuntimeError: Invalid binary wheel, found the following shared library/libraries in purelib folder:
258
  	tzf.so
259
  The wheel has to be platlib compliant in order to be repaired by auditwheel.
```
