### ISSUE TITLE
Question: Why `uses: actions/setup-python@v3` exists in github-with-qemu.yml while it is not in github-minimal.yml?

### ISSUE THREAD

**Issue by lebarsfa** [pypa/cibuildwheel#1202]
### Description

Hello,

In github-with-qemu.yml, is 
https://github.com/pypa/cibuildwheel/blob/7c7dda72084bd9203b4fffd3af856560f8e48c64/examples/github-with-qemu.yml#L16-L19
useful while it is not in github-minimal.yml or github-apple-silicon.yml?
If it is not necessary, maybe those lines should be removed to simplify and for consistency...

### CI config

GitHub Actions

**Comment by henryiii** [comment]
I _think_ it's a leftover and can be removed.

**Comment by lebarsfa** [comment]
OK, thank you for this confirmation.
