### ISSUE TITLE
Fails to build some windows-only code with CIBW 2.9 and CPython 3.11

### ISSUE THREAD

**Issue by neutrinoceros** [pypa/cibuildwheel#1229]
### Description

Trying to upgrade to CIBW 2.9.0 to build CPython 3.11 wheels for yt at https://github.com/yt-project/yt/pull/4076

I found that the following line in a C header file doesn't compile

```C
#define isnormal(x) ((_fpclass(x) == _FPCLASS_NN) || (_fpclass(x) == _FPCLASS_PN))
```

and I get the following error

```
    D:\a\yt\yt\yt\utilities\lib\platform_dep_math.hpp(11): error C3861: '_fpclass': identifier not found
    D:\a\yt\yt\yt\utilities\lib\platform_dep_math.hpp(11): error C2065: '_FPCLASS_NN': undeclared identifier
    D:\a\yt\yt\yt\utilities\lib\platform_dep_math.hpp(11): error C2065: '_FPCLASS_PN': undeclared identifier
```

for context, these identifiers are documented as Windows-only:
https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/fpclass-fpclassf?view=msvc-170
and so is the code block where they appear in yt (https://github.com/yt-project/yt/blob/616ec74942ce08ce14426d7b6a4c7ce65b1974b1/yt/utilities/lib/platform_dep.h#L7)

I'm not sure the problem is with CIBW or something else in the supply chain, but I find it suspicious that it compiles fine within the same widows image for all other CPython versions we use it for.

### Build log

https://github.com/yt-project/yt/runs/7818103108?check_suite_focus=true

### CI config

https://github.com/neutrinoceros/yt/blob/cp311_wheels/.github/workflows/wheels.yaml

**Comment by henryiii** [comment]
Maybe the `<float.h>` header is no longer leaked by CPython 3.11? Have you tried either a normal test build (via something like `python-version: “3.11-dev”` in GHA) or a local build?

**Comment by neutrinoceros** [comment]
> Maybe the <float.h> header is no longer leaked by CPython 3.11?

Indeed that's precisely what's happening. I just checked that explicitly including this header fixed the build.
So, clearly nothing wrong with CIBW here, I'll close this.

Thank you so much @henryiii !
