### ISSUE TITLE
CircleCI + native aarch64 linux buils work, how to document this?

### ISSUE THREAD

**Issue by mr-c** [pypa/cibuildwheel#1241]
Here is how we did it, as inspired by @minrk (their setup is at https://github.com/zeromq/pyzmq/pull/1743 )

https://github.com/common-workflow-language/schema_salad/pull/579/files#diff-78a8a19706dbd2a4425dd72bdab0502ed7a2cef16365ab7030a5a0588927bf47R15

**Comment by Czaki** [comment]
I think that you could see #1191 for inspiration. 

Also, a note about this may be added here https://github.com/pypa/cibuildwheel/blob/main/docs/data/projects.yml#L179 for people looking for working examples.

**Comment by joerick** [comment]
Are the ARM runners available for free for open source? If so, we could just add a linux arm runner to the minimal config and add a ✅ to the readme table.

**Comment by mr-c** [comment]
> Are the ARM runners available for free for open source?

Yep!

**Comment by minrk** [comment]
#1307 adds the example, readme ✅, and note
