### ISSUE TITLE
Wheels built for Apple silicon with `brew` dependencies are broken

### ISSUE THREAD

**Issue by pablogsal** [pypa/cibuildwheel#1251]
### Description

When `chibuildwheel` cross-compiles for `aarch64`, if the package has any dependency on a library installed with `brew` it will produce broken wheels because linking will fail. This is because `brew` downloads artefacts for the host architecture and that is x86-64, and then the macOS linker silently fails to link (is not a hard error in most cases). The wheel produced doesn't have all the dependencies linked and therefore when installed on a different machine it fails to load. The fact that wheels cannot be tested makes also this harder to detect before someone tries to install the wheel.

One of the dangers of this issue is that this is not documented and because the error is silent, is very easy to trip over this and produce a bunch of invalid wheels without knowing.

**Comment by Czaki** [comment]
You should not build wheels using brew dependencies as it may have incorrect platform tag.

**Comment by pablogsal** [comment]
How do I get then the binary dependencies on the system to build the wheel?

**Comment by joerick** [comment]
> This is because brew downloads artefacts for the host architecture and that is x86-64, and then the macOS linker silently fails to link (is not a hard error in most cases). The wheel produced doesn't have all the dependencies linked and therefore when installed on a different machine it fails to load.

Yikes. Maybe we could add a post-build check for this (or perhaps delocate could do it?)

> How do I get then the binary dependencies on the system to build the wheel? This is also not documented anywhere that I can see. Not only that, but the documentation hints as using brew to do it:

Yeah, maybe this is worth a FAQ entry. 

When using cibuildwheel, Homebrew is useful to install build tools like Cmake. But it's normally a bad idea to use it for libraries that your wheel is going to link into. As part of the wheel build process, cibuildwheel will invoke `delocate` to bundle these shared libraries into your wheel. That means the brew-installed binaries will be distributed inside your built wheel.

This is generally not a good idea, because brew binaries are compiled for a specific version of macOS, meaning your wheel compatibility is _very_ limited w.r.t. macOS. (is that right @Czaki ?) (That's on top of this architecture confusion that you raise!)

If you're intentionally bundling a shared library with your Python wheel, it's advised to build it as part of the wheel build process, or to find a source for that binary that's broadly compatible.

Alternatively you could disable the [repair step](https://cibuildwheel.readthedocs.io/en/stable/options/#repair-wheel-command), making the shared library a runtime requirement, meaning that users have to `brew install` or otherwise install the requirement themselves.

What is the library that you're experiencing this problem with?

**Comment by Czaki** [comment]
Ok. I see. There is a requirement to validate and update docs (I stop using mac over a year ago, but do not read about changes that will invalidate my objections). 

The brew is a great source to install build tools like automake etc. but it has a few big disadvantages:

1) it installs libraries in a version for the host system (for example 10.15, 11.0, 12.0), and currently delocate does not properly validate platform tag (I start such PR, but then lost access to macOS machines, maybe will try finish without it). And currently, x86 wheels are built against MacOS 10.9 
2) at least once I meet the brew package that was compiled locally (during install) with `--march=native` which means that the library could use CPU commands that are not available on all machines. I do not know if it is possible to detect a minimal CPU that is able to run such a binary.
3) brew installed libraries may be the full versions of the library with all dependencies, even if your library does not use it that may produce much bigger wheels.

In general, brew is great for building tools, but all dependant libraries you need to build by yourself. You may try to cache such build for speedup build if build dependency every run is to long.

**Comment by pablogsal** [comment]
> What is the library that you're experiencing this problem with?

In this case is `liblz4`

> Yeah, maybe this is worth a FAQ entry.

I think it is because the docs currently point to brew in `Missing dependencies` and that is not clear that it only points to `missing build dependencies`.

> it installs libraries in a version for the host system (for example 10.15, 11.0, 12.0), and currently delocate does not properly validate platform tag (I start such PR, but then lost access to macOS machines, maybe will try finish without it). And currently, x86 wheels are built against MacOS 10.9

Hummm, but then is fine as long as I don't support MacOS versions older than the machine I am building for, no?

> In general, brew is great for building tools, but all dependant libraries you need to build by yourself. You may try to cache such build for speedup build if build dependency every run is to long.

I understand this but this is quite a disappointment because the maintenance cost of building these dependencies myself is now generally unbounded as some of these dependencies have even more dependencies and the tree can be just too much.

**Comment by Czaki** [comment]
> In this case is `liblz4`

download: https://github.com/Czaki/imagecodecs_build/blob/master/build_utils/download_libraries.sh#L7

build and install: https://github.com/Czaki/imagecodecs_build/blob/54c5fb3426012a47bd02907542c2c3320841b753/build_utils/build_libraries.sh#L70-L73

> Hummm, but then is fine as long as I don't support MacOS versions older than the machine I am building for, no?

it is not ok until you ensure that the macOS platform tag is set correctly. 

> I understand this but this is quite a disappointment because the maintenance cost of building these dependencies myself is now generally unbounded as some of these dependencies have even more dependencies and the tree can be just too much.

you cold check the brew formulas to know how it is build and how they build dependcies. for example you may see here that it is a pure `make install` call: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/lz4.rb

**Comment by joerick** [comment]
I haven't run into this myself, so a couple of questions from me @Czaki-

> it is not ok until you ensure that the macOS platform tag is set correctly.

What is 'correct' here? That the MACOSX_DEPLOYMENT_TARGET is correct? How does one check this - perhaps an `otool` invocation?

> you may see here that it is a pure `make install` call: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/lz4.rb

And I guess the difference is that if you call this `make install` from cibuildwheel, we have set the MACOSX_DEPLOYMENT_TARGET correctly so that it is more compatible?

**Comment by Czaki** [comment]
@joerick Yes. Currently, we set `MACOSX_DEPLOYMENT_TARGET` to 10.9 (Maybe we should set another target for ARM builds?)
https://github.com/pypa/cibuildwheel/blob/2dfeb940266b8129af4374c5b440ab13aa1d4b2d/cibuildwheel/macos.py#L209

And if the user would like to use brew prebuild libraries then he should set `MACOSX_DEPLOYMENT_TARGET` to target the same as the currently running system as currently `delocate`. Currently, only checks are done in `wheel` package
 https://github.com/pypa/wheel/blob/main/src/wheel/macosx_libfile.py#L278

From python there are three options. Custom code (like wheel), pares otool and use macholib
https://github.com/matthew-brett/delocate/issues/56#issuecomment-926884811


> And I guess the difference is that if you call this `make install` from cibuildwheel, we have set the MACOSX_DEPLOYMENT_TARGET correctly so that it is more compatible?

yes. If `MACOSX_DEPLOYMENT_TARGET` is unset then the compiler compiles against the current system. 
But in the `CIBW_BEFORE_ALL` we also set the proper target:
https://github.com/pypa/cibuildwheel/blob/2dfeb940266b8129af4374c5b440ab13aa1d4b2d/cibuildwheel/macos.py#L294
so calling this here mak produced binary compiled in compatible mode.

**Comment by pablogsal** [comment]
> download: [https://github.com/Czaki/imagecodecs_build/blob/master/build_utils/download_libraries.sh#L7](https://github.com/Czaki/imagecodecs_build/blob/master/build_utils/download_libraries.sh?rgh-link-date=2022-09-04T15%3A29%3A17Z#L7)
> 
> build and install: [Czaki/imagecodecs_build@`54c5fb3`/build_utils/build_libraries.sh#L70-L73](https://github.com/Czaki/imagecodecs_build/blob/54c5fb3426012a47bd02907542c2c3320841b753/build_utils/build_libraries.sh#L70-L73)

I gave this a go but there are more mines in the field because by default if you build Apple silicon wheels compiling dependencies in an intel host will only create intel artifacts and then the linker will refuse to link anything from those. This means that we also need to set the compiler toolchain to know when to build amd64 artifacts which makes the whole thing more complicated because we only need this when compiling for apple silicon.

**Comment by Czaki** [comment]
@pradyunsg totally agree. I currently cannot do this, but I think that our target should be to set up all things for `CIBW_BEFORE_ALL` command, not only `MACOSX_DEPLOYMENT_TARGET` variable.  

Maybe `CC=clang -target arm64-apple-macos11` may help?

**Comment by pablogsal** [comment]
> @pradyunsg totally agree.

Did you mean to say "pablogsal"? I cannot see @pradyunsg commenting on this PR :confused:

**Comment by pablogsal** [comment]
> Maybe `CC=clang -target arm64-apple-macos11` may help?

I tried that but some build systems have special options. For example, we also link against `libbacktrace` and that wants you to set `--host= arm64-apple-macos11` and fails if you set `--target` in CFLAGS.

**Comment by pablogsal** [comment]
Check out [this PR](https://github.com/bloomberg/memray/pull/202) for reference.

**Comment by Czaki** [comment]
> Did you mean to say "pablogsal"? I cannot see @pradyunsg commenting on this PR confused

yes. I do not check github suggestion
