### ISSUE TITLE
github actions recursion error

### ISSUE THREAD

**Issue by maxbachmann** [pypa/cibuildwheel#1252]
### Description

In one of my builds there is a permission error when cibuildwheel attempts to delete one of it's temporary files: `'C:\\Users\\RUNNER~1\\AppData\\Local\\Temp\\cibw-sdist-aysdq8e6'` which appears to be used by another process. This leads to a recursion error when cibuildwheel attempts to delete the file repeatedly:
```
Traceback (most recent call last):
  File "C:\hostedtoolcache\windows\Python\3.10.6\x64\lib\shutil.py", line 621, in _rmtree_unsafe
    os.rmdir(path)
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\RUNNER~1\\AppData\\Local\\Temp\\cibw-sdist-aysdq8e6'
```
```
   File "C:\hostedtoolcache\windows\Python\3.10.6\x64\lib\tempfile.py", line 855, in _rmtree
    _shutil.rmtree(name, onerror=onerror)
  File "C:\hostedtoolcache\windows\Python\3.10.6\x64\lib\shutil.py", line 749, in rmtree
    return _rmtree_unsafe(path, onerror)
  File "C:\hostedtoolcache\windows\Python\3.10.6\x64\lib\shutil.py", line 623, in _rmtree_unsafe
    onerror(os.rmdir, path, sys.exc_info())
  File "C:\hostedtoolcache\windows\Python\3.10.6\x64\lib\tempfile.py", line 840, in onerror
    resetperms(path)
  File "C:\hostedtoolcache\windows\Python\3.10.6\x64\lib\tempfile.py", line 832, in resetperms
    _os.chflags(path, 0)
RecursionError: maximum recursion depth exceeded while calling a Python object
```

### Build log

https://github.com/maxbachmann/JaroWinkler/runs/8168022602?check_suite_focus=true

### CI config

https://github.com/maxbachmann/JaroWinkler/blob/build_sdist/.github/workflows/releasebuild.yml

**Comment by maxbachmann** [comment]
Restarting the build fixed the issue.
Looking into it this appears to be an issue inside cpython:

https://github.com/python/cpython/blob/3.11/Lib/tempfile.py#L877-L881

can lead to indefinite recursion

**Comment by maxbachmann** [comment]
This should be the following issue in CPython https://github.com/python/cpython/issues/86962 and is caused by the temp directory creation here: https://github.com/pypa/cibuildwheel/blob/0117165b02675521b3db2d05033747819bb3ecc5/cibuildwheel/__main__.py#L133

Maybe we can just catch this RecursionError and ignore it if it occurs similar to the `onerror=True` that is used on Windows when calling rmtree.

**Comment by joerick** [comment]
Hmm. Thanks for the report. Yes that looks to be the issue. The only thing I don't understand is why the rmtree fails in the tempfile case, since while we do chdir to that temp directory, the context manager does chdir back to the original working dir before the tempdir is deleted. 

Either way, I agree that it's not good to fail the whole build because cleanup failed - logging a warning is sufficient.
