### ISSUE TITLE
[GH Actions] cibuildwheel action ignores sigterm/sigkill signals

### ISSUE THREAD

**Issue by ddelange** [pypa/cibuildwheel#1272]
### Description

From [docs](https://docs.github.com/en/actions/managing-workflow-runs/canceling-a-workflow):

> For steps that need to be canceled, the runner machine sends SIGINT/Ctrl-C to the step's entry process (node for javascript action, docker for container action, and bash/cmd/pwd when using run in a step). If the process doesn't exit within 7500 ms, the runner will send SIGTERM/Ctrl-Break to the process, then wait for 2500 ms for the process to exit. If the process is still running, the runner kills the process tree.

There are [currently](https://github.com/ddelange/asyncpg/actions) jobs running for 2+ hours which I have tried cancelling repeatedly. As they seem to ignore the signals and keep running, it's blocking newer jobs due to GH quota.

Is there a way to properly interrupt?

### Build log

n/a

### CI config

[`release.yml`](https://github.com/ddelange/asyncpg/blob/7622cd59bfec11012381f2048ee217e2d166c755/.github/workflows/release.yml#L120)

**Comment by joerick** [comment]
Sounds like a bug with GHA, not us. Even if cibuildwheel wasn't properly responding to signals, the runner should kill it after 10 seconds, according to the above.

BTW, we've noticed that emulated jobs on GHA can occasionally hang. Don't know why. The hang seems to be at a lower-level than we're able to detect - we have a pytest plugin that should detect timeouts that isn't able to intervene and kill the test. That sounds like it might be the same issue you're seeing here.

Maybe worth reporting to GHA, if you have time? If you can't cancel the job, you might have to wait for it to timeout before you can restart it.

**Comment by ddelange** [comment]
Closing in favour of https://github.com/actions/runner/issues/2128

**Comment by joerick** [comment]
Thanks!
