### ISSUE TITLE
Wheel file name should not replace dashes with underscores

### ISSUE THREAD

**Issue by ketozhang** [pypa/cibuildwheel#1288]
### Description

Dashes are being replaced with underscores. Dashes are valid package names ([PEP 503](https://peps.python.org/pep-0503/)).

The results issue does not exist with the `build` tool (`python -m build --wheel`)

### Build log

Created wheel for redacted-package-name: filename=redacted_package_name-1.0.0-cp310-cp310-linux_x86_64.whl size=1191321 sha256=b9c8fc1ebc75dbc844a81565372aa57ea66de38f2dd1c22e8a1e694ade01387f

**Comment by henryiii** [comment]
Dashes are not valid in package names, it would interfere with the tags. `redacted_package_name-1.0.0-cp310-cp310-linux_x86_64.whl` would not be parsable into tags - tags are separated by dashes and there are a variable number of them.

I'm a maintainer on build too and it does the same thing. I think you are looking at the sdist instead, where it doesn't matter so tools leave it alone.

In Python packaging, dashes and underscores (and periods) are equivalent.
