### ISSUE TITLE
ARM Mac cross compiling (on github actions) breaks while updating cibuildwheel from 2.5.0 to 2.10.2 

### ISSUE THREAD

**Issue by ankith26** [pypa/cibuildwheel#1299]
### Description

While updating cibuildwheel from 2.5.0 to 2.10.2 I stumbled on a new fail in cibuildwheels "Setting up build environment..." step
```
 + /usr/local/Cellar/pipx/1.1.0/.cache/3f6b5de2dc26d3e/bin/python -sS /Users/runner/Library/Caches/cibuildwheel/virtualenv-20.16.5.pyz --activators= --no-periodic-update --pip=22.2.2 --setuptools=65.3.0 --wheel=0.37.1 --symlink-app-data --python /Library/Frameworks/Python.framework/Versions/3.8/bin/python3 /private/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/cibw-run-n911ma87/cp38-macosx_arm64/build/venv
  dyld[3596]: Library not loaded: '/usr/local/opt/gettext/lib/libintl.8.dylib'
    Referenced from: '/Users/runner/hostedtoolcache/Python/3.10.7/x64/bin/python3.10'
    Reason: tried: '/usr/local/opt/gettext/lib/libintl.8.dylib' (no such file), '/usr/local/lib/libintl.8.dylib' (mach-o file, but is an incompatible architecture (have (arm64), need (x86_64))), '/usr/lib/libintl.8.dylib' (no such file)
```
The arm64 dylib is in there intentionally as part of the build process. But the older cibuildwheels build process didn't pick that up, and it's trying to do that now.

### Build log

https://github.com/pygame/pygame/actions/runs/3209355879/jobs/5245995082

### CI config

https://github.com/pygame/pygame/blob/8d308d54cbf60278d40cd8b22a810e2b4cd58485/.github/workflows/build-macos.yml

**Comment by joerick** [comment]
cibuildwheel itself isn't loading gettext, but python or virtualenv might be. Installing non-native libraries in system locations is likely to cause issues though. It might be better to put these deps somewhere else and link them into the build process with the relevant option - though I don't know what that might be off the top of my head, perhaps `DYLD_LIBRARY_PATH`.

**Comment by ankith26** [comment]
> Installing non-native libraries in system locations is likely to cause issues though. It might be better to put these deps somewhere else and link them into the build process with the relevant option

That is good advice and is likely what I'll have to end up doing. I just brought up this issue because I found it super weird. First of all it only happened when cibuildwheel version was bumped. I don't think cpython 3.8 would have changed much (maybe the patch was bumped, but I'd not expect changes like this to happen in a patch version)... and ofc virtualenv is a pure python package so I don't expect it to look for dependencies like gettext

**Comment by mayeut** [comment]
The version bump includes an action bump which now uses a python version installed by [actions/setup-python](https://github.com/actions/setup-python).
It seems the (pre-installed on runners) python 3.10.7 version is linking against this library which fails to start once the library is modified.

**Comment by ankith26** [comment]
I was able to workaround this issue on my side so I'm fine with this issue being closed if y'all think it's trivial enough. It's not exactly a bug, but it's definitely a change in something.

**Comment by joerick** [comment]
I concur with @mayeut that this is more likely caused by the change in actions/setup-python version.
