### ISSUE TITLE
Option to leave OCI container alive for debugging after build

### ISSUE THREAD

**Issue by Helveg** [pypa/cibuildwheel#1320]
### Description

When experimenting with the local setup, using `cibuildwheel --platform=linux`, for example, a container is created. The container is removed after the build finishes. If the build fails, there's no way to debug what caused it except for the logs. The roundtrip time of adding debug logs are pretty high for big software projects. For myself I've commented out these lines:

https://github.com/pypa/cibuildwheel/blob/f7669045f52f7ffc85ff6a3534b61ea90c00ad1b/cibuildwheel/oci_container.py#L148-L152

But I could PR a proper solution if someone talks me through the requirements, and if everyone agrees this is a good addition for debugging.

**Comment by Helveg** [comment]
@henryiii sorry to tag you, but 1 year later, and still willing to PR this ^_^

**Comment by henryiii** [comment]
I'd be okay with an environment variable to disable the cleanup. CIBW_CONTAINER_DEBUG or something like that? @joerick, @mayeut?

**Comment by joerick** [comment]
Yeah, that would be fine. CIBW_DEBUG_KEEP_CONTAINER might make sense. IMO it doesn't have to go through all the options.py machinery, it can be a simple `os.environ.get`, as we don't care about reading from TOML etc. I think we could add a little section to the bottom of the options documentation page to note little extra options that are more for debugging. The other one that doesn't fit with the other options is CIBW_CACHE_PATH, that could be documented there too.
