### ISSUE TITLE
Feature request: CIBW_AFTER_ALL

### ISSUE THREAD

**Issue by smheidrich** [pypa/cibuildwheel#1329]
### Description

To allow running commands in Linux<sup>1</sup> build containers before any builds are started, cibuildwheel has the [`CIBW_BEFORE_ALL*`](https://cibuildwheel.readthedocs.io/en/stable/options/#before-all) env vars. I would like it if there was a complementary `CIBW_AFTER_ALL` env var to allow running commands after all builds within a container are completed.

This would be useful to e.g. move around cache directories that are specific to the architecture and hence container image used.

In my specific use case, I could probably get around needing this if something like the `CIBUILDWHEEL_BUILD_ARCH` env var from https://github.com/pypa/cibuildwheel/issues/944 was implemented *and* available when the `CIBW_ENVIRONMENT*` env vars are evaluated *and* if that evaluation happened separately for each container, because then I could set an architecture-dependent cached directory outside the container to be used directly instead of having to move it around. But others might need this even then because not all build tools are as flexible with directory locations as Cargo.

Related issues:

- https://github.com/pypa/cibuildwheel/issues/115 requests an env var to specify commands to be executed after *each build*, which can currently be worked around using the test or repair commands

<sup>1 Of course it also works for Mac OS and Windows builds, but in principle it could be replaced by a separate CI step for those and isn't strictly needed.</sup>

**Comment by joerick** [comment]
@smheidrich , just so I understand, what are you wanting to do after the build is finished? My confusion is that the container is going to be deleted once it's closed, so I'm not sure what cleanup tasks would actually affect anything. Or are you thinking that the `after-all` command would run outside the container?

**Comment by smheidrich** [comment]
@joerick The basic problem was to have container-specific cache directories, but I only now found out that `CIBW_ENVIRONMENT` is evaluated _inside_ each container, so the alternative solution I mentioned in the 3rd paragraph above with arch-containing paths defined in `CIBW_ENVIRONMENT` will work (e.g. using `$(uname -m)`) and I no longer need to move cache directories around like I thought I'd have to as a workaround.

So at least for my use case this is no longer needed, if anyone has another reason to need this they can reopen or write a new ticket.

Sorry!
