### ISSUE TITLE
Add support to configure cibuildwheel shell (Github Actions).

### ISSUE THREAD

**Issue by lithomas1** [pypa/cibuildwheel#1338]
### Description

Sometimes you don't want to run the build step under the bash shell, since on the bash shell things such as cl.exe are not part of the PATH.

This is relevant for projects building with meson, since meson is not smart enough to find your VS installation if it's not on the PATH.

**Comment by henryiii** [comment]
You have to specify a shell when making a composite action (at least last I checked); you can't get the auto-change on platform. Also, we use a bash-specific construct to avoid output interleaving. However, we could split it into two steps and put `if: runner.os` (I think if's are supported in composite actions). Also, the output interleaving issues are better know (I hope).
