### ISSUE TITLE
Help with musl overrides in environment variables

### ISSUE THREAD

**Issue by djhoese** [pypa/cibuildwheel#1340]
### Description

I read the documentation regarding musl support, but couldn't find the answer to this so sorry if I missed it. I'm using cibuildwheel in GitHub Actions and in the PR to update to the new cibuildwheel it has failed to install pillow because it is looking for JPEG. I assume the solution is to use apk to install the missing dependencies, but I could only find ways of doing this in pyproject.toml which I'm not using.

https://cibuildwheel.readthedocs.io/en/stable/options/#overrides

Is there a way to control this with environment variables? Or could I put apk and yum install commands in the same LINUX environment variable and cibuildwheel will just try executing all of it?

Here's the pillow error:

```
         __main__.RequiredDependencyException: jpeg
        
        During handling of the above exception, another exception occurred:
        
        Traceback (most recent call last):
          File "<string>", line 36, in <module>
          File "<pip-setuptools-caller>", line 34, in <module>
          File "/tmp/pip-install-hsrc7n2y/pillow_956850d3d8344312a25d1155c5d37071/setup.py", line 1012, in <module>
            raise RequiredDependencyException(msg)
        __main__.RequiredDependencyException:
        
        The headers or library files could not be found for jpeg,
        a required dependency when compiling Pillow from source.
        
        Please see the install instructions at:
           https://pillow.readthedocs.io/en/latest/installation.html
        
```

### Build log

https://github.com/vispy/vispy/actions/runs/3461362501/jobs/5778874457

### CI config

https://github.com/vispy/vispy/blob/dependabot/github_actions/pypa/cibuildwheel-2.11.2/.github/workflows/wheels.yml

**Comment by Czaki** [comment]
Hi @djhoese. 
In general the `CIBW_BEFORE_BUILD_LINUX` passes its content to the shell so `||` operator could be used in command so 
```
 CIBW_BEFORE_BUILD_LINUX: "yum install -y fontconfig || apk add fontconfig; pip install -U pip setuptools; pip install freetype-py"
```
could be used. 

Is there anything that prevents you from migrating to pyroject.toml based config?

**Comment by djhoese** [comment]
> Is there anything that prevents you from migrating to pyroject.toml based config?

My time :stuck_out_tongue_winking_eye:

**Comment by djhoese** [comment]
I should have said: Thanks for the help. I'll try some shell conditions and see if I can get this passing and put it on my TODO list to transition to pyproject.toml for the cibuildwheel configuration.

**Comment by henryiii** [comment]
There are other benefits of TOML configuration, including it's much easier to run locally (which is fantastic in a pinch! I've had to use that when things break more times than I'd like to admit to ;) ). The `||` pattern above is the "classic" way to do it, as @Czaki said.
