### ISSUE TITLE
Python 3.11 wheels not build

### ISSUE THREAD

**Issue by liudonghua123** [pypa/cibuildwheel#1348]
### Description

I try to build an example [package](https://github.com/liudonghua123/python-rtmidi) with `cibuildwheel`, but it only build python up to 3.10. It did not build python 3.11 wheels even I specified `CIBW_BUILD: cp36-* cp37-* cp38-* cp39-* cp310-* cp311-*`.

![image](https://user-images.githubusercontent.com/2276718/203482135-448d2949-5ceb-4248-a6e2-1f4131bb1a40.png)

### Build log

https://github.com/liudonghua123/python-rtmidi/actions/runs/3529576164/jobs/5920712821

### CI config

https://github.com/liudonghua123/python-rtmidi/blob/cb653feb61199e216e46c07f952cbc33200e6924/.github/workflows/wheels.yml

**Comment by Czaki** [comment]
You specify very old cibuildwheel version in your workfow (2.1.2) where latest is 2.11.2. Please update it and it should work.

**Comment by Czaki** [comment]
Because between these two releases cibuildwheel add support for musllinux wheel. Musllinux uses `apk` package installer: Here example in the documentation:

https://cibuildwheel.readthedocs.io/en/stable/options/#examples

**Comment by henryiii** [comment]
You can skip musllinux if you want until you get it working, that's the same as the older cibuildwheels. Or you can use TOML overrides to specify install commands only for musl.

**Comment by henryiii** [comment]
You can also put it into pyproject.toml:

```toml
[tool.cibuildwheel]
skip = "*-musllinux_*"
```

This will also make doing local builds easier or switching/multiple CI providers, etc.
