### ISSUE TITLE
Macos `universal2` wheels are tagged to be used with `x86_64`

### ISSUE THREAD

**Issue by Lunarmagpie** [pypa/cibuildwheel#1349]
### Description

When building wheels for macos I am building wheels for `auto` and `universal2`. In the repairing stage for the `universal2` wheels it raises because there is a wheel already built with the name `pycooldown-0.1.4-cp311-cp311-macosx_12_0_x86_64.whl`.

I also tried only building `universal2`. I did a test install on macos arm64 and it did not fetch the `universal2` wheels form pypi, probably because the name only included `x86_64` as the architecture.

### Build log

[Action](https://github.com/Lunarmagpie/pycooldown/actions/runs/3545269698)
[Log](https://gist.github.com/Lunarmagpie/89857f039e8148e025ec6cabb5f45d0d)

### CI config

https://github.com/Lunarmagpie/pycooldown/blob/482e5d06475c728fd1f0332b6952586dcc15a920/.github/workflows/pypi.yml

**Comment by joerick** [comment]
I can't access the build log above. Could you relink it? But, if I'm guessing, the error is most likely to come from your build backend - not outputting a universal2 wheel when _PYTHON_HOST_PLATFORM is set (to `macosx-10.9-universal2`).

**Comment by Lunarmagpie** [comment]
I relinked the log

**Comment by Lunarmagpie** [comment]
I went and tested on a project that uses `setuptools.build_meta`. It worked so it must be a problem with poetry poetry like you suspected.
