### ISSUE TITLE
Broken delocate version in v2.11.2

### ISSUE THREAD

**Issue by sbrodehl** [pypa/cibuildwheel#1365]
### Description

Hi there!

we have an issue with cibuildwheel `2.11.2` and builds using Python `3.10` on macOS using the default repair command `delocate-wheel ...`.
It looks like there has been an issue with `wheel` + `delocate` (see https://github.com/matthew-brett/delocate/issues/166) which has been fixed in delocate `0.10.3`, and was introduced by `wheel=0.38.1`
However, using version `2.11.2` for cibuildwheels currently fails, because `delocate==0.10.2` has issues with `wheel=0.37.1` (no idea why?! should be fine, was fine before).
Please see the attached CI build log for more details.

The dependency issue seems to be fixed in the main branch, so a new release should fix it?

Looking forward for a new release ;-) or other suggestions as to why the build fails,
Thank you very much!

Here is the error log:
```python
Repairing wheel...
  
  + delocate-wheel --require-archs x86_64 -w <...>/T/cibw-run-aydq2lzz/cp310-macosx_x86_64/repaired_wheel -v <...>/T/cibw-run-aydq2lzz/cp310-macosx_x86_64/built_wheel/lukeparser-0.3.29-cp310-cp310-macosx_10_9_x86_64.whl
  Traceback (most recent call last):
    File "<...>/T/cibw-run-aydq2lzz/cp310-macosx_x86_64/build/venv/bin/delocate-wheel", line 5, in <module>
      from delocate.cmd.delocate_wheel import main
    File "<...>/T/cibw-run-aydq2lzz/cp310-macosx_x86_64/build/venv/lib/python3.10/site-packages/delocate/__init__.py", line 4, in <module>
      from .delocating import delocate_path, delocate_wheel, patch_wheel
    File "<...>/T/cibw-run-aydq2lzz/cp310-macosx_x86_64/build/venv/lib/python3.10/site-packages/delocate/delocating.py", line 46, in <module>
      from .wheeltools import InWheel, rewrite_record
    File "<...>/T/cibw-run-aydq2lzz/cp310-macosx_x86_64/build/venv/lib/python3.10/site-packages/delocate/wheeltools.py", line 19, in <module>
      from wheel.util import native, urlsafe_b64encode
  ImportError: cannot import name 'native' from 'wheel.util' (<...>/T/cibw-run-aydq2lzz/cp310-macosx_x86_64/build/venv/lib/python3.10/site-packages/wheel/util.py)
```

### Build log

https://github.com/lukeparser/lukeparser/actions/runs/3620866874/jobs/6105952560

**Comment by joerick** [comment]
Interesting. Our tests don't actually 'delocate' anything, so we haven't seen this. I'll try to get a new release out shortly.

**Comment by sbrodehl** [comment]
Thank you very much for the quick reply!

I checked the release of 2.11.2 and found the same wheel and delocate versions (see https://github.com/pypa/cibuildwheel/actions/runs/3331757723/jobs/5511898140), so it's hard to tell where the issue was introduced (and what is going on, at least for me!).

It looks to me that the issue is in the cibw environment, is there any way we can set up a test case or run the test above again (from v2.11.2 release)? 
I would like to make sure that this is not something we messed up in out project!

**Comment by henryiii** [comment]
I think if you use pyproject.toml you’ll avoid polluting cibuildwheel’s environment - my guess is something is requiring wheel and forcing an upgrade. Also you don’t need universal=true in setup.cfg, you don’t support python 2 and it’s only for pure Python projects anyway.

**Comment by joerick** [comment]
Ah, I found it - you are updating wheel yourself in `before_build`. https://github.com/lukeparser/lukeparser/actions/runs/3620866874/jobs/6105952560#step:6:1064

**Comment by henryiii** [comment]
Just saw that too! That would do it.

**Comment by joerick** [comment]
I'm imminently releasing v2.11.3, which will bump to the newer version of delocate, which should fix your issue, too.

**Comment by joerick** [comment]
released!

**Comment by sbrodehl** [comment]
Great! Thank you very much!
