### ISSUE TITLE
Update PyPy versions, add macos arm64 PyPy

### ISSUE THREAD

**Issue by mattip** [pypa/cibuildwheel#1369]
### Description

PyPy has released version 7.3.10 which includes macos arm64 versions. This release only has python 3.8 and 3.9.

**Comment by henryiii** [comment]
Also CPython 3.11.1 is out - would make a nice update & release. :)

FYI, I'm on vacation this week so if it's up to me, likely will be early next week. Maybe someone else will be faster. :)

**Comment by mayeut** [comment]
Update available in #1371
I'll prepare a PR with macos arm64 PyPy

**Comment by mayeut** [comment]
@mattip, we're running into https://foss.heptapod.net/pypy/pypy/-/issues/3865 in the macOS tests on AppVeyor (using 10.14)

**Comment by mattip** [comment]
bummer. Is there a way to pin the macos-x86_64 image to 7.3.9?

**Comment by mattip** [comment]
It seems I will release PyPy v7.3.11 within two weeks, which should solve the macos-x86_64 problem.

**Comment by mattip** [comment]
PyPy 7.3.11 is out, it is worth trying to see if it works on the Appveyor images
