### ISSUE TITLE
universal2 wheel build fails on github action macos runner

### ISSUE THREAD

**Issue by jonathanunderwood** [pypa/cibuildwheel#1385]
### Description

When building a universal2 wheel using github actions and a MacOS runner, the build fails to delocate the wheel, as below. This is with cibuildwheel 2.11.4.

```console
Repairing wheel...
  
  + delocate-wheel --require-archs x86_64,arm64 -w /private/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/cibw-run-183j578h/cp311-macosx_universal2/repaired_wheel -v /private/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/cibw-run-183j578h/cp311-macosx_universal2/built_wheel/lz4-4.2.1.dev1+gcae2a15-cp311-cp311-macosx_10_9_universal2.whl
  INFO:delocate.delocating:Copying library /usr/local/Cellar/lz4/1.9.4/lib/liblz4.1.9.4.dylib to lz4/.dylibs/liblz4.1.9.4.dylib
  INFO:delocate.delocating:Modifying install name in lz4/_version.cpython-311-darwin.so from /usr/local/opt/lz4/lib/liblz4.1.dylib to @loader_path/.dylibs/liblz4.1.9.4.dylib
  INFO:delocate.delocating:Modifying install name in lz4/frame/_frame.cpython-311-darwin.so from /usr/local/opt/lz4/lib/liblz4.1.dylib to @loader_path/../.dylibs/liblz4.1.9.4.dylib
  INFO:delocate.delocating:Modifying install name in lz4/block/_block.cpython-311-darwin.so from /usr/local/opt/lz4/lib/liblz4.1.dylib to @loader_path/../.dylibs/liblz4.1.9.4.dylib
  Fixing: /private/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/cibw-run-183j578h/cp311-macosx_universal2/built_wheel/lz4-4.2.1.dev1+gcae2a15-cp311-cp311-macosx_10_9_universal2.whl
  Traceback (most recent call last):
    File "/private/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/cibw-run-183j578h/cp311-macosx_universal2/build/venv/bin/delocate-wheel", line 8, in <module>
      sys.exit(main())
               ^^^^^^
    File "/private/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/cibw-run-183j578h/cp311-macosx_universal2/build/venv/lib/python3.11/site-packages/delocate/cmd/delocate_wheel.py", line 127, in main
      copied = delocate_wheel(
               ^^^^^^^^^^^^^^^
    File "/private/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/cibw-run-183j578h/cp311-macosx_universal2/build/venv/lib/python3.11/site-packages/delocate/delocating.py", line 664, in delocate_wheel
      raise DelocationError(
  delocate.delocating.DelocationError: Some missing architectures in wheel
  Required arch arm64 missing from lz4/_version.cpython-311-darwin.so
  Required arch arm64 missing from lz4/block/_block.cpython-311-darwin.so
  Required arch arm64 missing from lz4/frame/_frame.cpython-311-darwin.so
                                                              ✕ 2.19s
Error: Command delocate-wheel --require-archs x86_64,arm64 -w /private/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/cibw-run-183j578h/cp311-macosx_universal2/repaired_wheel -v /private/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/cibw-run-183j578h/cp311-macosx_universal2/built_wheel/lz4-4.2.1.dev1+gcae2a15-cp311-cp311-macosx_10_9_universal2.whl failed with code 1. None

Error: Process completed with exit code 1.
```

### Build log

https://github.com/python-lz4/python-lz4/actions/runs/3802711010/jobs/6468449369

### CI config

https://github.com/python-lz4/python-lz4/blob/f15636f0b2c8173fee74dfb4ae59537a53531d9e/.github/workflows/build_dist.yml

**Comment by henryiii** [comment]
Your copy of lz4 is not universal. Looks like you are using it from brew - this is not supported, homebrew libraries are explicitly not designed to be portable - and this is especially obvious when it comes to universal builds - they are only native. You'll need a proper universal build of lz4.

**Comment by jonathanunderwood** [comment]
> Your copy of lz4 is not universal. Looks like you are using it from brew - this is not supported, homebrew libraries are explicitly not designed to be portable - and this is especially obvious when it comes to universal builds - they are only native. You'll need a proper universal build of lz4.

Nope - this is building python bindings compiling directly against lz4 upstream sources, not using a system library.

**Comment by henryiii** [comment]
You can brew unlink it, I would suppose. Brew ships by default on the GHA builders. It's handy for tests, but not for redistributable artifacts.

**Comment by jonathanunderwood** [comment]
Yeah. I do actually think there is a bug here. When I build the wheel, I am forcing the extension module to statically link against bundled lz4 sources (I have confirmed this). However, delocate wheel is somehow getting confused with the symbols from the extension module, and the system lz4 dynamic library. Very odd. 

For now I'll try brew unlinking (or removing) the system installed lz4 library, but there is for sure something to fix here, probably with delocate-wheel, rather than cibuildwheel.

**Comment by jonathanunderwood** [comment]
Oh, wait, scratch that - I read the wrong logs....

**Comment by jonathanunderwood** [comment]
I'll close this: @henryiii thank you for your help, much appreciated.
