### ISSUE TITLE
How do I fix cibuildwheels building slowly?

### ISSUE THREAD

**Issue by Strilanc** [pypa/cibuildwheel#1390]
### Description

I really like cibuildwheels, but it has been a huge performance problem in my continuous integration setup. Something I don't understand is *why* it is a huge performance problem. When I build my code base using `make` or `ninja` or `bazel` the build times are a few minutes. But with cibuildwheels these builds take between 10 and 20 minutes. What is taking all the extra time? Is there some option I should be setting to make it go fast?

For example, here is a recent CI run: https://github.com/quantumlib/Stim/actions/runs/3840868002

I've split up the cibuildwheel builds to only do one target per job. For example, here's the job that build the python 3.11 manylinux wheel: https://github.com/quantumlib/Stim/actions/runs/3840868002/jobs/6540431659 . It built and tested the wheel in 10.5 minutes.

For contrast, here's the job that tests that the bazel build is working: https://github.com/quantumlib/Stim/actions/runs/3840868002/jobs/6540429935 . It built the wheel *and* the command line tool *and* the tests *and* the shared library *and* the benchmarks (and ran the tests, of course) in under 7 minutes. On my laptop from a cold start, building the wheel takes about 3 minutes.

I would bet there is something simple going wrong here which, if fixed, would immediately give a factor of 2 reduction in the build times, but I don't know what it is. For example, is it telling python to build using multiple cores? My understanding is github actions has 2 cores available. Do y'all have any ideas? It would be majorly useful to make cibuildwheels twice as fast.

### Build log

https://github.com/quantumlib/Stim/actions/runs/3840868002

### CI config

https://github.com/quantumlib/Stim/blob/main/.github/workflows/ci.yml

**Comment by burgholzer** [comment]
Hey Craig 👋🏻
If I am not mistaken, setuptools' extension builder doesn't automatically parallelize.

I am not sure if it is the easiest way, but you could achieve parallelization by creating your own `Extension` that derives from the standard one and orchestrates the build. We do that for all of our projects, see e.g. https://github.com/cda-tum/qcec/blob/main/setup.py

In the not-so-distant future (or maybe even right now), you could switch to `scikit-build-core` (https://github.com/scikit-build/scikit-build-core), which natively handles parallelization and looks like the future for C/C++ extension modules for python.

Side note: GitHub macOS runners even offer three cores. So you could potentially cut your build time down to 1/3.

**Comment by joerick** [comment]
The slow step for your GHA run is indeed the 'Build wheel' step, which is running

    + python -m pip wheel /project --wheel-dir=/tmp/cibuildwheel/built_wheel --no-deps

This is invoking pip, which in turn invokes your build-backend, which is setuptools. We don't have any control over the speed here, as we've handed off to setuptools. As @burgholzer mentions, there might be some things you play with to improve the speed of that, but I can't see how cibuildwheel could improve anything there. I suppose it's possible some of the difference is due to building inside a Docker container, but that's more-or-less non-negotiable in the wheel-building world.

**Comment by Strilanc** [comment]
Thanks for the explanations.
