### ISSUE TITLE
Cannot repair wheel, because required library "libavahi-common.so.3" could not be located

### ISSUE THREAD

**Issue by dcnieho** [pypa/cibuildwheel#1392]
### Description

I have just set up wheel building through a github action of a package that includes C++ code using cibuildwheel. This build includes distribution of a closed-source .so, and that is giving me all kinds of grief:

1. For manylinux, i am using `quay.io/pypa/manylinux_2_28_x86_64` (how i got there, see 2. below). However, auditwheel fails with `Cannot repair wheel, because required library "libavahi-common.so.3" could not be located`. I have tried on `ubuntu-latest` and `ubuntu-20.04` runners (though i think that shouldn't matter since building happens in the manylinux image?). I do not know how to fix this, how would i go about that? Indeed, the closed-source `libtobii_research.so.1.10.1` that i package in the wheel links to `libavahi-common.so.3`.
2. The reason i even am on `manylinux_2_28_x86_64` and not `2014` (I don't fully oversee the consequences of that choice, but i assume 2014 is default for a good reason) is that once i started to package the .so, auditwheel gave me another error: `auditwheel: error: cannot repair "/tmp/cibuildwheel/built_wheel/TittaPy-1.0.0rc1-cp38-cp38-linux_x86_64.whl" to "manylinux2014_x86_64" ABI because of the presence of too-recent versioned symbols. You'll need to compile the wheel on an older toolchain.`  Using `2_28` fixed that at least. In the end i just need to distribute this wheel and have it work on pretty recent distributions (like Ubuntu 20.04 and newer). If there is another way to achieve that (like telling auditwheel to ignore `libtobii_research.so.1.10.1`, could you fill me in?

Thanks!

### Build log

https://github.com/dcnieho/Titta/actions/runs/3868633650/jobs/6594204153

### CI config

https://github.com/dcnieho/Titta/blob/master/.github/workflows/wheels.yml

**Comment by Czaki** [comment]
You provide `libtobii_research` so file in your repository, but this file to work requires `libavahi-common.so.3`to work. So you need to provide such library in your build environment. Either by install from distribution repository or by provide in repository. 



> 2\. If there is another way to achieve that (like telling auditwheel to ignore `libtobii_research.so.1.10.1`, could you fill me in?

whole problem here is caused that this close source library (`libtobii_research`) is built using too recent gcc version. To build wheels using `manylinux_2014` you need to reach a person who could compile it using an older toolchain.

**Comment by dcnieho** [comment]
@Czaki Thank you! No more hair being pulled. `CIBW_BEFORE_BUILD_LINUX: dnf install -y avahi-libs` was the solution, thanks for putting me on its tracks. I sadly do not think i'll get the closed source dependency to be compiled on an older toolchain, so this'll have to do.
