### ISSUE TITLE
Building macos wheel fails with permission denied

### ISSUE THREAD

**Issue by pranavrth** [pypa/cibuildwheel#1401]
### Description

Hello Team,

I am trying to generate macos wheels in our CI pipeline (Semaphore CI). The wheel generation fails with `Could not install packages due to an EnvironmentError: [Errno 13] Permission denied: '/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/certifi-2022.12.7.dist-info'`

Full Error Log ->

```
Here we go!
Building cp37-macosx_x86_64 wheel
CPython 3.7 macOS x86_64
Installing Python cp37...
+ pkgutil --pkgs
+ Download https://www.python.org/ftp/python/3.7.9/python-3.7.9-macosx10.9.pkg to /private/var/folders/8d/mrnln04n7w929frg6k0y2dt00000gq/T/cibw-run-k_vw_zvi/cp37-macosx_x86_64/build/Python.pkg
+ sudo installer -pkg /private/var/folders/8d/mrnln04n7w929frg6k0y2dt00000gq/T/cibw-run-k_vw_zvi/cp37-macosx_x86_64/build/Python.pkg -target /
installer: Package name is Python
installer: Installing at base path /
installer: The install was successful.
+ /Library/Frameworks/Python.framework/Versions/3.7/bin/python3 /Users/semaphore/semaphore/workspace/.local/lib/python3.10/site-packages/cibuildwheel/resources/install_certifi.py
 -- pip install --upgrade certifi
Collecting certifi
  Using cached certifi-2022.12.7-py3-none-any.whl (155 kB)
Installing collected packages: certifi
ERROR: Could not install packages due to an EnvironmentError: [Errno 13] Permission denied: '/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/certifi-2022.12.7.dist-info'
Consider using the `--user` option or check the permissions.
 
Traceback (most recent call last):
  File "/Users/semaphore/semaphore/workspace/.local/lib/python3.10/site-packages/cibuildwheel/resources/install_certifi.py", line 54, in <module>
    main()
  File "/Users/semaphore/semaphore/workspace/.local/lib/python3.10/site-packages/cibuildwheel/resources/install_certifi.py", line 33, in main
    [sys.executable, "-E", "-s", "-m", "pip", "install", "--upgrade", "certifi"]
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 363, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/Library/Frameworks/Python.framework/Versions/3.7/bin/python3', '-E', '-s', '-m', 'pip', 'install', '--upgrade', 'certifi']' returned non-zero exit status 1.
                                                             ✕ 44.17s
Error: Command ['/Library/Frameworks/Python.framework/Versions/3.7/bin/python3', '/Users/semaphore/semaphore/workspace/.local/lib/python3.10/site-packages/cibuildwheel/resources/install_certifi.py'] failed with code 1. None
 
```

Our script to generate wheel is present here -> [build-wheels.sh](https://github.com/confluentinc/confluent-kafka-python/blob/v2.0.0rc4.dev3/tools/wheels/build-wheels.sh)

I was trying to debug the issue. The exception occurs while executing [install_certifi.py](https://github.com/pypa/cibuildwheel/blob/main/cibuildwheel/resources/install_certifi.py#L33) from [macos.py](https://github.com/pypa/cibuildwheel/blob/main/cibuildwheel/macos.py#L140) 

I feel that the issue is related to installing python with sudo. Can you please have a look and help me here?

**Comment by joerick** [comment]
Hmm. This is strange because the install_certifi.py script is the same script that is distributed with Python for mac, and that is designed to be run by a user by double-clicking - so not with sudo. If I had to guess, I'd wonder if the user Semaphore runs the build as has sudo privileges but isn't a member of the `admin` group. Perhaps in your build you can add the current user to the admin group before running cibuildwheel?

**Comment by pranavrth** [comment]
I feel the same. Python is getting installed with sudo but the current user don't have permission to access the Python folder.

Can we do something here to resolve this?

Currently, I have fixed my issue by installing Python before running the script.

**Comment by joerick** [comment]
This feels like an issue with the CI image, rather than cibuildwheel, since the same procedure works on other CIs and local machines. Feel free to reopen if you/Semaphore disagrees!
