### ISSUE TITLE
all built wheels past the first one are dirty

### ISSUE THREAD

**Issue by akielaries** [pypa/cibuildwheel#1413]
### Description

I have a C++ based project that I am using SWIG, setuptools, and cibuildwheel to publish the a Python binding to PyPI for OSX and Linux. I have had some success previously but as I have made edits to my pipelines I have run into issues with dirty wheels being built. 

Both the OSX & Linux build run simultaneously, both build a **clean first wheel** with the recent tag as the version number, but each wheel built after is tagged as dirty with the commit hash. I tried to do some debugging by checking the `git status` at different stages of my workflows and it seems that nothing is being modified or changed during my build process. 

To my understanding dirty wheels happen when new modifications are made without being included in the most recent commit, in this specific case it appears each newly built wheel that gets stored in the `wheelhouse` directory counts as a new modification that hasn't been committed. 

### Build log

https://gist.github.com/akielaries/38fb461a2dc6cab7aea6fa70833ca477

### CI config

https://github.com/akielaries/openMTPK/blob/main/.github/workflows/openmtpk.yml

**Comment by Czaki** [comment]
Please past the working link to the build log.

**Comment by akielaries** [comment]
My apologies, updates the link for logs.

**Comment by Czaki** [comment]
Did you have a log with `git status` called in `CIBW_BEFORE_BUILD` ?

**Comment by akielaries** [comment]
what would the difference be for declaring `CIBW_BEFORE_BUILD: git status` vs invoking `git status` in a step that occurs directly before the build step is ran. I have tried both, with the latter being what is visible in my log file under the step `Install versioneer` (see [here](https://gist.github.com/akielaries/38fb461a2dc6cab7aea6fa70833ca477#file-failure-log-L538)).

**Comment by akielaries** [comment]
Notice [here](https://gist.github.com/akielaries/38fb461a2dc6cab7aea6fa70833ca477#file-failure-log-L712) where the first wheel being built for OSX is successful and tagged with the correct version VS [here](https://gist.github.com/akielaries/38fb461a2dc6cab7aea6fa70833ca477#file-failure-log-L800) where the wheel being built immediately after is tagged as dirty

**Comment by Czaki** [comment]
`CIBW_BEFORE_BUILD` should be executed before each build (once per python version), when `git status` directly before `cibuildwheel` call only checks if there is no dirty before cibuildwheel call, that is not the case when the first wheel is tagged properly.  

Could you point a log of job with `CIBW_BEFORE_BUILD: git status`?

**Comment by akielaries** [comment]
Let me give this a test to generate a up to date log file. What should be declared along with `CIBW_BEFORE_BUILD`? For example, I previously experimented with `CIBW_BEFORE_BUILD: "git clean -xdfq && git reset --hard HEAD"` as an attempt to set the instance in which the job is running back to the recent commit, therefore ignoring what ever modifications/updates were made in the environment of the github action. However this resulted in the `wheelhouse` directory to be missing/deleted in the process not allowing for the built wheels to reside in one location

**Comment by Czaki** [comment]
So why you just not put wheelhouse in `.gitignore` file?

**Comment by akielaries** [comment]
Thank you very much for this. Super simple fix. The build finally succeeded as expected after ~5 hours.
