### ISSUE TITLE
macosx x86_64 build does not respect MACOSX_DEPLOYMENT_TARGET

### ISSUE THREAD

**Issue by stefanv** [pypa/cibuildwheel#1419]
### Description

We are unable to produce macosx wheels on x86_64 with a tag any other than 12_0.

We set `MACOSX_DEPLOYMENT_TARGET=10.13`.  See [the resulting build log](https://github.com/scikit-image/scikit-image/actions/runs/4176509278/jobs/7232886922).

I've tried various versions of cibuildwheel, all the way back to 2.10.2.

With `SYSTEM_VERSION_COMPAT=1` I could not get the build working.

### Build log

https://github.com/scikit-image/scikit-image/actions/runs/4176509278/jobs/7232886922

### CI config

https://github.com/scikit-image/scikit-image/blob/maintenance/py310-x86_64-macosx/.github/workflows/wheel_tests_and_release.yml

**Comment by Czaki** [comment]
Could you modify the workflow to upload the wheel as an artifact to allow inspecting its files?

**Comment by stefanv** [comment]
For sure: https://github.com/scikit-image/scikit-image/actions/runs/4177707895/jobs/7235613309

**Comment by henryiii** [comment]
I suspect this may be a bug in meson-python? Possibly interaction with an update to something like packaging?

**Comment by Czaki** [comment]
As far as I check all files are correctly compiled to macos 10.13 (see bellow script)

```python
from macholib.MachO import MachO
from macholib.mach_o import version_min_command


def to_version(num):
    return num >> 16, (num >> 8 & 255)


 def check_file(path_):
    m_file = MachO(path_)
    assert len(m_file.headers) == 1
    for cmd, min_ver, _ in m_file.headers[0].commands:
        if isinstance(min_ver, version_min_command):
            return cmd, to_version(min_ver.version)

for p in glob("**/*.so", recursive=True):
    print(p, check_file(p))
```

With output (I do not find any dylib file except libomp that is compatible with 10.9):

```
feature/censure_cy.cpython-310-darwin.so (<load_command cmd=36 cmdsize=16>, (10, 13))
feature/corner_cy.cpython-310-darwin.so (<load_command cmd=36 cmdsize=16>, (10, 13))
feature/_cascade.cpython-310-darwin.so (<load_command cmd=36 cmdsize=16>, (10, 13))
feature/_texture.cpython-310-darwin.so (<load_command cmd=36 cmdsize=16>, (10, 13))
feature/_canny_cy.cpython-310-darwin.so (<load_command cmd=36 cmdsize=16>, (10, 13))
feature/orb_cy.cpython-310-darwin.so (<load_command cmd=36 cmdsize=16>, (10, 13))
feature/brief_cy.cpython-310-darwin.so (<load_command cmd=36 cmdsize=16>, (10, 13))
feature/_hoghistogram.cpython-310-darwin.so (<load_command cmd=36 cmdsize=16>, (10, 13))
feature/_hessian_det_appx.cpython-310-darwin.so (<load_command cmd=36 cmdsize=16>, (10, 13))
feature/_sift.cpython-310-darwin.so (<load_command cmd=36 cmdsize=16>, (10, 13))
feature/_haar.cpython-310-darwin.so (<load_command cmd=36 cmdsize=16>, (10, 13))
measure/_moments_cy.cpython-310-darwin.so (<load_command cmd=36 cmdsize=16>, (10, 13))
measure/_ccomp.cpython-310-darwin.so (<load_command cmd=36 cmdsize=16>, (10, 13))
measure/_marching_cubes_lewiner_cy.cpython-310-darwin.so (<load_command cmd=36 cmdsize=16>, (10, 13))
measure/_pnpoly.cpython-310-darwin.so (<load_command cmd=36 cmdsize=16>, (10, 13))
measure/_find_contours_cy.cpython-310-darwin.so (<load_command cmd=36 cmdsize=16>, (10, 13))
filters/_multiotsu.cpython-310-darwin.so (<load_command cmd=36 cmdsize=16>, (10, 13))
filters/rank/bilateral_cy.cpython-310-darwin.so (<load_command cmd=36 cmdsize=16>, (10, 13))
filters/rank/core_cy.cpython-310-darwin.so (<load_command cmd=36 cmdsize=16>, (10, 13))
filters/rank/generic_cy.cpython-310-darwin.so (<load_command cmd=36 cmdsize=16>, (10, 13))
filters/rank/core_cy_3d.cpython-310-darwin.so (<load_command cmd=36 cmdsize=16>, (10, 13))
filters/rank/percentile_cy.cpython-310-darwin.so (<load_command cmd=36 cmdsize=16>, (10, 13))
util/_remap.cpython-310-darwin.so (<load_command cmd=36 cmdsize=16>, (10, 13))
restoration/_unwrap_3d.cpython-310-darwin.so (<load_command cmd=36 cmdsize=16>, (10, 13))
restoration/_nl_means_denoising.cpython-310-darwin.so (<load_command cmd=36 cmdsize=16>, (10, 13))
restoration/_inpaint.cpython-310-darwin.so (<load_command cmd=36 cmdsize=16>, (10, 13))
restoration/_denoise_cy.cpython-310-darwin.so (<load_command cmd=36 cmdsize=16>, (10, 13))
restoration/_unwrap_2d.cpython-310-darwin.so (<load_command cmd=36 cmdsize=16>, (10, 13))
restoration/_rolling_ball_cy.cpython-310-darwin.so (<load_command cmd=36 cmdsize=16>, (10, 13))
restoration/_unwrap_1d.cpython-310-darwin.so (<load_command cmd=36 cmdsize=16>, (10, 13))
segmentation/_quickshift_cy.cpython-310-darwin.so (<load_command cmd=36 cmdsize=16>, (10, 13))
segmentation/_watershed_cy.cpython-310-darwin.so (<load_command cmd=36 cmdsize=16>, (10, 13))
segmentation/_slic.cpython-310-darwin.so (<load_command cmd=36 cmdsize=16>, (10, 13))
segmentation/_felzenszwalb_cy.cpython-310-darwin.so (<load_command cmd=36 cmdsize=16>, (10, 13))
graph/_mcp.cpython-310-darwin.so (<load_command cmd=36 cmdsize=16>, (10, 13))
graph/_spath.cpython-310-darwin.so (<load_command cmd=36 cmdsize=16>, (10, 13))
graph/_ncut_cy.cpython-310-darwin.so (<load_command cmd=36 cmdsize=16>, (10, 13))
graph/heap.cpython-310-darwin.so (<load_command cmd=36 cmdsize=16>, (10, 13))
_shared/geometry.cpython-310-darwin.so (<load_command cmd=36 cmdsize=16>, (10, 13))
_shared/interpolation.cpython-310-darwin.so (<load_command cmd=36 cmdsize=16>, (10, 13))
_shared/transform.cpython-310-darwin.so (<load_command cmd=36 cmdsize=16>, (10, 13))
_shared/fast_exp.cpython-310-darwin.so (<load_command cmd=36 cmdsize=16>, (10, 13))
morphology/_grayreconstruct.cpython-310-darwin.so (<load_command cmd=36 cmdsize=16>, (10, 13))
morphology/_skeletonize_3d_cy.cpython-310-darwin.so (<load_command cmd=36 cmdsize=16>, (10, 13))
morphology/_convex_hull.cpython-310-darwin.so (<load_command cmd=36 cmdsize=16>, (10, 13))
morphology/_max_tree.cpython-310-darwin.so (<load_command cmd=36 cmdsize=16>, (10, 13))
morphology/_skeletonize_cy.cpython-310-darwin.so (<load_command cmd=36 cmdsize=16>, (10, 13))
morphology/_flood_fill_cy.cpython-310-darwin.so (<load_command cmd=36 cmdsize=16>, (10, 13))
morphology/_extrema_cy.cpython-310-darwin.so (<load_command cmd=36 cmdsize=16>, (10, 13))
io/_plugins/_histograms.cpython-310-darwin.so (<load_command cmd=36 cmdsize=16>, (10, 13))
io/_plugins/_colormixer.cpython-310-darwin.so (<load_command cmd=36 cmdsize=16>, (10, 13))
transform/_warps_cy.cpython-310-darwin.so (<load_command cmd=36 cmdsize=16>, (10, 13))
transform/_radon_transform.cpython-310-darwin.so (<load_command cmd=36 cmdsize=16>, (10, 13))
transform/_hough_transform.cpython-310-darwin.so (<load_command cmd=36 cmdsize=16>, (10, 13))
draw/_draw.cpython-310-darwin.so (<load_command cmd=36 cmdsize=16>, (10, 13))
``` 

But 12.0 tag is set by `wheel`, so it looks like this line causes the problem 

https://github.com/pypa/wheel/blob/895558fc74f694dc6132723cfee58752d14c1482/src/wheel/bdist_wheel.py#L49

could you add run of this `python -c "import sysconfig; print(sysconfig.get_platform())"` in your build process? (for example in `CIBW_BEFORE_BUILD`) to check what is returned by `sysconfig`?

**Comment by stefanv** [comment]
```
  platform: macosx-10.9-x86_64
```

https://github.com/scikit-image/scikit-image/actions/runs/4178626078/jobs/7237638409#step:5:166

**Comment by Czaki** [comment]
At this moment, I do not have an idea. I would start from fork wheel and add more debug prints to understand. As everything looks correct, but the tag is set incorrectly. 

The only thing that is in my mind here is that something is updating `MACOSX_DEPLOYMENT_TARGET` before the call of `wheel`.

**Comment by henryiii** [comment]
I thought we removed wheel from meson-python? https://meson-python.readthedocs.io/en/latest/changelog.html#id2

**Comment by stefanv** [comment]
I wonder if this is a mistake in the Meson documentation, or a mistake in their implementation. Their variable is called `MACOS_DEPLOYMENT_TARGET`:

https://meson-python.readthedocs.io/en/latest/reference/environment-variables.html

**Comment by stefanv** [comment]
Err, that seems to be it: https://github.com/scikit-image/scikit-image/actions/runs/4178925700/jobs/7238290441

/cc @eli-schwartz bug or feature?

**Comment by Czaki** [comment]
> I thought we removed `wheel` from meson-python? [meson-python.readthedocs.io/en/latest/changelog.html#id2](https://meson-python.readthedocs.io/en/latest/changelog.html#id2)

It is my bad that I assume that meson is using build. But as I check code this change looks like regressions. 

When I check this code: 
https://github.com/mesonbuild/meson-python/blob/d75f4cd9df80c086ee1efeda346b74cf8e1ae0b9/mesonpy/_tags.py#L93 

There are no querying files for the minimum macOS version like in wheel https://github.com/pypa/wheel/blob/895558fc74f694dc6132723cfee58752d14c1482/src/wheel/macosx_libfile.py#L392. 
`delocate` also does not do this (I lost access to the macOS machine, and no one grab the topic).

**Comment by eli-schwartz** [comment]
IMO this is a typo regression introduced in https://github.com/mesonbuild/meson-python/commit/9e84bd993c359721c3011cddd7f2403e5b019f74

**Comment by stefanv** [comment]
Closed by https://github.com/mesonbuild/meson-python/pull/309
