### ISSUE TITLE
`--config-settings` is passed as `--config-setting`

### ISSUE THREAD

**Issue by Schamper** [pypa/cibuildwheel#1429]
### Description

Whenever I try to use the feature to pass `--config-settings` (either through environment variable or `pyproject.toml`), I am met with a `no such option: --config-setting` error in the logs.

A cursory look at the pip documentation seems to suggest the argument name actually is `--config-settings`:
https://pip.pypa.io/en/stable/cli/pip_wheel/#cmdoption-config-settings

It looks like the options that should be passed as `--config-settings` are actually being passed as `--config-setting` (missing the `s`):

https://github.com/pypa/cibuildwheel/blob/acdbe87e3d002598b10435bb6f17bae758418ba8/cibuildwheel/util.py#L213

**Comment by henryiii** [comment]
Build and pip differ here. So it (should be) conditional. (If you use the `build` backend, I expect it works currently).

**Comment by joerick** [comment]
Fixed in v2.12.1
