### ISSUE TITLE
Unable to build ARM64 Windows wheels on Github

### ISSUE THREAD

**Issue by Marco-Sulla** [pypa/cibuildwheel#1441]
### Description

The error:

> This version of %1 is not compatible with the version of Windows you're running. Check your computer's system information and then contact the software publisher

I'm using windows-latest.

Full stacktrace and pipeline are attached.

PS: I use 2.8.1 because for the moment I still want to build 3.6 wheels.
PPS: I'm a fan of RISC.

### Build log

https://pastebin.com/amZsBP0V

### CI config

https://github.com/Marco-Sulla/python-frozendict/blob/a70d95f1088f77f7644152242dd753bef65348c6/.github/workflows/build_wheels.yml

**Comment by joerick** [comment]
Hey. Not sure what's going on with your error, but

- You can build 3.6 wheels with the latest cibuildwheel.
- The ability to build ARM64 windows wheels (cross-compiled) was [added in v2.11.0](https://cibuildwheel.readthedocs.io/en/stable/changelog/#v2110). So you should be using a newer version of cibuildwheel.

**Comment by Marco-Sulla** [comment]
Hi Joe.

> You can build 3.6 wheels with the latest cibuildwheel.

Well, indeed in the [2.9 changelog](https://cibuildwheel.readthedocs.io/en/stable/changelog/#v290) is stated:

> However, cibuildwheel continues to build CPython 3.6 wheels for the moment.

So I can simply change the version and the 3.6 wheel will continue to build? I'll give it a try.

**Comment by Marco-Sulla** [comment]
It works now with the latest version, and 3.6 wheels continue to be built. Thank you.

PS: do you know if there's a way to get informed about new releases?

**Comment by henryiii** [comment]
GitHub has a subscribe to new releases option under “watch”. Also many of us use the action + dependabot.

**Comment by joerick** [comment]
> > However, cibuildwheel continues to build CPython 3.6 wheels for the moment.
> 
> So I can simply change the version and the 3.6 wheel will continue to build? I'll give it a try.

I'll try to be more explicit in the next release notes that we drop a host version - it is admittedly slightly confusing.
