### ISSUE TITLE
Run before-build commands as optional

### ISSUE THREAD

**Issue by b3n3w** [pypa/cibuildwheel#1449]
### Description

Hi there, 

Is there an option to make the before-build commands optional ? Looking at the docs it seems like there is currently no parameter to do that. We need to obfuscate parts of our code in specific cases for every python version. Therefore, i would like to define when its needed and when not. 

The example shown below would always run this command before building the wheels.
```
before-build = "bash scripts/obfuscate_lib.sh"
``` 
For our internal wheels we don't want to have the code to be obfuscated. So in this scenario i would expect a custom argument like to define if the before-build command is required or not. 

 ```
cibuildwheel --platform linux --skip-before-build
```

**Comment by Czaki** [comment]
I think that you may look for configuration overrides: https://cibuildwheel.readthedocs.io/en/stable/options/#overrides

But in general, you copy configuration from `pyproject.toml`, when you should have the individual configurations for each project/wheel.

**Comment by b3n3w** [comment]
Hi Czaki, 
thanks for your quick response. Unfortunately this fits not really in the case. I would like to build the exact same project once with an obfuscation and one without. The wheels should be named the same. 

Does this mean we would need a separate pyproject.toml to archive this ?

**Comment by Czaki** [comment]
Maybe you could use environment variable to control if obsuscation script should be executed 

Something like 

```python
If os.environ.get("SKIP_OBFUSC", "0") == "1":
    sys.exit()
```

**Comment by henryiii** [comment]
Can't you override before-build by environment variable?

```console
$ CIBW_BEFORE_BUILD="echo empty" cibuildwheel --platform linux
```

You probably need something, as an empty environment variable is treated like no environment variable usually, but you can just stick something like `echo` there.

**Comment by henryiii** [comment]
Okay to close?

**Comment by b3n3w** [comment]
Yes 
Thank you !
