### ISSUE TITLE
Support for wasm32-emscripten wheels

### ISSUE THREAD

**Issue by hoodmane** [pypa/cibuildwheel#1454]
@henryiii has discussed adding a wasm32-emscripten target to cibuildwheel in the past. I would like to help with this. Currently it is not super invasive to build such wheels.

Here's numpy's CI support for Emscripten using `pyodide build`:
https://github.com/numpy/numpy/blob/main/.github/workflows/emscripten.yml

Rust + Python projects can directly use maturin:
https://github.com/pydantic/pydantic-core/blob/main/Makefile#L46

There's currently not all that many examples of projects building against Emscripten in their CI, but I would like to change that!. I think a lot of maintainers are enthusiastic about the concept.

**Comment by joerick** [comment]
I'm keen for this too. WASM is the next universal VM architecture! Looks like pyodide have done a lot of work to make this easier.

Why do we target wasm32 - a 32bit architecture? Is that the most common?

We don't want to depend on the setup-emsdk action, so we'd have to roll that functionality in. Luckily, that's [pretty simple](https://github.com/mymindstorm/setup-emsdk/blob/master/src/main.ts#L48-L95).

We'd also have to decide if it should be enabled by default, as I don't think PyPI is accepting these wheels yet.

**Comment by hoodmane** [comment]
> Why do we target wasm32 - a 32bit architecture? Is that the most common?

Well:
1. wasm64 doesn't really exist yet (it's specced but not implemented)
2. 32 bit pointers make code size much smaller
3. wasm is a harvard architecture -- function pointers and data pointers live in different address spaces. This reduces the amount of stuff in the address space by a fair amount. 

So far very few people are running into the 4 gb limit.

**Comment by hoodmane** [comment]
I notice that `build-frontend` defaults to `pip`. We can't really use `pip` as the build frontend for Pyodide at this point. Can I just print a warning and ignore this setting?

**Comment by hoodmane** [comment]
I don't think we'll need it to be on docker.

**Comment by hoodmane** [comment]
Successfully built and tested multidict:

![Screenshot from 2023-04-04 14-50-04](https://user-images.githubusercontent.com/8739626/229930457-46fd023b-6420-40eb-9197-98d5fae78306.png)

**Comment by hoodmane** [comment]
I'm trying to build numpy now but it pins `wheel==0.38.1` in it's build requires whereas `cibuildwheel/resources/constraints-python310.txt` has `wheel==0.40.0`. Am I using the cibuildwheel constraints file wrong?

**Comment by hoodmane** [comment]
It looks like numpy pins `cibuildwheel==2.12.0` which may have something to do with the wheel version...

**Comment by henryiii** [comment]
Yes, environments are pinned by cibuildwheel version (unless you request otherwise, via https://cibuildwheel.readthedocs.io/en/stable/options/#dependency-versions )

How is numpy pinning cibuildwheel if you are building it?

**Comment by henryiii** [comment]
As for the build frontend, I'd say ideally make it a warning or even an error if a user specifically sets it to `pip`, but no warning/error if it's unset, if possible. Not sure when we think we might want to change the default.

**Comment by hoodmane** [comment]
Numpy pins the version here: https://github.com/numpy/numpy/blob/main/tools/ci/cirrus_general.yml#L3
I get a crash because of the wheel version conflict. I removed one of the wheel versions and now I successfully build the wheel. Working on getting the numpy tests to run...
