### ISSUE TITLE
Local macosx build doesn't recognize homebrew Python

### ISSUE THREAD

**Issue by hoodmane** [pypa/cibuildwheel#1459]
### Description

```
$ which python3.11
/opt/homebrew/bin/python3.11
$ cibuildwheel --only cp311-macosx_arm64
Error: CPython 3.11 is not installed.
```
Would it make sense to accept that Python is installed if `shutil.which("python3.11")` finds something?

**Comment by henryiii** [comment]
You can't build redistributable wheels with homebrew Python; it's not compiled with 10.9 compatibility and it's not compiled universal either. You need the Python.org Python on macOS, that's one of the features of cibuildwheel. I thought it was supposed to download and install Python for you, though.

**Comment by hoodmane** [comment]
It's only willing to do the auto install in CI. Thanks for explaining!
