### ISSUE TITLE
pydantic doesn't seem to use cibuildwheel

### ISSUE THREAD

**Issue by hoodmane** [pypa/cibuildwheel#1463]
pydantic is listed as an example here:
https://cibuildwheel.readthedocs.io/en/stable/working-examples/
grepping for cibuildwheel doesn't seem to show anything (@samuelcolvin ?)

**Comment by henryiii** [comment]
Looks like it’s been moved to PyO3/maturin-action (unless it was mistakenly added, which is also possible). Which is fine for Rust, I’m not sure if if handles macOS properly, but I know it handles manylinux for Rust better than we do - for Rust, you don’t generally need (or want) the manylinux docker images.

**Comment by samuelcolvin** [comment]
We used to use it, still do on v1.10, but not on main.
