### ISSUE TITLE
BUG?: Uploaded wheels differ from CI artifacts

### ISSUE THREAD

**Issue by HaoZeke** [pypa/cibuildwheel#1490]
### Description

Wheels downloaded from the CI are correct, but when installed from PYPI:

```bash
  Created wheel for pypotlib: filename=pypotlib-0.0.11-cp38-cp38-linux_x86_64.whl size=9445043 sha256=535f28f78d2b2e0df4a0c88d43a17595de6e331f352124387aad5b006636eaeb
  Stored in directory: /home/rgoswami/.cache/pip/wheels/3e/62/73/cdd94343f38a0df108501d5dda9e3be669ae547e418a66d249
Successfully built pypotlib
Installing collected packages: pypotlib
Successfully installed pypotlib-0.0.11
❯ python
iPython 3.8.0 | packaged by conda-forge | (default, Nov 22 2019, 19:11:38) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pypotlib
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/rgoswami/Git/Github/Theochem/pypotlib/.py38/lib/python3.8/site-packages/pypotlib/__init__.py", line 1, in <module>
    from pypotlib import cpot
ImportError: /home/rgoswami/Git/Github/Theochem/pypotlib/.py38/lib/python3.8/site-packages/pypotlib/cpot.cpython-38-x86_64-linux-gnu.so: undefined symbol: PyThreadState_GetFrame
>>> exit()
```

It appears then that the wheel uploaded to PyPi is not the correct cp38 release, but instead is the cp311 one.

### Build log

https://github.com/TheochemUI/pypotlib/actions/runs/4885927262

### CI config

https://github.com/TheochemUI/pypotlib/actions/runs/4885927262/workflow

**Comment by henryiii** [comment]
You can't upload `linux` wheels to PyPI. Only `manylinux` or `musllinux` wheels. You are disabling the conversion of linux to manylinux here:

https://github.com/TheochemUI/pypotlib/blob/8cd98433572375049467400931b439afab01e4a2/pyproject.toml#L37

And then you break the artifact upload here:

https://github.com/TheochemUI/pypotlib/blob/8cd98433572375049467400931b439afab01e4a2/.github/workflows/build_wheels.yml#L35

So no wheels are being uploaded at all:

https://pypi.org/project/pypotlib/#files

You are then trying to build the file locally, and you probably didn't install the Conda compilers.

Also, why are you using conda to build an SDist? https://github.com/TheochemUI/pypotlib/blob/8cd98433572375049467400931b439afab01e4a2/.github/workflows/build_wheels.yml#L45

Why are you installing wheel and setuptools to build with meson? https://github.com/TheochemUI/pypotlib/blob/8cd98433572375049467400931b439afab01e4a2/pyproject.toml#L24 (One reason could be if dependencies are missing pyproject.toml's, but then you are building too many wheels)

Why are you pre-installing cmake and meson? meson-python should pull in meson. https://github.com/TheochemUI/pypotlib/blob/8cd98433572375049467400931b439afab01e4a2/pyproject.toml#L31-L33

**Comment by HaoZeke** [comment]
Ack, thanks for the detailed comments @henryiii.

**Comment by henryiii** [comment]
Sure, feel free to ask if you have any issues after trying those things!

**Comment by henryiii** [comment]
FYI, you need to tell auditwheel where it can find libfmt.so so it can bundle it in.

**Comment by HaoZeke** [comment]
In this case I ended up removing `fmt` from the underlying C++ project since I was only using it for STDOUT. I thought it should have been picked up automatically since its also a `meson wrap` dependency, like `eigen` and `pybind11`.. Does `auditwheel` need `LD_LIBRARY_PATH` to be set? I couldn't seem to find a flag for library locations in the `auditwheel repair --help`...

**Comment by eli-schwartz** [comment]
> In this case I ended up removing `fmt` from the underlying C++ project since I was only using it for STDOUT. I thought it should have been picked up automatically since its also a `meson wrap` dependency, like `eigen` and `pybind11`..

eigen and pybind11 are both header-only libraries, while fmt builds its own objects. For wrap usage, it probably makes a lot of sense to pass the `default_options: ['default_library=static']` option to that dependency(), to make sure that when building it in vendored mode you link with a static library -- then you don't have to bundle anything at all.
