### ISSUE TITLE
Missing Python3 symlink for Windows

### ISSUE THREAD

**Issue by lithomas1** [pypa/cibuildwheel#1496]
### Description

When using cibuildwheel on Windows,
the selected Python version (in this case Python 3.11) doesn't seem to be symlinked to the ``python3`` command.

See the highlighted line in
https://github.com/pandas-dev/pandas/actions/runs/4877296328/jobs/8701796777#step:3:210
for example.

(The Python3 pointed there is the default one that comes with Github Actions).

I am on cibuildwheel 2.12.3 by the way.

### Build log

https://github.com/pandas-dev/pandas/actions/runs/4877296328/jobs/8701796777#step:3:210

**Comment by joerick** [comment]
Hrm... I thought we had a test for this. Ah, we actually only test that `python` resolves to the correct executable, not `python3`. 
Are you able to use `python` instead?

I wonder if the removal of this executable from CPython Windows distribution was deliberate?

**Comment by joerick** [comment]
Did `python3` work on previous versions of CPython?

**Comment by mayeut** [comment]
I think `python3` is Unix only and always has been. I don't have a windows system to check wether venv/virtualenv used to create a python3 executable.
For GHA installed python on windows, the python3 executable does not come from the official python installer but from a symlink created by the GHA installer on top of that: https://github.com/actions/python-versions/blob/256e6ddd5702c2232851d7602f14b68867efc6f1/installers/win-setup-template.ps1#L130-L133

**Comment by lithomas1** [comment]
I haven't tested if it works on previous versions of CPython. 

Do you know if there's a way to force Python3 across all platforms then?

On cibuildwheel, just using ``python`` works, but I'm worried that ``python`` might point to Python 2 for e.g. some Linux users.

(The context is that I have a Python script that runs during the build process to set the version of my package)

**Comment by Czaki** [comment]
It looks like the proper solution will be to use https://mesonbuild.com/Python-module.html#find_installation to determine the python used for installing pandas.

**Comment by lithomas1** [comment]
Ah, makes sense. This seems to be a meson limitation then, where it blocks the Python module from being used in the ``project`` declaration.
Thanks for all the help.
