### ISSUE TITLE
repair wheel command fails on macos without clear reason

### ISSUE THREAD

**Issue by brenthuisman** [pypa/cibuildwheel#1497]
### Description

See title. The command (`delocate-wheel`) errors out with `UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd1 in position 396537: invalid continuation byte`, see log.

I trawled all possibly relevant changelogs but couldn't find anything that might be related to this error. The workaround is setting the repair command to `""` for the moment, since no libraries were bundled anyway, but I still would like to know why this happens.

### Build log

https://github.com/arbor-sim/arbor/actions/runs/4904892311/jobs/8758317425#step:7:10823

### CI config

https://github.com/arbor-sim/arbor/actions/runs/4904892311/workflow

**Comment by brenthuisman** [comment]
Sure https://github.com/matthew-brett/delocate/issues/181

Still, that project has had no changes since January (and very little activity in general), so it's something else or an interaction with a change in environment.

**Comment by joerick** [comment]
`unzip` prints the filenames of the files as it extracts them, so I'm guessing there's a filename in the wheel that doesn't encode as utf-8 correctly.

**Comment by brenthuisman** [comment]
There is an upstream fix. Our problem is that somehow a copy of our source tree (which includes that file) is ending up in the wheel, but that's on us.
