### ISSUE TITLE
Build types that pass the tests get removed when either one fails

### ISSUE THREAD

**Issue by gurgenyegoryan** [pypa/cibuildwheel#1531]
### Description

I am building Python using the command `python3 -m cibuildwheel --platform linux` . It should build versions `cp37`, `cp38`, `cp39`, `cp310`, and `cp311`. However, when a test fails in one package, the process stops and deletes the container, along with all the .whl files for which the test had passed. I would like to extract the files for which the test has passed. Unfortunately, I haven't found any options in the `pyproject.toml` file that could solve this issue.

**Comment by henryiii** [comment]
I think this is #1062.

**Comment by gurgenyegoryan** [comment]
It will move those `.whl` files into `/output` on which the test passed, so after adding `continue-on-failure`, if for example it passed on the first build, but the test did not pass, it will not move the file into `/output` and will continue to `build/repair /test` on other `platforms/python versions` , did I understand you correctly?

**Comment by henryiii** [comment]
`continue-on-failure` hasn't been implemented yet. But I think the plan is that all successful outputs would be produced, and you'd still get an error code with a message about what failed.

I'm not sure about how failure-to-build vs. failure-to-test should be handled, though.

**Comment by gurgenyegoryan** [comment]
@reynoldsnlp Ok, thanks!
