### ISSUE TITLE
Building arm64 on macos runners pip install x86 dependencies

### ISSUE THREAD

**Issue by makslevental** [pypa/cibuildwheel#1547]
### Description

Title says it all: I'm building arm64 wheels on the macos github runners using 

```
      - name: Build wheels
        uses: pypa/cibuildwheel@v2.14.0
        env:
          CIBW_ARCHS_MACOS: arm64
          CIBW_ARCHS_LINUX: x86_64
```

and cibuildwheel is somehow passing the wrong flags somewhere such that *some* of the wheels pip installs are the wrong arch. Smoking gun lines:

[cmake is arm64/universal](https://gist.github.com/makslevental/eca6f5d6f702f0c35c29b3e3b7a1ab81#file-gistfile1-txt-L845)
[numpy is x86](https://gist.github.com/makslevental/eca6f5d6f702f0c35c29b3e3b7a1ab81#file-gistfile1-txt-L856)

Most importantly for me, a dependency ([mlir](https://gist.github.com/makslevental/eca6f5d6f702f0c35c29b3e3b7a1ab81#file-gistfile1-txt-L868)) that I own and distribute through `--extra-index-url` also has the x86 wheel installed rather than the arm64 wheel. 

All of this of course comes to a crashing hault during compile where unsurprisingly there's a [failure to link](https://gist.github.com/makslevental/eca6f5d6f702f0c35c29b3e3b7a1ab81#file-gistfile1-txt-L1415-L1416).

Note I have tried to use

```
before-all = [
    "export PIP_PLATFORM=macosx_11_0_arm64",
    "export PIP_ONLY_BINARY=:all:",
]
```

but it has no effect.

### Build log

https://gist.githubusercontent.com/makslevental/eca6f5d6f702f0c35c29b3e3b7a1ab81/raw/63bd64ccfec997571a6f6de5571f84bcb853407c/gistfile1.txt

### CI config

https://github.com/makslevental/nelli/blob/0870bc65d74245362c2e4a983883f50170d156eb/.github/workflows/build.yml

**Comment by oscargm98** [comment]
We are having the same problem at https://github.com/Blosc/blosc2_plugin_example:
https://github.com/Blosc/blosc2_plugin_example/actions/runs/5691535171/job/15426966313
We obtain the next warning: "Ignoring file /private/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/pip-build-env-dqt03i0k/overlay/lib/libblosc2.dylib, building for macOS-arm64 but attempting to link with file built for macOS-x86_64"

Here you can see how the Mac arm64 task installs x86_64 dependencies:
```
Installing build dependencies: started
    Collecting setuptools
      Using cached setuptools-68.0.0-py3-none-any.whl (804 kB)
    Collecting scikit-build
      Downloading scikit_build-0.17.6-py3-none-any.whl (84 kB)
         ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 84.3/84.3 kB 3.1 MB/s eta 0:00:00
    Collecting cmake
      Downloading cmake-3.27.0-py2.py3-none-macosx_10_10_universal2.macosx_10_10_x86_64.macosx_11_0_arm64.macosx_11_0_universal2.whl (47.4 MB)
         ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 47.4/47.4 MB 6.0 MB/s eta 0:00:00
    Collecting ninja
      Downloading ninja-1.11.1-py2.py3-none-macosx_10_9_universal2.macosx_10_9_x86_64.macosx_11_0_arm64.macosx_11_0_universal2.whl (270 kB)
         ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 270.7/270.7 kB 8.1 MB/s eta 0:00:00
    Collecting blosc2
      Downloading blosc2-2.2.5-cp38-cp38-macosx_10_9_x86_64.whl (4.3 MB)
         ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.3/4.3 MB 17.4 MB/s eta 0:00:00
    Collecting distro (from scikit-build)
      Downloading distro-1.8.0-py3-none-any.whl (20 kB)
    Collecting packaging (from scikit-build)
      Using cached packaging-23.1-py3-none-any.whl (48 kB)
    Collecting tomli (from scikit-build)
      Downloading tomli-2.0.1-py3-none-any.whl (12 kB)
    Collecting wheel>=0.32.0 (from scikit-build)
      Downloading wheel-0.41.0-py3-none-any.whl (64 kB)
         ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 64.7/64.7 kB 2.6 MB/s eta 0:00:00
    Collecting msgpack (from blosc2)
      Downloading msgpack-1.0.5-cp38-cp38-macosx_10_9_x86_64.whl (73 kB)
         ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 73.2/73.2 kB 3.6 MB/s eta 0:00:00
    Collecting ndindex>=1.4 (from blosc2)
      Downloading ndindex-1.7-py3-none-any.whl (85 kB)
         ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 85.7/85.7 kB 5.8 MB/s eta 0:00:00
    Collecting numpy>=1.20.3 (from blosc2)
      Downloading numpy-1.24.4-cp38-cp38-macosx_10_9_x86_64.whl (19.8 MB)
         ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 19.8/19.8 MB 8.3 MB/s eta 0:00:00
    Collecting py-cpuinfo (from blosc2)
      Downloading py_cpuinfo-9.0.0-py3-none-any.whl (22 kB)
    Installing collected packages: py-cpuinfo, ninja, msgpack, cmake, wheel, tomli, setuptools, packaging, numpy, ndindex, distro, scikit-build, blosc2
    Successfully installed blosc2-2.2.5 cmake-3.27.0 distro-1.8.0 msgpack-1.0.5 ndindex-1.7 ninja-1.11.1 numpy-1.24.4 packaging-23.1 py-cpuinfo-9.0.0 scikit-build-0.17.6 setuptools-68.0.0 tomli-2.0.1 wheel-0.41.0
```

**Comment by Czaki** [comment]
Cross compilation means only cross compilation. As runners are x86 they cannot execute ARM64 code. All binaries need to be dynamically linked against other python packages. If you need to statistically link against another package then I think you need to use native runner.

**Comment by makslevental** [comment]
> Cross compilation means only cross compilation.

By far the weirdest take I have ever seen. Especially since what's actually happening is not that the toolchain can't link but that the wrong wheels are getting downloaded (and if you patch things up so that the right wheels get downloaded then the linking succeeds just fine).

**Comment by Czaki** [comment]
I just noticed that you use:

> ```
> before-all = [
>     "export PIP_PLATFORM=macosx_11_0_arm64",
>     "export PIP_ONLY_BINARY=:all:",
> ]
> ```

It will not work as every command has its own shell. You need to use the environment section: https://cibuildwheel.readthedocs.io/en/stable/options/#environment but it will impact all build tools also. 

I do not understand why linking is required, as user will install own numpy version

**Comment by FrancescAlted** [comment]
> I do not understand why linking is required, as user will install own numpy version

In our case (https://github.com/Blosc/blosc2_plugin_example), we do need linking because it is the way to automatically register a plugin to be dynamically loaded inside Blosc2.  I agree with @makslevental that, if getting the right wheels for the arch (arm64 in this case) would be possible, the linking would succeed.

**Comment by makslevental** [comment]
> It will not work as every command has its own shell. You need to use the environment section: https://cibuildwheel.readthedocs.io/en/stable/options/#environment but it will impact all build tools also.

I was [aware](https://github.com/makslevental/nelli/blob/0870bc65d74245362c2e4a983883f50170d156eb/pyproject.toml#L24) of environment but (somehow) missed that each command runs in its own shell (makes sense). But this idea, while maybe closer doesn't work because during the `Installing build tools` pip will fail to install with [`ERROR: Can not use any platform or abi specific options unless installing via '--target'`](https://github.com/makslevental/nelli/actions/runs/5694339840/job/15435345173#step:4:137).

> I do not understand why linking is required, as user will install own numpy version

This was just an example/proof positive that the fail was what I claimed it was (mismatch in archs). My real issue, just as @FrancescAlted, is I link against libs during build of my wheel and those libs are also in a (arch tagged) wheel.

**Comment by Czaki** [comment]
> This was just an example/proof positive that the fail was what I claimed it was (mismatch in archs). My real issue, just as @FrancescAlted, is I link against libs during build of my wheel and those libs are also in a (arch tagged) wheel.

but if I correctly understand this way of doing this make a problem when user install different version of package than is used when creating wheels as there will be used two different versions of same library? I think that you should think about runtime loading library. 

@oscargm98 your links to https://github.com/Blosc/blosc2_plugin_example return 404, does this repository is private?

**Comment by makslevental** [comment]
> but if I correctly understand this way of doing this make a problem when user install different version of package than is used when creating wheels as there will be used two different versions of same library?

Seems you do not understand correctly - I am **statically** linking the libs in the wheel I depend on.

> I think that you should think about runtime loading library.

Do you know what I think? I think the biggest plague in software is people mistakenly, arrogantly, assuming a case of [xy](https://xyproblem.info/) when it really is x. So I think you should think about whether being condescending, insisting on covering up a bug, is the right way to approach OSS dev.

**Comment by Czaki** [comment]
> Seems you do not understand correctly - I am **statically** linking the libs in the wheel I depend on.

so then download wheel (install to target dir in `before-build` steep) and link against it in `setup.py` (the environment variable `CIBUILDWHEEL=1` is always defined) when building in CI.

 

> So I think you should think about whether being condescending, insisting on covering up a bug, is the right way to approach OSS dev.

This what you try to do is a way to produce multiple hard-to-debug bugs. For example random segfaults. But if you still think that it is bug then go to setuptools, pip or build project. Here we only set environment variables for MacOS.  

> Do you know what I think? I think the biggest plague in software is people mistakenly, arrogantly, assuming a case of [xy](https://xyproblem.info/) when it really is x.

as I mention above. Using multiple versions of the same library, even if it is statistically linked is error-prone. I do not know how you use it here, so I do not know if it could cause errors in your case. But supporting it by default is not the best idea.

**Comment by makslevental** [comment]
This is the last time I'm going to explain this (and afterwards I'm going to fork):

> so then download wheel (install to target dir in `before-build` steep) and link against it in `setup.py` (the environment variable `CIBUILDWHEEL=1` is always defined) when building in CI.

You're saying I should by-hand download a wheel for my specific arch and system and then move it to the build directory and figure out the paths and etc etc etc **when pip is exactly already the tool for this and my dep is a wheel**. This makes exactly **zero sense**.

> This what you try to do is a way to produce multiple hard-to-debug bugs.

That's your opinion and you are welcome to it but I didn't ask you your opinion on this (how I should build and package my code).

> For example random segfaults. But if you still think that it is bug then go to setuptools, pip or build project. Here we only set environment variables for MacOS.

Yes and you're very clearly setting the wrong environment variables **if wheels for two different arches are being downloaded**.

> as I mention above. Using multiple versions of the same library, even if it is statistically linked is error-prone. I do not know how you use it here, so I do not know if it could cause errors in your case.

Again, this is completely outside of the realm of something you can have input on **when it comes to my software**.

> But supporting it by default is not the best idea.

You're not supporting to me by fixing this bug, you're fixing a bug **in your code**.

**Comment by Czaki** [comment]
> Yes and you're very clearly setting the wrong environment variables **if wheels for two different arches are being downloaded**.

Both `universal2` and `x86_64` are proper platform tags for arch `x86_64` Both contain `x86_64` code. The `universal2` contains, in addition, `arm64` code. This is wheel author decision if they would like to upload two separated wheels of single universal one. So it download single architecture.



> You're not supporting to me by fixing this bug, you're fixing a bug **in your code**.

Even if I agree that this is bug it is still bug in the build backend, not in cibuildwheel.   



> You're saying I should by-hand download a wheel for my specific arch and system and then move it to the build directory and figure out the paths and etc etc etc **when pip is exactly already the tool for this and my dep is a wheel**. This makes exactly **zero sense**.

so you could use `--pltform` and `--target` to download. Downloading wrong arch may lead to non-working environment if package is imported/used during build process. Simple `np.get_include()` may be enough to crash the build process.

**Comment by FrancescAlted** [comment]
We have fixed this by avoiding linking against the blosc2 shared library. In the end @Czaki suggestion of avoiding linking against libs in other wheels was a good one for us :-)
