### ISSUE TITLE
3.12 beta 4 support

### ISSUE THREAD

**Issue by godlygeek** [pypa/cibuildwheel#1549]
### Description

Python 3.12 beta 4 is expected to be the final beta of Python 3.12, and was released earlier this week. Can a cibuildwheel release be cut supporting this? It's important to get it sooner rather than later, as this will be the last chance for people to test with 3.12 before the ABI freeze of the release candidate phase.

**Comment by joerick** [comment]
I hear you. We're currently waiting on pypa/manylinux to include it. Might be worth chiming in on https://github.com/pypa/manylinux/issues/1484 

p.s. sorry about your avatar :(

**Comment by henryiii** [comment]
I have been waiting because we need manylinux to pick it up first.

**Comment by henryiii** [comment]
Someone needs to trigger https://github.com/pypa/manylinux/actions/workflows/update-dependencies.yml otherwise it will trigger on Sunday (4 days).

**Comment by joerick** [comment]
(humble plug for [manylinux inspector](https://manylinuxinspector.joerick.me/#/) which shows 3.12.0b3 still the latest :) )

**Comment by henryiii** [comment]
I just pulled the image. Using [manylinux inspector](https://manylinuxinspector.joerick.me/#/) would have been much smarter on conference wifi!

**Comment by henryiii** [comment]
> as this will be the last chance for people to test with 3.12 before the ABI freeze of the release candidate phase.

FYI, Technically I believe the ABI is supposed to stable at RC4, though I think they've softened the language around it a bit: "Our goal is to have no ABI changes after this release, and as few code changes as possible after 3.12.0rc1, the first release candidate.")https://pythoninsider.blogspot.com/2023/07/pleased-to-announce-release-of-python-3.html

**Comment by godlygeek** [comment]
> I hear you. We're currently waiting on pypa/manylinux to include it.

Ah, I see. Thanks!

> FYI, technically I believe the ABI is supposed to stable at RC4

That's the goal, yes - but between beta 4 and release candidate 1 is the last chance for an ABI breaking change. It would need to be well justified, but it can happen, which is why it's important that people test with it now. Once release candidate 1 comes out (scheduled for 2023-07-31) it will be too late to make an ABI breaking change no matter how well justified.

> p.s. sorry about your avatar :(

GitHub autogenerated me a frowny face, and I think that's so funny that I upload it as my profile picture everywhere! 😂

**Comment by mayeut** [comment]
Manylinux is currently rebuilding with beta4.
It should be available in a couple hours.

**Comment by godlygeek** [comment]
The [manylinux inspector](https://manylinuxinspector.joerick.me/#/) tells me that has landed! I think we should now be unblocked to cut a new cibuildwheel release that uses beta 4?

**Comment by joerick** [comment]
Yes. I'll cut a new release tomorrow, all being well

**Comment by joerick** [comment]
2.14.1 is out!
