### ISSUE TITLE
Version number mismatch when buidling for Python3.6

### ISSUE THREAD

**Issue by LinZhihao-723** [pypa/cibuildwheel#1551]
### Description

The CI config builds for Python versions from 3.6 to 3.11. It worked fine for Python 3.7 to 3.11, but the wheels for Python 3.6 had unexpected names.
Expected name: `clp_ffi_py-0.0.0b1-cp36-cp36m-manylinux_2_17_x86_64.manylinux2014_x86_64.whl`
Generated name: `clp_ffi_py-0.1.dev1+g59e4576-cp36-cp36m-manylinux_2_17_x86_64.manylinux2014_x86_64`
The expected name is what's required from the PyPI naming convention. However, this problem only occurred in Python 3.6. The rest of the wheels got built properly.
I don't know how to configure the tool to generate the correct name for Python 3.6...

### Build log

https://github.com/LinZhihao-723/clp_ffi_py_beta/actions/runs/5527699662

### CI config

https://github.com/LinZhihao-723/clp_ffi_py_beta/blob/ir_decoder/.github/workflows/build_wheels.yml

**Comment by henryiii** [comment]
There is no version of setuptools that supports both Python 3.6 and the `[project]` table in pyproject.toml as far as I can remember. You are getting very old versions of everything. Setuptools 61 is the first to support that and 62 is better.

Python 3.6 and now 3.7 are past EoL.

**Comment by LinZhihao-723** [comment]
Thank you for your response! Is there any thing I can do to build for 3.6? Like using an older version of cibuildwheel?

**Comment by Czaki** [comment]
You may use `setup.cfg` instead of `project` section in `pyproject.toml`

**Comment by LinZhihao-723** [comment]
Ok, thanks for the help!
