### ISSUE TITLE
Building on Macos fails on account of `pip` version

### ISSUE THREAD

**Issue by brenthuisman** [pypa/cibuildwheel#1558]
### Description

As of a week ago our CI job building wheels using `cibuildwheel` is failing. Under Macos, the Building wheel phase errors out with a `pip` related error:
```
Building wheel...
  
  + python -m pip freeze --all
  + python -m build /Users/runner/work/arbor/arbor --wheel --outdir=/private/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/cibw-run-n4wrai89/cp38-macosx_universal2/built_wheel
  * Creating virtualenv isolated environment...
  ERROR:root:fail
  Traceback (most recent call last):
    File "/private/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/cibw-run-n4wrai89/cp38-macosx_universal2/build/venv/lib/python3.8/site-packages/virtualenv/seed/embed/via_app_data/via_app_data.py", line 84, in _get
      result = get_wheel(
    File "/private/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/cibw-run-n4wrai89/cp38-macosx_universal2/build/venv/lib/python3.8/site-packages/virtualenv/seed/wheels/acquire.py", line 36, in get_wheel
      wheel = download_wheel(
    File "/private/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/cibw-run-n4wrai89/cp38-macosx_universal2/build/venv/lib/python3.8/site-packages/virtualenv/seed/wheels/acquire.py", line 76, in download_wheel
      raise CalledProcessError(process.returncode, cmd, **kwargs)
  subprocess.CalledProcessError: Command '['/private/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/cibw-run-n4wrai89/cp38-macosx_universal2/build/venv/bin/python', '-m', 'pip', 'download', '--progress-bar', 'off', '--disable-pip-version-check', '--only-binary=:all:', '--no-deps', '--python-version', '3.8', '-d', '/Users/runner/Library/Application Support/virtualenv/wheel/house', 'pip==23.2.1']' returned non-zero exit status 1.
  ERROR:root:failed to download pip version 23.2.1, pip download exit code 1
  
  The conflict is caused by:
      The user requested pip==23.2.1
      The user requested (constraint) pip==23.1.2
  
  To fix this you could try to:
  1. loosen the range of package versions you've specified
  2. remove package versions to allow pip attempt to solve the dependency conflict
  
  ERROR: Cannot install pip==23.2.1 because these package versions have conflicting dependencies.
  ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts
```

The two versions mentioned are the two versions that are shown in the Running before_build phase: the older versions is uninstalled and the more recent version is installed. So, I don't understand where in a subsequent step the ostensible request for the older version comes from, not from the cibw command, which clearly asks for the specific version matching the most recent `pip`. I also don't see what I can do to work around this.

Do you know what's going on?

### Build log

https://github.com/arbor-sim/arbor/actions/runs/5634061150/job/15263611953

### CI config

https://github.com/arbor-sim/arbor/blob/master/.github/workflows/release.yml

**Comment by brenthuisman** [comment]
The problem is worked around by suppressing updating `pip` in the `before-build` stage, which was `before-build = "python -m pip install pip --upgrade"`. This was at one point necessary for another dep, but it looks like not anymore.

I'm not sure if preventing this, which used to work, is intentional, and why. I'd like to know :)

**Comment by joerick** [comment]
It might be a change in how build installs pip in the isolated build environment. Our code for this is here-                     

https://github.com/pypa/cibuildwheel/blob/5b32ee7d7bcd9433f559d8b43e9f9a180288c227/cibuildwheel/macos.py#L402-L420

Your upgrade of pip means that the pip version in `PIP_CONSTRAINT` (which is a constraints.txt file) doesn't match the one we specify in `VIRTUALENV_PIP`. 

It could be that we don't need to specify `VIRTUALENV_PIP` anymore if `build` is respecting the pip version in `PIP_CONSTRAINT`. But even if so, your upgrade won't affect the pip version used internally by `build`.

**Comment by joerick** [comment]
I should say - you could set [`CIBW_DEPENDENCY_VERSIONS=latest`](https://cibuildwheel.readthedocs.io/en/stable/options/#dependency-versions) to get latest pip (and everything else), and you wouldn't need the before-build bit either.

**Comment by brenthuisman** [comment]
OK, thanks for explanation and tip!
