### ISSUE TITLE
Testing Linux wheels on Windows host (via Docker)

### ISSUE THREAD

**Issue by MBS9** [pypa/cibuildwheel#1572]
### Description

Hi all!

Thanks so much for building this wonderful project! It helps a lot in building wheels.

While testing the tool locally on my Windows laptop, I found that while I can build Linux wheels using containers, the test setup doesn't seem to work.

Here is the output from repair & test which shows the error:

```
Repairing wheel...

    + sh -c 'auditwheel repair -w /tmp/cibuildwheel/repaired_wheel /tmp/cibuildwheel/built_wheel/krptn-0.7.0-cp39-cp39-linux_x86_64.whl'
INFO:auditwheel.main_repair:Repairing krptn-0.7.0-cp39-cp39-linux_x86_64.whl
INFO:auditwheel.wheeltools:Previous filename tags: linux_x86_64
INFO:auditwheel.wheeltools:New filename tags: manylinux_2_17_x86_64, manylinux2014_x86_64
INFO:auditwheel.wheeltools:Previous WHEEL info tags: cp39-cp39-linux_x86_64
INFO:auditwheel.wheeltools:New WHEEL info tags: cp39-cp39-manylinux_2_17_x86_64, cp39-cp39-manylinux2014_x86_64
INFO:auditwheel.main_repair:
Fixed-up wheel written to /tmp/cibuildwheel/repaired_wheel/krptn-0.7.0-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl
    + /opt/python/cp38-cp38/bin/python -c 'import sys, json, glob; json.dump(glob.glob('"'"'/tmp/cibuildwheel/repaired_wheel/*.whl'"'"'), sys.stdout)'

                                                                       ✓ 0.71s
Testing wheel...

    + pip install virtualenv -c '\constraints.txt'
ERROR: Could not open requirements file: [Errno 2] No such file or directory: '\\constraints.txt'

                                                                       ✕ 1.80s
Error: Command ['pip', 'install', 'virtualenv', '-c', PureWindowsPath('/constraints.txt')] failed with code 1.
```
Based on what I see in the error above, it seems like CI Build Wheel is using a `PureWindowsPath` to reference the `contraints.txt` file inside a Linux container. This fails since the linux container uses Linux and hence `PureWindowsPath` should be  `PurePosixPath` (or something like that).

If the CI Build Wheel team agrees, I would love to open a pull request to fix this. I have traced that this path is constructed [here](https://github.com/pypa/cibuildwheel/blob/main/cibuildwheel/linux.py#L188), and would be happy to change that code to use `PurePosixPath` (and any other changes which need making), as opposed to `PurePath` (which will use Windows Paths since its running on Windows host).

Thanks, a lot, in advance!

**Comment by mayeut** [comment]
Hi @MBS9,
your analysis seems to be the right one.
This location was missed in https://github.com/pypa/cibuildwheel/pull/1117
You can go ahead and open a Pull Request.
Thanks

**Comment by MBS9** [comment]
Hi @mayeut ! Thanks for your quick response! I opened PR #1573 

Let me know if something needs change in the PR!

**Comment by MBS9** [comment]
Thank you for merging the PR. I’ll now close this issue.
