### ISSUE TITLE
job fails on python 3.12

### ISSUE THREAD

**Issue by louisabraham** [pypa/cibuildwheel#1574]
### Description

[This job](https://github.com/louisabraham/pydivsufsort/actions/runs/5851153678/job/15861602978) failed

The reason is [this](https://github.com/pypa/pip/issues/11501) pip bug so we should require pip >= 23.2

I'm trying a fix where I call `pip install -U pip` from `CIBW_BEFORE_BUILD`.

### Build log

https://github.com/louisabraham/pydivsufsort/actions/runs/5851153678/job/15861602978

### CI config

https://github.com/louisabraham/pydivsufsort/commit/baf932eb0018eb6ef0ae7686be38aa44821f9d4e

**Comment by louisabraham** [comment]
My fix didn't work: https://github.com/louisabraham/pydivsufsort/actions/runs/5851270990/job/15861950058

**Comment by joerick** [comment]
I think the reason is numpy, not pip, see https://github.com/numpy/numpy/issues/23808

**Comment by henryiii** [comment]
You can set `PIP_PRE=1`, that will get numpy 1.26.0b1.

**Comment by henryiii** [comment]
Actually, even better, set `PIP_ONLY_BINARY=:all:`, then you'll never try to build numpy or other dependent wheels, and it will get the only binary it can find, even though it's a pre-release. :) (`PIP_ONLY_BINARY=numpy` also works)

**Comment by yunjunz** [comment]
I got the same issue as well. [Setting `PIP_ONLY_BINARY=:all:`](https://github.com/insarlab/PySolid/pull/66/files) does not seem to solve the [issue](https://github.com/insarlab/PySolid/actions/runs/5850525279/job/15860434614?pr=66).

**Comment by henryiii** [comment]
Do you have a lower bound? For some reason, that changes the resolution to more strongly avoid pre-releases. You need PIP_PRE if so.

**Comment by henryiii** [comment]
Oh, by the way, your example is incorrect. You can’t set environment variables directly, it must be via CIBW_ENVIRONMENT or use CIBW_ENVIRONMENT_PASS with it. It’s less error prone if you use pyproject.toml config.

**Comment by brenthuisman** [comment]
> Actually, even better, set `PIP_ONLY_BINARY=:all:`, then you'll never try to build numpy or other dependent wheels, and it will get the only binary it can find, even though it's a pre-release. :) (`PIP_ONLY_BINARY=numpy` also works)

Unfortunately, both break. `PIP_ONLY_BINARY` doesn't work for PyPy builds (they don't publish PyPy binaries), and `PIP_PRE` get's you that 1.26 beta, but it doesn't (yet) build for PyPy (1.25.x does).

**Comment by joerick** [comment]
If you want to, [TOML overrides](https://cibuildwheel.readthedocs.io/en/stable/options/#overrides) should allow you to solve that. You could set the `PIP_ONLY_BINARY ` environment only on CPython, for example.

**Comment by brenthuisman** [comment]
Yep, I'm awaiting [CI on that](https://github.com/arbor-sim/arbor/pull/2211/commits/fc412b189b06fa1e3c027e98183cfa11da6ff019) :)

**Comment by henryiii** [comment]
Yes there are. But only for PyPy 3.9. 3.8 isn’t supported and 3.10 doesn’t seem to be added yet.

**Comment by joerick** [comment]
NumPy 1.26.0 is now released, this issue should be solved.
