### ISSUE TITLE
How to check if all PyPI builds are succesfull

### ISSUE THREAD

**Issue by LecrisUT** [pypa/cibuildwheel#1577]
### Description

This might be more appropriate on the PyPI repos, but I think it is helpful to be documented here as well since the purpose of this project is to CI test on multiple python environments.

From the documentation page on [uploading to pypi](https://cibuildwheel.readthedocs.io/en/stable/deliver-to-pypi/#github-actions), the job `upload_all` only pulls the artifact of the `sdist`, however all of the wheels are saved in `./wheelhouse/*.whl`, which is not pulled.
https://github.com/pypa/cibuildwheel/blob/9afd31017a92372002d0d22593b79cb7ef91f373/examples/github-deploy.yml#L27-L29

This would indicate that PyPI does not use those wheels and it always rebuilds from the `sdist`. But then how can we track if all of the builds there are successful? I couldn't find any badge that can be used to indicate that on the front page

**Comment by henryiii** [comment]
If a wheel fails, it fails the job. (There's an open issue on allowing failed tests to still pass, currently it's all or nothing). When you write: `./wheelhouse/*.whl`, that's uploading the wheels from the `/wheelhouse` folder into the artifact. It gets combined with the SDist which gets uploaded from `./dist`. When you download the combined artifact, you are putting everything in `/dist`. So you have all the wheels and the SDist.

**Comment by LecrisUT** [comment]
Ah, so in https://github.com/pypa/cibuildwheel/blob/main/examples/github-deploy.yml, the key part is that both artifacts are name `artifact` so they are getting combined together, and on `PyPI` it does use the wheels that are built in the CI, right?

**Comment by henryiii** [comment]
Yes
