### ISSUE TITLE
`CIBW_CONTAINER_ENGINE` splits on `:` when it shouldn't

### ISSUE THREAD

**Issue by makslevental** [pypa/cibuildwheel#1600]
### Description

`CIBW_CONTAINER_ENGINE="docker; create_args: -p=8080:8080"`

gets parsed into

```
  container_engine: 
    name: docker
    create_args: ['-p=8080', ':', '8080']
```

problem is here https://github.com/pypa/cibuildwheel/blob/e5d0cc0b0d37d20a053b85112e4e1f137079c85e/cibuildwheel/util.py#L710

potential fix from [here](https://stackoverflow.com/a/61737902/9045206):
```python
shlexer = shlex.shlex(key_value_string, posix=True, punctuation_chars=True)
shlexer.wordchars += ':'
```

with this change, `CIBW_CONTAINER_ENGINE="docker; create_args : -p=8080:8080"` (note the space after `create_args`) parses to `fields=[['docker'], ['create_args', ':', '-p=8080:8080']]`.

**Comment by joerick** [comment]
Ah, that's unfortunate. A workaround would be to quote the create_args, e.g. `CIBW_CONTAINER_ENGINE="docker; create_args: '-p=8080:8080'"`. However, I'll work on a fix too.

**Comment by joerick** [comment]
Fix for this in https://github.com/pypa/cibuildwheel/pull/1621

**Comment by makslevental** [comment]
@joerick - I had tried quoting various ways but couldn't get it to work. Thanks for the fix!
