### ISSUE TITLE
OSX: Not a supported wheel on this platform.

### ISSUE THREAD

**Issue by Fokko** [pypa/cibuildwheel#1603]
### Description

At pyiceberg we've adopted `cibuildwheel` and it is really well. Thanks for the amazing work!

We're using Poetry as well, and I think that's causing some issue when running the tests. I've noticed that the wheel is not installable. It looks like the Python versions check out, but I think it has to do with the MacOSX version `macosx_11_4` instead of `macosx_11_0`. I have to double-check this, but wanted to reach out if this is something that others have seen as well.

Relevant stack trace:
```
+ python -m virtualenv --no-download /private/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/cibw-run-atq1ry1r/cp38-macosx_x86_64/venv-test
  created virtual environment CPython3.8.10.final.0-64 in 2176ms
    creator CPython3Posix(dest=/private/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/cibw-run-atq1ry1r/cp38-macosx_x86_64/venv-test, clear=False, no_vcs_ignore=False, global=False)
    seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/Users/runner/Library/Application Support/virtualenv)
      added seed packages: pip==23.2.1, setuptools==68.0.0, wheel==0.41.0
    activators BashActivator,CShellActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator
  + which python
  /private/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/cibw-run-atq1ry1r/cp38-macosx_x86_64/venv-test/bin/python
  + pip install '/private/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/cibw-run-atq1ry1r/cp38-macosx_x86_64/repaired_wheel/pyiceberg-0.5.0-cp38-cp38-macosx_11_0_x86_64.whl[s3fs,glue]'
  ERROR: pyiceberg-0.5.0-cp38-cp38-macosx_11_0_x86_64.whl is not a supported wheel on this platform.
```

### Build log

https://github.com/Fokko/incubator-iceberg/actions/runs/6130886860/job/16640407592

### CI config

https://github.com/Fokko/incubator-iceberg/blob/master/.github/workflows/python-release.yml

**Comment by joerick** [comment]
My memory is terrible - I previously discovered this and reported it back in February.

https://github.com/pypa/pip/issues/11789

**Comment by joerick** [comment]
Waiting on https://github.com/pypa/pip/issues/11715 .

Not a lot we can do here. You could try running your tests with `SYSTEM_VERSION_COMPAT=0`, e.g `SYSTEM_VERSION_COMPAT=0 pytest <path>`. Or just skip the tests on Python 3.8 macOS, other versions aren't affected.

**Comment by Fokko** [comment]
Got it, thanks @joerick for the context.

**Comment by njzjz** [comment]
Pip on Python 3.8 has fixed this issue. However, I still got this error with Python 3.7, which the latest pip doesn't support.
