### ISSUE TITLE
skip `setup-python` on self-hosted Linux aarch64 runner

### ISSUE THREAD

**Issue by njzjz** [pypa/cibuildwheel#1623]
### Description

I try to use `cibuildwheel` on a self-hosted Linux aarch64 runner, considering QEMU is much slower.

I used `uses: pypa/cibuildwheel@2.15` in the GitHub Actions configuration file and got the following error:
```
Run actions/setup-python@v4
  with:
    python-version: 3.8 - 3.11
    update-environment: false
    check-latest: false
    token: ***
    allow-prereleases: false
  env:
    CIBW_BUILD_VERBOSITY: 1
    CIBW_ARCHS: all
    CIBW_BUILD: cp310-manylinux_aarch64
    DP_VARIANT: cpu
Installed versions
  Version 3.8 - 3.11 was not found in the local cache
  Error: The version '3.8 - 3.11' with architecture 'arm64' was not found for this operating system.
  The list of all available versions can be found here: https://raw.githubusercontent.com/actions/python-versions/main/versions-manifest.json
```

I've checked https://raw.githubusercontent.com/actions/python-versions/main/versions-manifest.json and found there is no Linux arm64. There has been an issue with it: https://github.com/actions/setup-python/issues/678. Thus, I wonder if `setup-python` step in `action.yml` can be skipped on Linux arm64, until GitHub supports it, or add an option to skip `setup-python` manually.

### Build log

https://github.com/njzjz/deepmd-kit/actions/runs/6244159421/job/16950679187

### CI config

https://github.com/njzjz/deepmd-kit/blob/22237677d58974c99beaf694edd0848088f4cc94/.github/workflows/build_wheel.yml

**Comment by mayeut** [comment]
I think you can populate the runner cache with a shim to your python install (or with a venv) for the tool cache to be able to find python without even looking at the manifest.
I don't have a doc for this but I guess you can follow the filesystem structure in https://github.com/actions/python-versions/blob/main/installers/nix-setup-template.sh
This would also allow you to use other actions/workflows using `setup-python` (side effects on self-hosted is likely to happen though so venv is probably the way to go).

**Comment by njzjz** [comment]
Thanks, I know how to use `venv` to make it work.

```sh
cd /path/to/actions-runner/  # the path to install the actions runner
mkdir -p _work/_tool/Python/3.10.12/arm64  # assume Python version is 3.10.12
python -m venv _work/_tool/Python/3.10.12/arm64
mkdir -p _work/_tool/Python/3.10.12/arm64.complete  # important, otherwise it can not be found
```
