### ISSUE TITLE
Platform-Arch specific environmental variables

### ISSUE THREAD

**Issue by bashtage** [pypa/cibuildwheel#1624]
### Description

I need to pass a specific environmental variable when building on OSX-ARM, but not on OSX-x86_64.  Right now I use github actions to build wheels for OSX and get (or try to get) both x86_64 and ARM builds in a single pass.

**Comment by Czaki** [comment]
It looks like you need use configuration overrides: https://cibuildwheel.readthedocs.io/en/stable/options/#overrides

**Comment by bashtage** [comment]
Thank you both.
