### ISSUE TITLE
reduce manylinux package name length

### ISSUE THREAD

**Issue by MrBitBucket** [pypa/cibuildwheel#1654]
### Description

I raised an issue here https://discuss.python.org/t/limits-on-pypi-download-name-length/37700/3 concerning a long manylinux package name. 

There is a suggestion from Brett Cannon that the package name can be shortened considerably because packaging.tags will be used to generate the relevant information.

I suspect name shortening should be done by cibuildwheel rather than by me guessing how it can be reduced, however, I suppose that there are facts about the pypi/pip interaction that will make this more or less possible.

**Comment by joerick** [comment]
The wheel filename in this case is decided by auditwheel, so it would be best to raise it over there https://github.com/pypa/auditwheel .

I suspect that there is some heuristic that can be changed here, but I believe the reason so many tags are written is to ensure compatibility with versions of pip that predate the newer tags. But I think the auditwheel folks will know more.

**Comment by henryiii** [comment]
You can manually retag with `python -m wheel tags <...>` if you want to remove some of the compatibility tags.
