### ISSUE TITLE
Problem loading Apple Silicon wheels built on Intel Mac runner: `(mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64')`

### ISSUE THREAD

**Issue by lanctot** [pypa/cibuildwheel#1662]
### Description

Hi all, 

I think I've followed all the docs and believe to have everything setup correctly, but I must be missing something. I am able to build `*_arm64.whl` binary wheels using GutHub Actions, but when I try to install the binary pip on my Apple Silicon Mac I get an error in the subject (that it's only finding an `x86_84` architecture).

Full transcript (error at the bottom):
```
lanctot-macbookpro23:Downloads lanctot$ rm -rf ~/Library/Cache/pip
lanctot-macbookpro23:Downloads lanctot$ unzip artifact.zip 
Archive:  artifact.zip
   creating: dist/
   creating: wheelhouse/
  inflating: dist/open_spiel-1.4.tar.gz  
  inflating: wheelhouse/open_spiel-1.4-cp310-cp310-macosx_10_9_x86_64.whl  
  inflating: wheelhouse/open_spiel-1.4-cp310-cp310-macosx_11_0_arm64.whl  
  inflating: wheelhouse/open_spiel-1.4-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl  
  inflating: wheelhouse/open_spiel-1.4-cp311-cp311-macosx_10_9_x86_64.whl  
  inflating: wheelhouse/open_spiel-1.4-cp311-cp311-macosx_11_0_arm64.whl  
  inflating: wheelhouse/open_spiel-1.4-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl  
  inflating: wheelhouse/open_spiel-1.4-cp312-cp312-macosx_10_9_x86_64.whl  
  inflating: wheelhouse/open_spiel-1.4-cp312-cp312-macosx_11_0_arm64.whl  
  inflating: wheelhouse/open_spiel-1.4-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl  
  inflating: wheelhouse/open_spiel-1.4-cp38-cp38-macosx_10_9_x86_64.whl  
  inflating: wheelhouse/open_spiel-1.4-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl  
  inflating: wheelhouse/open_spiel-1.4-cp39-cp39-macosx_10_9_x86_64.whl  
  inflating: wheelhouse/open_spiel-1.4-cp39-cp39-macosx_11_0_arm64.whl  
  inflating: wheelhouse/open_spiel-1.4-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl  
lanctot-macbookpro23:Downloads lanctot$ pip3 install wheelhouse/open_spiel-1.4-cp39-cp39-macosx_11_0_arm64.whl 
Defaulting to user installation because normal site-packages is not writeable
Processing ./wheelhouse/open_spiel-1.4-cp39-cp39-macosx_11_0_arm64.whl
Requirement already satisfied: pip>=20.0.2 in /Users/lanctot/Library/Python/3.9/lib/python/site-packages (from open-spiel==1.4) (23.3.1)
Requirement already satisfied: attrs>=19.3.0 in /Users/lanctot/Library/Python/3.9/lib/python/site-packages (from open-spiel==1.4) (23.1.0)
Requirement already satisfied: absl-py>=0.10.0 in /Users/lanctot/Library/Python/3.9/lib/python/site-packages (from open-spiel==1.4) (1.4.0)
Requirement already satisfied: numpy>=1.21.5 in /Users/lanctot/Library/Python/3.9/lib/python/site-packages (from open-spiel==1.4) (1.25.2)
Requirement already satisfied: scipy>=1.10.1 in /Users/lanctot/Library/Python/3.9/lib/python/site-packages (from open-spiel==1.4) (1.11.2)
Requirement already satisfied: ml-collections>=0.1.1 in /Users/lanctot/Library/Python/3.9/lib/python/site-packages (from open-spiel==1.4) (0.1.1)
Requirement already satisfied: PyYAML in /Users/lanctot/Library/Python/3.9/lib/python/site-packages (from ml-collections>=0.1.1->open-spiel==1.4) (6.0.1)
Requirement already satisfied: six in /Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/site-packages (from ml-collections>=0.1.1->open-spiel==1.4) (1.15.0)
Requirement already satisfied: contextlib2 in /Users/lanctot/Library/Python/3.9/lib/python/site-packages (from ml-collections>=0.1.1->open-spiel==1.4) (21.6.0)
Installing collected packages: open-spiel
Successfully installed open-spiel-1.4
lanctot-macbookpro23:Downloads lanctot$ python3
Python 3.9.6 (default, May  7 2023, 23:32:44) 
[Clang 14.0.3 (clang-1403.0.22.14.1)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import pyspiel
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: dlopen(/Users/lanctot/Library/Python/3.9/lib/python/site-packages/pyspiel.so, 0x0002): tried: '/Users/lanctot/Library/Python/3.9/lib/python/site-packages/pyspiel.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64')), '/System/Volumes/Preboot/Cryptexes/OS/Users/lanctot/Library/Python/3.9/lib/python/site-packages/pyspiel.so' (no such file), '/Users/lanctot/Library/Python/3.9/lib/python/site-packages/pyspiel.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64'))
>>> 
```

Here are:

- My [wheels.yml file](https://github.com/google-deepmind/open_spiel/blob/lanctot-patch-53/.github/workflows/wheels.yml). Note, I'm even passing in both architectures via the `--archs` flag
- A [recent successful build log of the artifact.zip](https://github.com/google-deepmind/open_spiel/actions/runs/6862299155/job/18659714507) from above. Note that cibuildwheel shows using the correct architectures for the `arm64` wheels. 

So what I'm thinking now is that maybe I need to pass the architecure target to my package's build system, which is based entirely on CMake. Could that be it? I'm not finding much docs on what happens when the architecture is set to `arm64`.. perhaps I need to pass along a compilation flag through to my CMake setup? Any other ideas?

### Build log

https://github.com/google-deepmind/open_spiel/actions/runs/6862299155/job/18659714507

### CI config

https://github.com/google-deepmind/open_spiel/blob/lanctot-patch-53/.github/workflows/wheels.yml

**Comment by joerick** [comment]
Yes, that sounds right. To perform cross-compilation, cibuildwheel sets flags for setuptools:

https://github.com/pypa/cibuildwheel/blob/81812d05a396036d2313d0b4893e0068a567567e/cibuildwheel/macos.py#L248-L252

But if you're building using cmake you might have to pass this through to the actual compile command somehow. The easiest one will probably be the `ARCHFLAGS` env var. @henryiii will probably know more, being a bit of a cmake pro.

**Comment by joerick** [comment]
Alternatively, you could avoid the cross-compilation thing altogether using the new Apple Silicon runners: https://github.blog/2023-10-02-introducing-the-new-apple-silicon-powered-m1-macos-larger-runner-for-github-actions/

**Comment by lanctot** [comment]
Thank you both! 

I did not realize those new runners were already available. I'm trying on them because it requires little change on my part. After [a bit of trial-and-error](https://github.com/google-deepmind/open_spiel/pull/1141), I've almost got it working! The arm64 wheels are now built. 

All that's left is testing them on my laptop. If they work, I'll close the issue.

I also didn't know about scikit-build!  Thanks so much.

**Comment by lanctot** [comment]
Worked! Thanks again.
