### ISSUE TITLE
env variables are not taken over into manylinux docker container

### ISSUE THREAD

**Issue by maxnoe** [pypa/cibuildwheel#1671]
### Description

To test the cibuildwheel workflow, I enabled building on push and tried to deploy to test pypi.

The project is using `setuptools_scm` for versioning, but (test)-pypi rejects local versions (versions including git hashes).

So in my workflow, I exported `SETUPTOOLS_SCM_PRETEND_VERSION_FOR_EVENTIO=0.0.0dev2` to get an acceptable version for testing the upload.

This worked for the sdist, the windows and macos wheels build by the cibuildwheel step but not for the manylinux wheels.

I guess the environment variable is not taken over into the docker manylinux build container.

As you can see in the build log linked below, the windows and macos wheels have the overriden version, while the manylinux wheel have the "correct" version extracted from git info.

### Build log

https://github.com/cta-observatory/pyeventio/actions/runs/6942567789/job/18885995650?pr=270#step:5:18

### CI config

https://github.com/cta-observatory/pyeventio/pull/270

**Comment by Czaki** [comment]
Yes. Passing all environment variables is not a good idea. So `cibuildwheel` provides [`CIBW_ENVIRONMENT_PASS_LINUX`](https://cibuildwheel.readthedocs.io/en/stable/options/#environment-pass) configuration options to allow define which variables should be copied to container. 

So you need to `CIBW_ENVIRONMENT_PASS_LINUX: SETUPTOOLS_SCM_PRETEND_VERSION_FOR_EVENTIO` To your configuration

**Comment by maxnoe** [comment]
Thanks @Czaki and sorry for not properly checking the documentation.
