### ISSUE TITLE
Dependencies are not properly built into the whl files in Python3.6

### ISSUE THREAD

**Issue by LinZhihao-723** [pypa/cibuildwheel#1676]
### Description

When using cibuildwheel to build my C-extension project in Python3.6, the whl file is successfully built. However, when installing the whl file in Python3.6, the dependency files are not properly installed required by my project.
The dependencies are specified in `pyproject.toml` file. Since Python3.6 is quite old, I am not sure if this is an expected behavior. If so, is there any way I can fix it? Thanks!

**Comment by Czaki** [comment]
Support for storing dependencies in `pyproject.toml` was introduced in `setuptools` in version 61, which support only Python 3.7+.

To properly configure dependencies for python 3.6 you need to use `setup.cfg`, not `pyproject.toml`

**Comment by LinZhihao-723** [comment]
Thanks! I will try to configure a setup.cfg
