### ISSUE TITLE
Misleading documentation for `CIBW_BEFORE_ALL`

### ISSUE THREAD

**Issue by doronz88** [pypa/cibuildwheel#1685]
### Description

I'm trying to use `cibuildwheel` locally to test stuff before using the GitHub actions.
I an installation prequisite of `libssl-dev` and followed the guidelines from:
https://cibuildwheel.readthedocs.io/en/stable/setup/

However, when I try exporting `CIBW_BEFORE_ALL` to use `apt` just as the example suggests, I'm getting an error that no `apt` binary exists.

**Comment by joerick** [comment]
Which build fails? Link a build log. What's your exact config? etc.

**Comment by doronz88** [comment]
Just discovered the real culprit - the documentation!
I got by the solution suggested in #1034 - I had to try and install using all package manager variations.
The documentation should be updated to reflect this is necessary.

**Comment by doronz88** [comment]
I get that, but I believe the documentation should state that it is built on several linux distros with different package managers. Usually, I expect documentation examples to work as-is.

**Comment by joerick** [comment]
ah, yeah that isn't a good snippet to include so early in the docs, and it is outdated given that the default image is now almalinux-based.

The point of this snippet is to show how to pass options to cibuildwheel. So we should change it to something less platform-dependent. `CIBW_BUILD_FRONTEND=build` could be a non-controversial replacement that works everywhere.

PR would be welcome for this!

**Comment by doronz88** [comment]
Updated my PR for that #1686
