### ISSUE TITLE
[docs][infra] Set up a pypa.io subdomain?

### ISSUE THREAD

**Issue by webknjaz** [pypa/cibuildwheel#1688]
### Description

$sbj. It's essentially the same as https://github.com/pypa/pipx/issues/1058.
Any objections?

**Comment by joerick** [comment]
This would be nice. But, is there a way to make all the links to cibuildwheel.readthedocs.io redirect to the new domain? There are a lot of links to that domain. I'm not sure I'd like to make the change unless we can be confident that URLs will properly redirect. e.g. if a link sent a user to https://cibuildwheel.readthedocs.io/en/stable/options/#before-build, they end up at https://cibuildwheel.pypa.io/en/stable/options/#before-build

**Comment by webknjaz** [comment]
Yes, that's how it works out of the box, zero config needed.

**Comment by webknjaz** [comment]
@ewdurbin hey Ee, could you make another CNAME for this RTD project too, plz?

**Comment by henryiii** [comment]
You can see this working for build, which did this recently.

**Comment by joerick** [comment]
Nice, yeah I just tested it and the redirect was perfect, even including the URL fragment (i guess this is standard browser behaviour, TIL).

https://pypa-build.readthedocs.io/en/stable/installation.html#compatibility

**Comment by ewdurbin** [comment]
> @ewdurbin hey Ee, could you make another CNAME for this RTD project too, plz?

Yes. Please add my user on readthedocs.org for the project first. (This is primarily so that DNS/cert/etc settings can be managed in the future by PSF infra).

**Comment by henryiii** [comment]
Did we not do that with build?

**Comment by joerick** [comment]
Thanks @ewdurbin ! just sent you the invite to the RtD project.

**Comment by ewdurbin** [comment]
CNAME and domain configuration added.

**Comment by webknjaz** [comment]
@henryiii @joerick RTD config update pending?

**Comment by joerick** [comment]
I totally forgot about this, thanks for the reminder! I'll take a look tomorrow. It will probably need some code/docs edits too so might require some planning to sync it up with a release.

**Comment by webknjaz** [comment]
> It will probably need some code/docs edits

Not really. Those shouldn't be blockers since the redirects will work for the old links just fine.

**Comment by joerick** [comment]
> Those shouldn't be blockers since the redirects will work for the old links just fine.

Sure, not blockers but I don't see any reason to rush, I'd rather keep things neat and make the change all at once with a release.

**Comment by joerick** [comment]
It's done! Btw, thanks to whoever changed over the sidebar URL :)
