### ISSUE TITLE
Update PyPy to 7.3.15

### ISSUE THREAD

**Issue by mattip** [pypa/cibuildwheel#1736]
### Description

PyPy was updated for the 2.6.13 release to 7.3.14, which fixed one bug but added another. Please update for the next cibuildwheel release. The new bug is pypy/pypy#4816, which broke ABI compatibility, so wheels with c-extensions built with 7.3.14 will hit an incompatibility when using the buffer protocol when mixed with c-extensions built with other versions.

Sorry for the mess.

**Comment by henryiii** [comment]
I thought we bumped this right before release? Maybe just manylinux lagged? (Not by computer at moment)

**Comment by henryiii** [comment]
Ahh, no, date on manylinux is too old. https://github.com/pypa/cibuildwheel/pull/1737 should fix.

**Comment by mattip** [comment]
Thanks.

**Comment by henryiii** [comment]
@joerick this doesn’t seem to show PyPy version: https://manylinuxinspector.joerick.me/#/

(Unless I’m missing it, on my phone)

**Comment by mattip** [comment]
I guess pypa/cibuildwheel#1728 was meant to update to pypy7.3.15, maybe I am mistaken in opening this issue.

**Comment by henryiii** [comment]
It was meant to, but it didn’t have the proper manylinux bump.

It’s not as obvious, but I found the PyPy version (PyPy 7.3.15) in the updated images.
