### ISSUE TITLE
[small] In release 2.18 documentation, freethreaded section seems to contain wrong #-link

### ISSUE THREAD

**Issue by ShadowJonathan** [pypa/cibuildwheel#1825]
### Description

Currently, the release text / changelog says this:

> ✨ Adds CPython 3.13 support, under the prerelease flag [CIBW_PRERELEASE_PYTHONS](https://cibuildwheel.pypa.io/en/stable/options/#prerelease-pythons). This version of cibuildwheel uses 3.13.0b1. Free-threading mode is not available yet, waiting on official binaries (planned for beta 2) and pip support.
> While CPython is in beta, the ABI can change, so your wheels might not be compatible with the final release. For this reason, we don't recommend distributing wheels until RC1, at which point 3.13 will be available in cibuildwheel without the flag. (https://github.com/pypa/cibuildwheel/pull/1816)

It links to #1816, while that is a PR concerning itself with rust(?), and not freethreaded cp3.13

The only issue/PR I could (quickly) find for it is https://github.com/pypa/cibuildwheel/issues/1657, but im noting this here in this issue.

**Comment by henryiii** [comment]
It was supposed to be #1815. I didn’t have a free threaded link, though that’s not a bad idea.
