### ISSUE TITLE
conda package

### ISSUE THREAD

**Issue by MementoRC** [pypa/cibuildwheel#1833]
### Description

FYI, there is a conda package for this project:
https://github.com/conda-forge/cibuildwheel-feedstock

**Comment by henryiii** [comment]
Curious. Seems odd to make PyPI wheels with a conda package. But technically fine, as we don't use the host Python.

**Comment by MementoRC** [comment]
It originated from the preference for pure-Conda dev environment where the tool was used with CLI. The message was in case anyone wanted to be added as a maintainer

**Comment by henryiii** [comment]
I'd be okay to be added.
