### ISSUE TITLE
`cibuildwheel` not finding the `conan` executable

### ISSUE THREAD

**Issue by rturrado** [pypa/cibuildwheel#1845]
### Description

I am working on this [project](https://github.com/QuTech-Delft/libqasm), `libqasm`.

It has a couple of issues:
1. For macos/x64 and Python 3.11 and 3.12 it's generating universal wheels instead of x86_64 wheels.
2. It still uses `setup.py`, which has been long deprecated.

After reading this [thread](https://github.com/pypa/wheel/issues/573), I've turned my eyes to `cibuildwheel`.

I have just run `pipx run cibuildwheel` from the root directory of a `libqasm` checkout, and I'm getting a `CommandNotFound` error, due to `cibuildwheel` not finding the `conan` binary. See some more logs here:

```
    File "/project/.eggs/plumbum-1.8.3-py3.6.egg/plumbum/machines/local.py", line 203, in which
      raise CommandNotFound(progname, list(cls.env.path))
  plumbum.commands.processes.CommandNotFound: (CommandNotFound(...), 'conan', [<LocalPath /opt/python/cp36-cp36m/bin>, <LocalPath /opt/rh/devtoolset-10/root/usr/bin>, <LocalPath /usr/local/sbin>, <LocalPath /usr/local/bin>, <LocalPath /usr/sbin>, <LocalPath /usr/bin>, <LocalPath /sbin>, <LocalPath /bin>])
  ----------------------------------------
  Building wheel for libqasm (setup.py): finished with status 'error'
  ERROR: Failed building wheel for libqasm
  Running setup.py clean for libqasm
Failed to build libqasm
ERROR: Failed to build one or more wheels
```

Any ideas of what I may be missing?
- I can run `conan` locally, it's in `$PATH`.
- And I can build the library with `python -m pip install --verbose .`.
- And according to this [documentation](https://cibuildwheel.pypa.io/en/stable/options/#environment) (see ! Note), `PATH` should be passed to (and extended by) `cibuildwheel`.

Thanks!

**Comment by henryiii** [comment]
For linux, wheels must be built in the manylinux containers in order to be redistributable. Cibuildwheel does this for you. So for linux wheels, you have to install prerequisites like Conan with `CIBW_BEFORE_ALL_LINUX` (envvar) or `[tool.cibuildwheel] linux.before-all` (`pyproject.toml`).

Also, `setup.py` is not deprecated at all, it will always a file setuptools supports. Calling it directly, such as `python setup.py ...`, is.

**Comment by rturrado** [comment]
Thanks so much for all your help, @henryiii.

I have added a `pyproject.toml` to my project, and has been doing some tests both locally (linux/x64), and through GitHub Actions (macos/x64), and I've been able to build a macos/x64/python3.11 wheel with `cibuildwheel` (see [here](https://github.com/QuTech-Delft/libqasm/actions/runs/9315609525)).

May I ask you an extra question? Once you start using `cibuildwheel`, do you still need these `bdist`, `sdist`, and `egg_info` in `setup_py`? (see [here](https://github.com/QuTech-Delft/libqasm/blob/release-0.6.7/setup.py)).

**Comment by henryiii** [comment]
I'm not sure why those were needed originally - was it just to reduce the verbosity of the messages by removing the absolute portions of the paths? `bdist` is for eggs, which haven't even been installable in years. `bdist_wheel` has replaced it.

**Comment by rturrado** [comment]
Hi @henryiii,

Can I still ask you a couple of questions? I am [playing](https://github.com/QuTech-Delft/libqasm/actions/runs/9348671097) with `cibuildwheel` to incorporate it as our wheel builder, yet I'm finding a couple of issues:

1) For Windows, it seems I'm trying to build 64-bit binaries but, for some reason, `cibuildwheel` is linking against 32-bit binaries (see [here](https://github.com/QuTech-Delft/libqasm/actions/runs/9348671097), that the top error mentions `--wheel-dir=C:\\Users\\runneradmin\\AppData\\Local\\Temp\\cibw-run-tylwy32a\\cp311-win32\\built_wheel`).
2) For Linux, I don't know why I'm not getting wheels for aarch64, only for x86_64 (see [here](https://github.com/QuTech-Delft/libqasm/actions/runs/9348671097/artifacts/1562189506)).

**Comment by rturrado** [comment]
OK, I think I've solved them myself hehe:

1) I just had to disable Win32 builds.
2) I had to setup emulation for linux/aarch64.

It's everything working as expected [now](https://github.com/QuTech-Delft/libqasm/actions/runs/9349869095).
