### ISSUE TITLE
Macos-14 builds fail if output_dir does not already exist AND testing is enabled

### ISSUE THREAD

**Issue by MusicalNinjaDad** [pypa/cibuildwheel#1850]
### Description

Building for Macos14 (in github actions = arm64) fails when attempting to move the wheel after testing if the output directory does not already exist.

Contrary to the documentation `pathlib.Path.unlink()` throws a `NotADirectoryError` in this case, and apparently only on this platform. (I will raise an Issue in cpython for that as well - at least to update the docs ...)

Compare:
- Failed run: https://github.com/MusicalNinjaDad/FizzBuzz/actions/runs/9351587993/job/25744497746
```
============================== 11 passed in 0.05s ==============================
  Traceback (most recent call last):
    File "/Users/runner/work/_temp/cibw/bin/cibuildwheel", line 8, in <module>
      sys.exit(main())
               ^^^^^^
    File "/Users/runner/work/_temp/cibw/lib/python3.12/site-packages/cibuildwheel/__main__.py", line 143, in main
      build_in_directory(args)
    File "/Users/runner/work/_temp/cibw/lib/python3.12/site-packages/cibuildwheel/__main__.py", line 315, in build_in_directory
      platform_module.build(options, tmp_path)
    File "/Users/runner/work/_temp/cibw/lib/python3.12/site-packages/cibuildwheel/macos.py", line 643, in build
      (build_options.output_dir / repaired_wheel.name).unlink()
    File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/pathlib.py", line 1342, in unlink
      os.unlink(self)
  NotADirectoryError: [Errno 20] Not a directory: '/Users/runner/work/FizzBuzz/FizzBuzz/wheelhouse/fizzbuzz-2.1.0-cp39-cp39-macosx_11_0_arm64.whl'
  Error: Process completed with exit code 1.
```
- Previously passed (no tests): https://github.com/MusicalNinjaDad/FizzBuzz/actions/runs/9108520076/job/25039459108
- Subsequently passed with workaround (added `&& mkdir wheelhouse` to `tool.cibuildwheel.macos.before-all`): https://github.com/MusicalNinjaDad/FizzBuzz/actions/runs/9354284188/job/25746806904

### Build log

https://github.com/MusicalNinjaDad/FizzBuzz/actions/runs/9351587993/job/25744497746

### CI config

https://github.com/MusicalNinjaDad/FizzBuzz/tree/pr48

**Comment by MusicalNinjaDad** [comment]
Happy to also put in a PR for this as it should be a quick fix to replace `with suppress` with `(missing_ok=True)`. I'll also see if I can update the CI to catch this in future.
Cloning now ...

**Comment by henryiii** [comment]
I believe CPython just translates the OS error code into Python errors. The error code 20 becomes NotADirectoryError. My initial uninformed guess would be the code is different.

**Comment by henryiii** [comment]
You shouldn’t have to make the wheelhouse directory
