### ISSUE TITLE
manylinux-2014 references mirrorlist.centos.org which does not exist....

### ISSUE THREAD

**Issue by epeisach** [pypa/cibuildwheel#1915]
### Description

Discovered today with linux build.  As Centos-7 reached EOL -- but still being supported - mirrorlist.centos.org was decommissioned, breaking "before-all" installation of packages using yum.

https://serverfault.com/questions/1161816/mirrorlist-centos-org-no-longer-resolve#:~:text=Centos%207%20has%20reached%20EOL,centos.org%20will%20work%20well.

suggests a simple sed script to change mirrorlists.centos.org to vault.centos.org.

Perhaps documentation could suggest this?

The following is working for me:

before-all = "sed -i s/mirror.centos.org/vault.centos.org/g /etc/yum.repos.d/*.repo ; sed -i s/^#.*baseurl=http/baseurl=http/g /etc/yum.repos.d/*.repo; yum -y install flex bison cmake"

I am happy for cibuildwheel to continue with centos-7 as I have servers that require it.  Just a little tweak needed.

**Comment by henryiii** [comment]
We are fixing this in the next version (very soon). See https://github.com/pypa/cibuildwheel/pull/1889#issuecomment-2200795256.

**Comment by 1yefuwang1** [comment]
This one works for me as a workaround for now
`before-build = "sed -i 's/mirrorlist/#mirrorlist/g' /etc/yum.repos.d/CentOS-*; sed -i 's|#baseurl=http://mirror.centos.org|baseurl=http://vault.centos.org|g' /etc/yum.repos.d/CentOS-*;yum install -y ninja-build"`

**Comment by henryiii** [comment]
When this finishes, we can bump our pinned images and release (if it's me, ~6-8 hours from now):

https://app.travis-ci.com/github/pypa/manylinux/builds/271224417

**Comment by henryiii** [comment]
This is the PR that fixes it: https://github.com/pypa/cibuildwheel/pull/1917

**Comment by henryiii** [comment]
Please update, latest versions should fix it!
