### ISSUE TITLE
Create a `CIBW_ALLOW_EMPTY` environment variable for `--allow-empty`

### ISSUE THREAD

**Issue by ConorMacBride** [pypa/cibuildwheel#1922]
### Description

Would it be possible to enable the CLI flag `--allow-empty` via an environment variable (e.g., `CIBW_ALLOW_EMPTY`)?

Here's our use case:
- We are running a matrix of build jobs in GitHub Actions.
- One of these jobs is `cp313-manylinux_x86_64`.
- Nightly builds will set `CIBW_PRERELEASE_PYTHONS=1` but otherwise this job will not match any wheels.
- We'd like to set the `--allow-empty` flag, but it currently doesn't seem possible through the cibuildwheel GitHub Action.
- (More details: https://github.com/OpenAstronomy/github-actions-workflows/issues/212)

I'm thinking we could compute its value similarly to how `CIBW_PRERELEASE_PYTHONS` is handled:
https://github.com/pypa/cibuildwheel/blob/a4d24056efa85210272c30da9eb1a88add065508/cibuildwheel/options.py#L523-L525

This could be integrated within `options.compute_options` and added to `options.GlobalOptions`:
https://github.com/pypa/cibuildwheel/blob/a4d24056efa85210272c30da9eb1a88add065508/cibuildwheel/options.py#L71-L77

Alternatively, `CIBW_ALLOW_EMPTY` could be checked directly within `__main__.py`:
https://github.com/pypa/cibuildwheel/blob/a4d24056efa85210272c30da9eb1a88add065508/cibuildwheel/__main__.py#L337-L338

I'm happy to open a PR if you think a new environment variable would be appropriate for this option. Thanks!

**Comment by joerick** [comment]
Sounds good! The first implementation idea above makes the most sense to me.
