### ISSUE TITLE
unsupported platform tag `linux_*` instead of `manylinux_*` generated

### ISSUE THREAD

**Issue by LecrisUT** [pypa/cibuildwheel#1929]
### Description

I am not sure whether this is a cibuildweel, scikit-build-core or a more general issue, but the generated artifacts that I get recently have an unsupported tag for PyPI `spglib-2.5.1.dev3+g0028515-cp311-cp311-linux_aarch64.whl` compared to 3 months ago `spglib-2.4.0-cp311-cp311-manylinux_2_17_aarch64.whl`. I've considered that this could be fixed by #1917, but updating the action did not fix it. Any ideas what is going on?

Failed release: https://github.com/spglib/spglib/actions/runs/9851199010
Updated action: https://github.com/spglib/spglib/pull/507

Tagging @henryiii 

---

Might be an issue with not running `auditwheel`?

**Comment by henryiii** [comment]
It's a scikit-build-core update, we were hit by [this bug](https://github.com/pypa/packaging/issues/160) in packaging; we never intended to produce "many"/"musl" in our tag names - we don't run auditwheel for you! You are disabling auditwheel: https://github.com/spglib/spglib/blob/3368f9eed4c74972f997558069cd3146d173b659/pyproject.toml#L108 so the wheels are not guaranteed to run on many linuxes.

If you _had_ do to this, you could use `wheel tags --remove --platform-tag manylinux_2_17_aarch64 {wheel}` as your repair command, but I'd _highly_ recommend fixing auditwheel instead.

**Comment by LecrisUT** [comment]
Yeah, I'm hitting the issue that I don't want the RPATH to be patched for the wheel, but then the audit fails because it is trying to fix that. I am still trying to think of ways how to better package to work around this, but probably what I will go for is for the wheel to always be statically linked, and if they want to install linking to local, that would be controlled by the sdist build.

Thanks for the tip of `wheel tags`, I will try it out, just as a dirty fix for this specific release while I work on refactoring the build system. I don't quite see in `auditwheel` how the appropriate tag is specified, I guess the default is dynamic based on the current environment?

**Comment by LecrisUT** [comment]
Managed to patch it upstream. Still need to rethink the packaging model. Thanks for the advice.
