### ISSUE TITLE
cibuildwheel fails on Linux Bamboo Agents because container doesn't have network access

### ISSUE THREAD

**Issue by gcarabi** [pypa/cibuildwheel#1945]
### Description

I had some build issues with cibuildwheel on a Linux Bamboo Agent becuse the docker container had no internet access.
Building wheel...

    + rm -rf /tmp/cibuildwheel/built_wheel
    + mkdir -p /tmp/cibuildwheel/built_wheel
    + python -m build /project --wheel --outdir=/tmp/cibuildwheel/built_wheel
Creating venv isolated environment...
Installing packages in isolated environment... (setuptools >= 61.0, wheel)
WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='[pypi.org](http://pypi.org/)', port=443): Read timed out. (read timeout=15)")': /simple/wheel/
WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='[pypi.org](http://pypi.org/)', port=443): Read timed out. (read timeout=15)")': /simple/wheel/
WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='[pypi.org](http://pypi.org/)', port=443): Read timed out. (read timeout=15)")': /simple/wheel/
WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='[pypi.org](http://pypi.org/)', port=443): Read timed out. (read timeout=15)")': /simple/wheel/
WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='[pypi.org](http://pypi.org/)', port=443): Read timed out. (read timeout=15)")': /simple/wheel/
ERROR: Could not find a version that satisfies the requirement wheel (from versions: none)
ERROR: No matching distribution found for wheel

The fix was to use the same work around as for Travis CI:

    # work-around for Travis-CI PPC64le Docker runs since 2021:
    # this avoids network splits
    # https://github.com/pypa/cibuildwheel/issues/904
    # https://github.com/conda-forge/conda-smithy/pull/1520
    #network_args = []
    #if detect_ci_provider() == CIProvider.travis_ci and platform.machine() == "ppc64le":
    network_args = ["--network=host"]

**Comment by joerick** [comment]
Since Bamboo isn't a supported platform, your best bet could be to work around this using the container-engine option, e.g. `CIBW_CONTAINER_ENGINE="docker; create_args: --network=host"`
