### ISSUE TITLE
`manylinux1_aarch64` is an undefined platform but gets built

### ISSUE THREAD

**Issue by Rot127** [pypa/cibuildwheel#1972]
### Description

According to https://github.com/pypi/warehouse/issues/6599#issuecomment-529432454 and https://github.com/pypa/manylinux/issues/84 `manylinux1` is not defined for `AArch64`.

But `cibuildwheel` generates wheels which are named `manylinux1_aarch64` if:

```
          CIBW_ARCHS_LINUX: "x86_64 i686 aarch64"
          CIBW_BUILD: "cp38-* cp39-* cp310-* cp311-* cp312-*"
```

The consequence is that pypi rejects the built wheel with:
```
ERROR    HTTPError: 400 Bad Request from https://upload.pypi.org/legacy/        
         Binary wheel                                                           
         'capstone-5.0.2-py3-none-manylinux1_aarch64.manylinux_2_17_aarch64.many
         linux2014_aarch64.whl' has an unsupported platform tag                 
         'manylinux1_aarch64'.
```

**Comment by henryiii** [comment]
Auditwheel is likely noticing you don’t use anything past manylinux1 and is setting that. I think either auditwheel needs to have an arch dependent floor or PyPI needs to accept tags that never had a supported image to build it. I think the correct way to do it is the former, though.

**Comment by mayeut** [comment]
The tag does not come from auditwheel.
Auditwheel will only ever replace a `linux_{arch}` tag however in https://github.com/capstone-engine/capstone/blob/v5/bindings/python/setup.py#L214, the platform is manually set to manylinux1. This tag does not get replaced.

**Comment by Rot127** [comment]
Oh boy. Now I feel stupid. Thank you :D

**Comment by Rot127** [comment]
So there is still the problem that out `setup.py` injects `--plat_name` into `argv` because it won't get set by `-m build wheel` (I think?). But this is a separated issue and is probably the fault of the 8-10year old Python code there.
@mayeut Thanks again. Nothing makes one quicker awake than old hard-coded fixes you never expect to be there in the first place.
