### ISSUE TITLE
exec format error when cross-compiling aarch64 with manylinux2014_aarch64

### ISSUE THREAD

**Issue by louisabraham** [pypa/cibuildwheel#1977]
### Description

This job failed when I added `CIBW_ARCHS_LINUX: auto aarch64`

https://github.com/louisabraham/pydivsufsort/actions/runs/10451200097/job/28937213392

Skipping the non relevant content:

```
Starting container image quay.io/pypa/manylinux2014_aarch64:2024.08.03-1...
  info: This container will host the build for cp39-manylinux_aarch64, cp310-manylinux_aarch64, cp311-manylinux_aarch64, cp312-manylinux_aarch64, cp313-manylinux_aarch64...
  Unable to find image 'quay.io/pypa/manylinux2014_aarch64:2024.08.03-1' locally
  2024.08.03-1: Pulling from pypa/manylinux2014_aarch64
[...]
  Status: Downloaded newer image for quay.io/pypa/manylinux2014_aarch64:2024.08.03-1
  WARNING: The requested image's platform (linux/arm64) does not match the detected host platform (linux/amd64/v3) and no specific platform was requested
  63ed3603266730f8623b7e656725bb2e9fb8cae68af8983457273d40d0e78e30
      + /bin/true
  exec /usr/local/bin/manylinux-entrypoint: exec format error
```

### Build log

https://github.com/louisabraham/pydivsufsort/actions/runs/10451200097/job/28937213392

### CI config

https://github.com/louisabraham/pydivsufsort/blob/8f8db4e5ef4f1a455dbd89658b4b494c3fea4559/.github/workflows/build-and-upload.yml

**Comment by mayeut** [comment]
QEMU setup is missing in the workflow: https://cibuildwheel.pypa.io/en/stable/faq/#emulation

**Comment by louisabraham** [comment]
Thank you very much!
