### ISSUE TITLE
File ownership not preserved when copying the project inside the container

### ISSUE THREAD

**Issue by mayeut** [pypa/cibuildwheel#2004]
### Description

File ownership not preserved when copying the project inside the container

Regression introduced by https://github.com/pypa/cibuildwheel/pull/1961

Originally reported by @cdce8p  in https://github.com/pypa/cibuildwheel/pull/1961#issuecomment-2349484355

FYI This change causes a build failure for mypy on `manylinux` and `musllinux` with Github actions and `ubuntu-latest`.
https://github.com/mypyc/mypy_mypyc-wheels/actions/runs/10852483095/job/30118641732#step:4:461

For the build, the mypy repo is first cloned in a previous step and cibuildwheel subsequently run with `package-dir: mypy`.

The error
```
fatal: detected dubious ownership in repository at '/project/mypy'
```

--
I was able to work around it by adding this to `linux.before-all`:
```
git config --global --add safe.directory {project}/mypy
```
The link to the PR: https://github.com/mypyc/mypy_mypyc-wheels/pull/82

**Comment by cdce8p** [comment]
Just tested `2.21.1` and the issue is resolved. Thanks for working on it @mayeut!
