### ISSUE TITLE
Travis CI status unclear

### ISSUE THREAD

**Issue by akx** [pypa/cibuildwheel#2069]
### Description

The Travis status badge in the readme leads to https://travis-ci.com/pypa/cibuildwheel which redirects to a login page.

I've understood Travis has stopped doing OSS builds some time back – should the badge be removed, or the build fixed?

(Sibling issue of #2068.)

**Comment by henryiii** [comment]
Travis 100% still works, it is terribly slow and one build at a time is allowed, and times out sometimes, but you can see it on all the PRs. I _think_ you have to request OS support, but the PyPA has done that.

**Comment by akx** [comment]
Alright, thanks! Feel free to close if this is non-actionable :)

**Comment by Czaki** [comment]
The link is Invalid. I have opened PR to fix it.
