### ISSUE TITLE
Choosing both arm64 and x86_64 build on macosx fails with meson and pkg-config

### ISSUE THREAD

**Issue by subhacom** [pypa/cibuildwheel#2088]
### Description

When building a Python c/c++ extension with github actions, macosx build fails, claiming pkg-config cannot be found.
```
        C compiler for the host machine: cc -arch arm64 (clang 15.0.0 "Apple clang version 15.0.0 (clang-1500.3.9.4)")
        C linker for the host machine: cc -arch arm64 ld64 1053.12
        C++ compiler for the host machine: c++ -arch arm64 (clang 15.0.0 "Apple clang version 15.0.0 (clang-1500.3.9.4)")
        C++ linker for the host machine: c++ -arch arm64 ld64 1053.12
        C compiler for the build machine: cc (clang 15.0.0 "Apple clang version 15.0.0 (clang-1500.3.9.4)")
        C linker for the build machine: cc ld64 1053.12
        C++ compiler for the build machine: c++ (clang 15.0.0 "Apple clang version 15.0.0 (clang-1500.3.9.4)")
        C++ linker for the build machine: c++ ld64 1053.12
        Build machine cpu family: x86_64
        Build machine cpu: x86_64
        Host machine cpu family: aarch64
        Host machine cpu: arm64
        Target machine cpu family: aarch64
        Target machine cpu: arm64
        Found pkg-config: NO
        pybind11-config found: YES (/private/var/folders/g6/rgtlsw6n123b0gt5483s5_cm0000gn/T/pip-build-env-w42vozeg/overlay/bin/pybind11-config) 2.13.6
        Run-time dependency pybind11 found: YES 2.13.6
        Found CMake: NO
        Run-time dependency gsl found: NO (tried framework)
        
        ../meson.build:20:10: ERROR: Dependency lookup for gsl with method 'pkgconfig' failed: Pkg-config for machine host machine not found. Giving up.
```

However, the configuration specifically installs pkg-config with brew before build:

```
          CIBW_BEFORE_ALL_MACOS: >
            brew install pkg-config gsl hdf5 meson &&
            which pkg-config 
```
And the log shows it was indeed installed:

```
Running before_all...
  
  + brew install pkg-config gsl hdf5 meson && which pkg-config 
  
  Warning: pkg-config 0.29.2_3 is already installed and up-to-date.
  To reinstall 0.29.2_3, run:
    brew reinstall pkg-config
  
  Warning: gsl 2.8 is already installed and up-to-date.
  To reinstall 2.8, run:
    brew reinstall gsl
  
  Warning: hdf5 1.14.4.3 is already installed and up-to-date.
  To reinstall 1.14.4.3, run:
    brew reinstall hdf5
...
  Bash completion has been installed to:
    /opt/homebrew/etc/bash_completion.d
  /opt/homebrew/bin/pkg-config
```
If only arm64 is selected, the build works.

### Build log

https://github.com/subhacom/moose-core/actions/runs/11915438410/job/33205701488

### CI config

https://github.com/subhacom/moose-core/actions/runs/11915438410/workflow

### Edit: 
I was mistaken, even choosing arm64 alone throws the same error.

**Comment by Czaki** [comment]
If I correctly read log it fails with lookup for `gls` package using pkg-config. So pkg-config is working but cannot find `gls` for architecture used as target for wheel. 

From brew you only could install library in version for your machine, not cross compiled one.

**Comment by subhacom** [comment]
But why is meson saying `Found pkg-config: NO`? Also, isn't `CIBW_BEFORE_ALL_MACOS: brew install pkg-config` supposed to install pkg-config on the build machine?

**Comment by subhacom** [comment]
BTW, in another workflow of the same project `pip install .` works fine for building on github macOS host. Could the issue be that the build machine on github macOS host is x86_64 but is trying to cross-compile for arm64?

**Comment by henryiii** [comment]
You should use macOS-13 for Intel and macOS-14 for ARM if possible, to avoid cross-compiling. You can't use brew to install libraries you want to link in, but in this case, it looks like you can't use brew to install even a binary you just use (pkg-config), because Meson is looking for a Universal version of it, brew never builds Universal. (`Pkg-config for machine host machine not found.` I'm assuming means it can't find a pkg-config that supports x86_64?)

**Comment by subhacom** [comment]
Interestingly github macOS-14 runner host is supposed to be Apple M1 (https://github.com/orgs/community/discussions/19197), and that is what my other workflow with `pip` builds for. I am not sure why `cibuildwheel` is showing the build cpu (virtual?) to be `x86_64` on the same system. 
I vaguely remember on M1 MacOS had some issue with homebrew/python where the x86_64 libs got installed instead of ARM64.

**Comment by henryiii** [comment]
I don't see why it's trying to build x86_64, the only arch setting I see (in pyproject.toml) is auto, which should only be the native arch. If you set the arch with x86_64 or universal2 as an option, then it will be try to build for Intel, but I don't see that.

**Comment by henryiii** [comment]
Oh, nevermind, you are building for Python 3.8. 3.8's support for ARM was really wonky (and 3.8 is now EoL, hooray!). If you pre-install the GitHub Actions CPython 3.8, then you'll get the native 3.8 ARM support (and won't be able to cross-compile).

**Comment by subhacom** [comment]
That was the problem! Removing cp38 build solved it.
Interestingly github macOS-14 runner host is supposed to be Apple M1 (https://github.com/orgs/community/discussions/19197), and that is what my other workflow with `pip` builds for. I am not sure why `cibuildwheel` is showing the build cpu (virtual?) to be `x86_64` on the same system. 
I vaguely remember on M1 MacOS had some issue with homebrew/python where the x86_64 libs got installed instead of ARM64.

**Comment by henryiii** [comment]
See the link above. It's because we use the Intel Python on ARM; the universal build has issues since they just squeezed it in before the deadline for bug fix releases (and therefore binaries) for 3.8 ended. Adding the setup-python step for 3.8 would fix it because it downloads the official Universal build, which has issues targeting Intel, but otherwise works better on ARM.

I wonder if we should change this to download the Universal build on 3.0 for 3.8, and just throw an error if macOS target is set below 11 in that case?

**Comment by subhacom** [comment]
Yes, a clear and more explicit error message will surely help.

**Comment by henryiii** [comment]
This would optimize for a different use case (building ARM wheels on ARM), and make the other situation (building Intel wheels on ARM) require a workaround - a much harder workaround, as you can't easily get the Intel-only installer from GitHub Actions. Though we can detect mistakes this path this and produce a better error message.
