### ISSUE TITLE
How to avoid duplicate build of abi3 wheels?

### ISSUE THREAD

**Issue by metab0t** [pypa/cibuildwheel#2091]
### Description

My project PyOptInterface uses nanobind and scikit-build-core to build wheels, and I find that CIBW builds the exactly same abi3 wheels under Python 3.12 and 3.13.

Is there some solution to rename the built wheels as abi3 tag and eliminate the unnecessary build process?

### Build log

https://github.com/metab0t/PyOptInterface/actions/runs/11966956691/job/33363432013

### CI config

https://github.com/metab0t/PyOptInterface/blob/master/.github/workflows/wheel.yml

**Comment by henryiii** [comment]
Yes, set, in pyproject.toml:

```toml
[tool.scikit-build]
# Build stable ABI wheels for CPython 3.12+
wheel.py-api = "cp312"
```

Then 3.12 and higher will use the same wheel name, and cibuildwheel will only test in for 3.13, and not try to build it again.

(See https://github.com/wjakob/nanobind_example/blob/master/CMakeLists.txt or the scikit-build-core docs)

**Comment by metab0t** [comment]
Thanks! I will try it.
