### ISSUE TITLE
Stable ABI3 wheels should be tested on all applicable python versions

### ISSUE THREAD

**Issue by rhpvorderman** [pypa/cibuildwheel#2102]
### Description

For example: stable ABI supports 3.10 and higher. CiBuildwheel builds wheel for only 3.10. That is already possible, but it should also test on 3.10  **and** 3.11, 3.12 and 3.13. There might be some deprecation in the python code in 3.13 for example. I'd rather cibuildwheel finds that before uploading to PyPI.
Yes I try to make sure all versions of python are properly tested before releasing, but I prefer only to upload wheels that are thoroughly tested on the python versions they support. That is currently not possible on stable ABI3 wheels using cibuildwheel.

**Comment by Czaki** [comment]
Since version 2.5.0 this is how cibuildwheel works. Did you meet some problem?

https://cibuildwheel.pypa.io/en/stable/changelog/#v250

**Comment by rhpvorderman** [comment]
Whoops. My bad. I see in the build logs now that that is what is done indeed. I saw all the "build" steps and assumed it was building something. I am sorry for creating an irrelevant issue.

**Comment by da-woods** [comment]
Quick note that this doesn't work using "prebuild a matrix with `jq` and pass it in a `with: only: ${{ matrix.only }}` that some projects use (e.g. https://github.com/pypa/cibuildwheel/discussions/1261).

Not really a complaint - it's perfectly understandable _why_ this doesn't work - just a note for future people that you need to make sure it's going through all the Python versions you want covered on a single runner.
