### ISSUE TITLE
Py 3.12 build, no module named pip

### ISSUE THREAD

**Issue by adhadseKavida** [pypa/cibuildwheel#2106]
### Description

I'm trying to build a many linux build on python 3.11 and 3.12. 3.11 build completes but the 3.12 doesn't finishes. It gives an error message no module named pip even though it's there.

### Build log

https://github.com/adhadse/excelFormExtractor/actions/runs/12117992173/job/33781576936

### CI config

https://github.com/adhadse/excelFormExtractor/blob/master/.github/workflows/build.yaml

**Comment by adhadse** [comment]
This issue is no longer required. 

I fixed it by removing `pip install pybindgen` from `setup_ci.py` and moved it to github action, under `CIBW_BEFORE_BUILD` env for cibbuildwheel. you may check the above build.yaml file.

closing the issue
