### ISSUE TITLE
[idea] pypa-build support

### ISSUE THREAD

**Issue by henryiii** [pypa/cibuildwheel#442]
Currently, we (along with most of the Python ecosystem) are misusing the `pip wheel` command to build wheels. It was the best available tool, but only because it was the only available tool; it wasn't really designed for wheel building. One side effect is that _all_ wheels are built into the "wheelhouse", and users have to pick out just the correct ones. This is partially mitigated by including "--no-deps", but that is just a hack solution that also requires more hacks (requiring dependencies to be installed separately, etc), and PEP 518 dependencies could possibly trigger more wheels. My recommendation so far has always been to use `<package_name>*.whl` when uploading/moving outputs to avoid grabbing an extra built dependency.

There is a solution; a proper PEP 517 builder instead of using the wheelhouse output. The infrastructure for it has been around (the `pep517` package, which pip vendors and uses, actually), but a proper front end has not been available until quite recently (not counting `pep517.build`, which was intended as an example, not intended for widespread use - though it was picked up by a large number of packages before being pulled).

A very young package, [targeted for PPA inclusion](https://github.com/FFY00/python-build/issues/42), is finally available and is the recommended migration path for `pep517.build`: [`python-build`](https://python-build.readthedocs.io/en/latest/). I think it would be a good idea to support this in cibuildwheel. Ideas:

I think we shouldn't lock in `build`, at least at this early point, partially because this could change in the near future. So how about providing a new environment variable that overrides the default build command, so that you could write `CIBW_BUILD_CMD="python -m build -w -o {output_dir}"`; when combined with `CIBW_BEFORE_BUILD: pip install build`, this should work, I think. Eventually, if this gets accepted into the PyPA and settles down, we could make this a simpler toggle and have it in the constraints file, perhaps?

Thoughts? Just putting it down while thinking about it, no rush.

Edit: It would also be nice to be able to adjust the build command, either to remove `--no-deps` or in **special** cases to add `--no-build-isolation`.

PS: Personally, I've been moving most pure python wheels to `build`, since it can build SDists using pyproject.toml, which pip cannot.

**Comment by Czaki** [comment]
> Edit: It would also be nice to be able to adjust the build command, either to remove `--no-deps` or in **special** cases to add `--no-build-isolation`.

Could you show example where `--no-build-isolation` is needed for package build using `cibuildwheel`. Its using allows to check already installed packages, which could be useful to conditionally compile some wraper, but I see no profit for use it in cibuildwheel. 

Also I do not understand why You may would to remove `--no-deps` 

Maybe I'm wrong, but still all python packages with compile extensions needs setup.py to work. `pyproject.toml` does not allow to define alternative of `Extension` from `setuptools`. 

For me `python-build` looks like very young project which cannot be et as default backend. Many peoples does not use `pyproject.toml` in their packages.  Could even `python-build` build wheel with C-extensions? (for ex poerty cannot). And if yes, then how it works? It does not call `wheel` package in background?

**Comment by YannickJadoul** [comment]
I agree moving forward to newer tools (or at least exploring them) would be nice, indeed! :-)

A few thoughts, though:

> So how about providing a new environment variable that overrides the default build command, so that you could write `CIBW_BUILD_CMD="python -m build -w -o {output_dir}"`; when combined with `CIBW_BEFORE_BUILD: pip install build`, this should work, I think.

I've never been a big fan of `CIBW_BUILD_COMMAND`, before. It's been suggested as a solution to a few other problems in the past, but it's really the core of `cibuildwheel`, and before you know, people aren't building wheels anymore (and we need to rename it to `cibuildanything`?). Also, not being able to change this forces users to create a `setup.py` (or `pyproject.toml`) that really works and takes everything into account; so it's kind of a check if the library is `pip`-installable from source (or am I wrong, here?).
I'd prefer something a bit more high-level, like `CIBW_BUILD_BACKEND=pip` or `CIBW_BUILD_BACKEND=python-build` or so.

As @Czaki says: why would you want to remove `--no-deps` or add other flags? Wouldn't there be other ways; because adding this to `pip wheel` would not have an impact on installing from source?

> PS: Personally, I've been moving most pure python wheels to `build`, since it can build SDists using pyproject.toml, which pip cannot.

Heh, yeah, that's a whole other discussion, on whether `cibuildwheel` should make sdists; see #173, if you have great ideas on how to approach this ;-)

**Comment by henryiii** [comment]
The main user of `--no-build-isolation` is conda - since it sets up its own package structure, you don't want it grabbing PyPI packages. That's why I highlighted "special" - it's not the norm. But, for example, imaging a package requiring `cmake` and trying to build on a platform that doesn't have a CMake wheel (specifically, PowerPC manylinux2014). You could use `--no-build-isolation` and install CMake manually, for example.

> Also I do not understand why You may would to remove

This breaks packages that use `setup_requires` and requires manual workarounds. While I'm not a big fan of using setup_requires (PEP 518 is much better), cibuildwheel is intentionally breaking this due to a side-effect (downloading extra wheels and putting them in the output directory), not because `setup_requires` itself is an issue. The extra wheels probably should be solved a different way, perhaps? It's not something I'm personally worried about, because I wouldn't write a package without a pyproject.toml.

> Maybe I'm wrong, but still all python packages with compile extensions needs setup.py to work.

Not true anymore, someone called me out on that. Enscons is an extension capable PEP 517 build tool. You don't have to like SCONS, but it does exist. Though this really isn't about setup.py.

> For me python-build looks like very young project which cannot be et as default backend.

I explicitly said "shouldn't lock in" and "a simpler toggle"; I'd like a way to use it, not to make it default. Look at https://github.com/FFY00/python-build/issues/101#issuecomment-705239947 - if this is accepted into the PyPA, and it's so far unanimous, this will become _the_ way, the authoritative way to build python packages. (Pip maintainers have been very unhappy about having to maintain "wheel", and have refused to add "sdist", because they don't want to be in the building business).

It's young, but it's really just a front-end to `pep517` (the package, not the PEP), which is quite mature and _exactly_ (vendored) what pip uses already.

> poerty cannot

build is a _builder_ that uses PEP 517 backends. So it runs setuptools, poetry, flit, enscons, etc. Exactly like `pip wheel` does. It either falls back (just like pip does) when pyproject.toml, or it complains it is not PEP 517 compliant - I don't know because all of my projects have a pyproject.toml. 

> It does not call wheel package in background

Yes, it uses wheel, pep517, etc. I think it currently, rather oddly requires setuptools too.

**Comment by henryiii** [comment]
> `CIBW_BUILD_BACKEND=pip`

This is what I called "a simpler toggle". Since they are still discussion the name (see the above two linked issues), it's too early I think for this. If that's the best way forward, then we should probably keep this in mind and wait to see what happens if(when?) it moves to PyPA.

> before you know, people aren't building wheels anymore

I'm not sure what else you'd build? Eggs? It seems more like an emergency escape hatch for power users to test things like we are discussing testing here?

> cibuildwheel should make sdists

Given that this is one line (`python -m build -s` if you want the pep518 enabled modern one), I wouldn't think so. If you could reliably run cibuildwheel job, it would be tempting - but then that would only be true for a single OS. I'd call it `cibuildsdist` then. :P

Really, cibuildwheel shouldn't be trying to recreate PEP 518. The biggest issue was SDists that required things in pyproject.toml (or, hopefully not, in CIBW variables), and that's being solved correctly by python-build (or whatever it ends up being moved to in the PyPA).

**Comment by henryiii** [comment]
Actually, adding pip flags can be done by environment markers, so ignore what I said about `--no-build-isolation`, just set `PIP_NO_BUILD_ISOLATION` (duh), but there is still no way to reenable `--no-deps`, which disables `setup_requires`. Personally I don't care that much about that - pyproject.toml is the correct solution, and setup_requires is deprecated.

[ASIDE] But it would be nice to have a way to keep extra wheels from being added to the output directory, which still can happen (IIRC) with pyproject.toml requirements (though tends to be rare, since the pyproject.toml requirements are very limited usually; NumPy is the standard culprit).

So really, a backend toggle might be enough, then - though probably should wait a bit until python-build's future is settled. On hold, perhaps? Or a "experimental" setting for now?

**Comment by Czaki** [comment]
> Not true anymore, someone called me out on that. Enscons is an extension capable PEP 517 build tool. You don't have to like SCONS, but it does exist. Though this really isn't about setup.py.

Did you know any example? IT looks very interesting. Could it be used with cython? 


As I see `pip wheel` could build package which is not pep 517. There are many of them. Did this package works with old one? I do fast check in code and it look like this backend requires `pyproject.toml` file.

**Comment by joerick** [comment]
Thanks for bringing this to the project, @henryiii. I also think this _kind_ of thing is going to be the future of wheel building. The `pip wheel` thing always felt a little janky.

The central questions seem to be-

- When should we start supporting `python-build`?
- Do we use a high-level toggle `CIBW_BUILD_BACKEND=python-build` or a low-level setting `CIBW_BUILD_COMMAND=python -m build -w -o {output_dir}`

> I've never been a big fan of `CIBW_BUILD_COMMAND`, before. It's been suggested as a solution to a few other problems in the past, but it's really the core of `cibuildwheel`, and before you know, people aren't building wheels anymore (and we need to rename it to `cibuildanything`?). Also, not being able to change this forces users to create a `setup.py` (or `pyproject.toml`) that really works and takes everything into account; so it's kind of a check if the library is `pip`-installable from source (or am I wrong, here?).
> I'd prefer something a bit more high-level, like `CIBW_BUILD_BACKEND=pip` or `CIBW_BUILD_BACKEND=python-build` or so.

My initial inclination is also towards a high-level toggle. I can imagine that we might need to write `if build_backend == 'pip` or similar, elsewhere in the script. And really cibuildwheel's goal is to invoke that build backend command with the right environment. Without that goal, we're more like a `tox` equivalent.

(That doesn't mean that `CIBW_BUILD_COMMAND` might be useful. But so far, whenever `CIBW_BUILD_COMMAND` comes up, we discuss and find a way around the problem without implementing the feature)

As for when we do it, I'd like to support this `python-build` effort, so I wouldn't mind adding a `CIBW_BUILD_BACKEND=python-build` option as soon as feasible, as long as it's marked as experimental/unstable in the docs. Our version pinning should prevent API changes from being a problem, but probably better to wait until it's stable before recommending it to our users.

**Comment by henryiii** [comment]
From the discussion, it looks like the PyPI package name (`build`) and the module name (`build`) are likely to be stable. The entry point, `python-build`, might become `pypa-build`, and the GitHub repo might move. Anyway, I think it's getting close enough that a clearly marked "experimental" or hidden option would be safe to add.

**Comment by YannickJadoul** [comment]
> just set `PIP_NO_BUILD_ISOLATION` (duh)

Ofc! Completely forgot about that, even though I use `PIP_PREFER_BINARY` myself, somewhere.

But good, I think we all kind of agree? I like @joerick's suggestion of the exerimental route, which can show us how many complications we'll still bump into :-) If things go smoothly, we not offer it as a non-default option, soon?

And, yes, if possible, let's stick with the high-level options; to me, it's really part of cibuildwheel's abstraction layer (as @joerick compares to `tox` :-) ).

**Comment by henryiii** [comment]
`pypa-build` (was `python-build`) was moved to the pypa recently: https://github.com/pypa/build !

**Comment by YannickJadoul** [comment]
> `pypa-build` (was `python-build`) was moved to the pypa recently: https://github.com/pypa/build !

So, now I'm definitely up to push this a bit further and see how things fit together! :-)
All in all, it might not be that hard to change? A few new requirements (and remove `wheel`?), and change `pip wheel` into `python -m build`?

**Comment by Czaki** [comment]
python-build is pep-517 build system. So it cannot build projects without `pyproject.toml`. So there should be `if` which checks the presence of `pyproject.toml` file and base on this decide which system use.  So I think that this check should be done in the main function and the command should be passed as an argument of the build function.

**Comment by henryiii** [comment]
> So it cannot build projects without pyproject.toml

Actually, yes it can. Currently it falls back kind of like (but not exactly like) pip. I think this is going to change though. For now, is this is opt-in, I don't think we need to worry about a check.

**Comment by henryiii** [comment]
It's actually worked quite well, I recently ran `pipx install build`, finally putting it into my main environment, then did `pyproject-build` on a classic-style project (no pyproject). The printout making the SDist and Wheel was perfect for debugging what was missing (py.typed and *.pyi files).

For the moment, we could:

* Add build to the dependencies
* Add a switch, `CIBW_PYPA_BUILD: 1`, that would
    * Replace `python -m pip wheel .` with `python -m build`
    * Drop the workaround where `--no-deps` is added (this literally causes us to suggest users run `CIBW_BEFORE_BUILD: pip install .`, building twice, if they use setup/install requires!)

Eventually, if this works well, we could change the default in 2.0 and require "classic" projects to run `CIBW_PYPA_BUILD: 0` to force pip wheel builds.

**Comment by YannickJadoul** [comment]
Sounds good.

>    * CIBW_PYPA_BUILD: 1

This is somewhere where I could imagine a flag `--pypa-build` to be useful, as it's likely to just be a "constant" flag for all `cibuildwheel` invocations in your matrix.

Are more things on their way? If so, `--builder=pypa-build`/`--builder=pip` and/or `CIBW_BUILDER=pypa-build`/`CIBW_BUILDER=pip` could be more future-proof.

**Comment by henryiii** [comment]
I think I might like that better. I don't think that that more are coming officially, though I think anyone could make a PEP 517 builder. But setting a value looks better; you don't have 0 vs. 1. Maybe `CIBW_BUILDER=build`/`CIBW_BUILDER=pip`? With a default of pip that may change to build someday?

We don't use flags much, just for platform and arch - I'd say this is best as an env var only, unless we were to add them more often (like how pip allows every option to be a flag).

**Comment by YannickJadoul** [comment]
Sounds good to me, unless `build` is going to get renamed?

> We don't use flags much, just for platform and arch - I'd say this is best as an env var only, unless we were to add them more often (like how pip allows every option to be a flag).

True, but this could make sense to me (since it's most likely a one-time choice across all CI matrix entries). But I don't mind keeping it as environment variable either; that makes things consistent with the rest of the options;

**Comment by YannickJadoul** [comment]
> Sounds good to me, unless `build` is going to get renamed?

Seems its `pip install build` but `pypa-build.readthedocs.io`, so I guess it's not entirely clear yet? Can always be changed later, ofc :-)

**Comment by henryiii** [comment]
The pypi package and module will always be called `build` and the repository is `pypa/build`. The docs are pypa-build. The command-line tool (without `python -m`) is `pyproject-build`. (You could never add a command line tool called "build" - too many conflicts). :/

**Comment by henryiii** [comment]
I ended up editing the above comment quite a bit after you posted, forgot I had already sent. :(

**Comment by YannickJadoul** [comment]
Ah, no, thanks for the extra info. I only found half of that ;-)

So yeah, `pypa-build` would make sense to me, but if we want to support `pypa-build` to because the standard `build`, then `build` is a good choice ;-) No one else should later pick `build` anyway.

**Comment by joerick** [comment]
`CIBW_BUILDER` and `pip`/`build` makes a lot of sense to me - echoing the package names, since that's a proper namespace on PyPI.

---

Seeing as we sometimes get requests for it, while we're here there might be merit in a special option `custom` that's like... `CIBW_BUILDER: custom: myCommand {package} {output_dir}`, where you can do whatever you like. We can document that you have to take care of everything, like installing prereqs in BEFORE_BUILD, and that such use is 'unsupported'. But it might be an escape hatch that some people find useful, in a pinch.

**Comment by YannickJadoul** [comment]
> Seeing as we sometimes get requests for it, while we're here there might be merit in a special option `custom` that's like...

I've never been a huge fan of that, being afraid it will push `cibuildwheel` away from actually building wheels and people just using it as a way to run something on all versions of Python (for which `cibuildwheel` is not designed, and for which you have e.g. `tox`?). The bit of extra pressure that you can't change that build command does help designing a decent Python package.
Then again, we can't stop "responsible adults" from doing whatever they want, ofc?

(I'd leave out the `custom:`, btw, in that case, and go for a similar thing as with the docker images. "If it's `pip`, do this; if it's `build` do this; else, just verbatim use the contents." That seems to work well with `CIBW_MANYLINUX_IMAGE=manylinux2010` vs. `CIBW_MANYLINUX_IMAGE=dockcross/manylinux2014-x86 `?)

**Comment by joerick** [comment]
> (I'd leave out the `custom:`, btw, in that case, and go for a similar thing as with the docker images. "If it's `pip`, do this; if it's `build` do this; else, just verbatim use the contents." That seems to work well with `CIBW_MANYLINUX_IMAGE=manylinux2010` vs. `CIBW_MANYLINUX_IMAGE=dockcross/manylinux2014-x86 `?)

Yeah, that would work, too. I was just thinking prefix with 'custom:' to make it clear you're doing something weird and unsupported (that's less true with the custom manylinux images)

> I've never been a huge fan of that, being afraid it will push `cibuildwheel` away from actually building wheels and people just using it as a way to run something on all versions of Python (for which `cibuildwheel` is not designed, and for which you have e.g. `tox`?). The bit of extra pressure that you can't change that build command does help designing a decent Python package.
>
> Then again, we can't stop "responsible adults" from doing whatever they want, ofc?

Yeah, all good points. And, nobody is asking for it, really. You might have convinced me :)
