### ISSUE TITLE
[idea] Remove nose from testing & docs

### ISSUE THREAD

**Issue by henryiii** [pypa/cibuildwheel#499]
I've noticed the Windows Travis build failed because it couldn't download nose - can we remove nose from our tests and docs? Nose has been [abandoned since 2015](https://pypi.org/project/nose/#history) in favor of pytest, which can run nose tests (and unittest and its own pytest format too). All major packages (including NumPy) transitioned over to pytest from nose. Showing abandonware in examples is not a great idea, IMO. :)

```
git grep nose

.gitignore:nosetests.xml
docs/options.md:# run the project tests against the installed wheel using `nose`
docs/options.md:CIBW_TEST_COMMAND: nosetests {project}/tests
docs/options.md:CIBW_TEST_REQUIRES: nose==1.3.7 moto==0.4.31
test/test_before_test.py:        'CIBW_TEST_REQUIRES': 'nose',
test/test_before_test.py:        'CIBW_TEST_COMMAND': 'false || nosetests {project}/test',
test/test_before_test.py:        'CIBW_TEST_COMMAND_WINDOWS': 'nosetests {project}/test',
test/test_testing.py:        test = nose
test/test_testing.py:        'CIBW_TEST_REQUIRES': 'nose',
test/test_testing.py:        'CIBW_TEST_COMMAND': 'false || nosetests {project}/test',
test/test_testing.py:        'CIBW_TEST_COMMAND_WINDOWS': 'COLOR 00 || nosetests {project}/test',
test/test_testing.py:        'CIBW_TEST_COMMAND': 'false || nosetests {project}/test',
test/test_testing.py:        'CIBW_TEST_COMMAND_WINDOWS': 'COLOR 00 || nosetests {project}/test',
test/test_testing.py:            'CIBW_TEST_REQUIRES': 'nose',
test/test_testing.py:            'CIBW_TEST_COMMAND': 'nosetests {project}/test',
```

**Comment by joerick** [comment]
Yes, that makes sense to me. I think that originally it was `nosetests` in the testing tests rather than pytest so that we were sure that TEST_REQUIRES had worked. So it might be worth considering that when modernising. if we shell out to `pytest something` in our test, are we sure we aren't getting the host's version of pytest.

**Comment by henryiii** [comment]
Then we could add an import X, where X is something we require? Like something pure Python near the top of this list? https://pythonwheels.com/
