### ISSUE TITLE
Cancel action for GHA, auto-merge

### ISSUE THREAD

**Issue by henryiii** [pypa/cibuildwheel#526]
When we push a new run, some of the CI systems cancel, but some don't. At least for GitHub, this looks useful: https://github.com/marketplace/actions/cancel-workflow-action

---

Also, GitHub has enabled merge when required checks pass; we can use this to drop the custom badge and job workaround and have it integrated into the UI, it replaces the merge button when the checks have not passed yet:

![image](https://user-images.githubusercontent.com/4616906/104083468-cac62300-520c-11eb-9b9d-5cd10d436cff.png)

![](https://files.gitter.im/5ca61dd1d73408ce4fbcd06b/HXoj/Screen-Shot-2021-01-08-at-12.22.12-PM.png)

@joerick, you'd have to set it up. It might not be in settings quite yet, but it seems to have finally rolled out most places.

**Comment by henryiii** [comment]
You can also set custom merge commit messages, and squash and merge or rebase and merge, which is so much nicer. :) I have "force linear history" turned on now that they have that option in my repos.

**Comment by joerick** [comment]
Weird, I thought that Github did already auto-cancel if you push a newer commit? Maybe I'm wrong.

**Comment by joerick** [comment]
Sorry @henryiii, I'm gonna turn off the auto-merge, the yellow statuses are bugging me.
![image](https://user-images.githubusercontent.com/1244307/104739371-896ad180-573e-11eb-98a4-d60554d0d73a.png)

**Comment by henryiii** [comment]
Not that I'm aware of. Most other CIs do, but GitHub is designed as modular, it also does't respect `[skip ci]`.

**Comment by henryiii** [comment]
> the yellow statuses are bugging me.

Can't you just close and reopen? The problem is that there's a stale, changed name; if you close and reopen, it rebuilt with the latest config and that does away.

**Comment by henryiii** [comment]
Having to come back and check every few minutes or being stuck with an ugly, non-linear, non-controlled auto-merge bugs me. 😢

**Comment by joerick** [comment]
> Can't you just close and reopen? The problem is that there's a stale, changed name; if you close and reopen, it rebuilt with the latest config and that does away.

No, the problem is that the required check names are defined project-wide, and this PR doesn't have a check with that name, so it'll never happen.

**Comment by henryiii** [comment]
Checks come from the merged state when they start running, so this should only happen if you delete a required check in a PR, which should not pass anyway?

**Comment by henryiii** [comment]
Ah, you are unhappy about the merged PRs that suddenly pick up orange dots? That seem like a bug to some degree.
