### ISSUE TITLE
Idea: build from SDists

### ISSUE THREAD

**Issue by henryiii** [pypa/cibuildwheel#597]
Just an idea, but how about allowing the "source dir" to be (a possibly remote?) SDist? If you separate the build into a different repository, having a way to put a SDist path, or simply require a user to download an SDist then put it in as a path would negate most of the need for "astrofrog/autowheel", which doesn't seem to be maintained. Just a thought.

**Comment by mayeut** [comment]
That's a great idea.

Even in simpler workflows than the one suggested, it would undoubtedly simplify some CI workflows.
I'm sure I'm not the only one to have a specific path to test the SDist is valid and can be used. Having this feature would allow to get rid of this, the SDist would be validated by cibuildwheel.

see also:
https://discuss.python.org/t/should-building-wheels-from-sdists-be-recommended-behavior/8358/20
https://github.com/pypa/build/issues/257

**Comment by pombredanne** [comment]
I pushed a minimally working branch that works super simply: the "package_dir" CLI argument can now be an sdist tarball and will be used to build the wheel if provided. It only works with the pip build backend (and not "build").
See https://github.com/pypa/cibuildwheel/pull/1020
Feedback mucho welcomed.
