### ISSUE TITLE
Use Nox?

### ISSUE THREAD

**Issue by henryiii** [pypa/cibuildwheel#646]
In bin, we have some code that likely could be run by nox, and at least one piece of code that could be replaced by Nox. This could simplify some of the scripts - mostly looking at the first half of update_dependencies.py. It could be then run either from a Nox docker container, using the Nox action, or locally if someone has installed all the required versions of Python, without having the current `--no-docker` duplication.

This could possibly be augmented over time to take support running all our development actions, so a new developer could easily run these in a controlled environment without having to set up anything, and get a matching environment to the CI. I wasn't that fond of tox - too rigid with too many options and assumptions , but nox is not bad, much cleaner and more natural with nicer output. `pip` uses nox and tox (slowly transitioning to nox-only, I think). `packaging` and `packaging.python.org` use nox. Pretty much all the other `pypa` projects use tox.

Common dev actions would mostly be still available as a script (though the nox runner would install the requirements for you), though some actions (esp. ones like update_dependencies) could only run in Nox (mostly ones that require multiple Python versions).

Thoughts?

PS: personally, I run `pipx run nox` which means I don't have to install nox.

**Comment by henryiii** [comment]
For an example of something very similar for manylinux, see https://github.com/pypa/manylinux/pull/1055

**Comment by henryiii** [comment]
Another nox example: https://github.com/scikit-build/scikit-build-sample-projects/pull/12/files

**Comment by joerick** [comment]
nox looks like a great tool! I never used tox myself, it always had this 'heavy' feeling, probably because of the configuration files. 

> It could be then run either from a Nox docker container, using the Nox action, or locally if someone has installed all the required versions of Python, without having the current --no-docker duplication.

If this is possible, that would be great.
