### ISSUE TITLE
Changing the default branch to `main`

### ISSUE THREAD

**Issue by joerick** [pypa/cibuildwheel#690]
This is just a heads up, I'm planning to change the default branch on this repo to `main` this week, let's say Wednesday 26th. Github have a tool to change it over, and update PRs to target the new branch, but you might have to update it on local checkouts and forks. Shouldn't be a big issue though, this is what [Github say](https://github.com/github/renaming#renaming-existing-branches) about it:

> Renaming a branch will:
> 
> - Re-target any open pull requests
> - Update any draft releases based on the branch
> - Move any branch protection rules that explicitly reference the old name
> - Update the branch used to build GitHub Pages, if applicable
> - Show a notice to repository contributors, maintainers, and admins on the repository homepage with instructions to update local copies of the repository
> - Show a notice to contributors who git push to the old branch
> - Redirect web requests for the old branch name to the new branch name
> - Return a "Moved Permanently" response in API requests for the old branch name

---

Checklist for the switch:

- [x] Use the Github tool to change it over
- [x] Find/replace `master` to `main` in CI configs, docs, scripts, example code, etc
- [x] Change default branch on Readthedocs

**Comment by pradyunsg** [comment]
Experience from renaming pip's default branch is encoded here: https://github.com/pypa/pip/issues/8948

Everything on GitHub "just works", but you'll need to manually update:

- Any custom scripts.
- non-GitHub CI configuration.
- (maybe) CI commands and automation.
- ReadTheDocs configuration.

**Comment by joerick** [comment]
Thanks @pradyunsg ! That's very helpful :)

**Comment by henryiii** [comment]
One extra personal detail - remember to delete your `master` branches locally afterwards. I find it's important that 'git switch master` fail locally or otherwise I've started making PRs based on the old deleted master more than once. :/

**Comment by joerick** [comment]
This is done! Github is helpfully showing a note how to change your local repos, but if anyone missed it, the commands are:

```console
git branch -m master main
git fetch origin
git branch -u origin/main main
git remote set-head origin -a
```

**Comment by henryiii** [comment]
Interesting, if you follow those steps, local `master` goes away - ah, `-m` is move. Nice, that's helpful. Was going to recommend you also delete `master` but those instructions handle that - guess I should follow instructions instead of doing it manually from now on. ;)
