### ISSUE TITLE
allow test exit status to terminate the job

### ISSUE THREAD

**Issue by MrBitBucket** [pypa/cibuildwheel#716]
I have a test which is failing, but it seems that cibuildwheel ignores the outcome so I see this in my workflow log
```log
+++++ os.system('/tmp/tmp.UCCIlchSDf/venv/bin/python runAll.py --post-install') exited with status=256
      + rm -rf /tmp/tmp.UCCIlchSDf/venv
      + mkdir -p /output
      + mv /tmp/cibuildwheel/repaired_wheel/reportlab-3.5.67-cp38-cp38-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_12_x86_64.manylinux2010_x86_64.whl /output
                                                             ✓ 32.25s
``` 
I could not see a way to get the test return status to terminate the job. The code in say linux.py uses docker.call and seems to ignore any return; I'm not even sure if it is possible to get the command response using docker.call. 

A sample run log is https://github.com/MrBitBucket/reportlab-ci/runs/2795420699?check_suite_focus=true

Looking at the docker code it seems to just return a string and try to handle the error in the docker bash, but for me that doesn't happen.  Perhaps the code that's actually doing the test is at fault in setup.py I have this 
```
    status = os.system(cli)
    print('+++++ os.system(%s) exited with status=%s' % (repr(cli),repr(status)))
    sys.exit(status)
```

On a completely different scale I want to use the same command for the test ie  `python {project}/setup.py....`, but I am a bit stupid as to how that can be done as windows barfs I think on the '/'. Since cibuildwheel seems to encourage mixed os builds I suppose there's some useful trick to doing this.

**Comment by joerick** [comment]
Hi @MrBitBucket ! It looks like you set the CIBW_TEST_COMMAND to this:

```yaml
      CIBW_TEST_COMMAND: python -c "import sys,os;os.system(' '.join((sys.executable,os.path.join('{project}','setup.py'),'tests-postinstall')))"
```

This little mini python script is swallowing the error, because os.system returns an error code, instead of raising an exception. 

If I'm reading the above correctly, you might be better off with:

```yaml
      CIBW_TEST_COMMAND: python {project}/setup.py tests-postinstall
```

The forward-slash should work on windows, too. At least, it does in our tests.
