### ISSUE TITLE
Missing Python_INCLUDE_DIRS and Python_LIBRARIES

### ISSUE THREAD

**Issue by DaAwesomeP** [pypa/cibuildwheel#727]
I apologize if this is the wrong to place to ask for help; I'm not sure if this is an issue with my configuration or a bug.

I am trying to build a `scikit-build` CMake project with cibuildwheel on GitHub Actions. It works fine outside of cibuildwheel, but with it I get:

```
...
    [8/8] Completed 'pybind11'
    -- pybind11 v2.6.2
    -- Found PythonInterp: /opt/_internal/cpython-3.9.5/bin/python (found version "3.9.5")
    -- Found PythonLibs: libpython3.9.a
    -- Performing Test HAS_FLTO
    -- Performing Test HAS_FLTO - Success
    CMake Error at /tmp/pip-build-env-f6l4sk12/overlay/lib/python3.9/site-packages/cmake/data/share/cmake-3.20/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
      Could NOT find Python (missing: Python_INCLUDE_DIRS Python_LIBRARIES
      Development Development.Module Development.Embed) (found version "2.7.5")
    Call Stack (most recent call first):
      /tmp/pip-build-env-f6l4sk12/overlay/lib/python3.9/site-packages/cmake/data/share/cmake-3.20/Modules/FindPackageHandleStandardArgs.cmake:594 (_FPHSA_FAILURE_MESSAGE)
      /tmp/pip-build-env-f6l4sk12/overlay/lib/python3.9/site-packages/cmake/data/share/cmake-3.20/Modules/FindPython.cmake:556 (find_package_handle_standard_args)
      wrappers/python/CMakeLists.txt:62 (find_package)
```
I'm also not sure if this is an issue from scikit-build or cibuildwheel, as either cibuildwheel seems to not be passing something to scikit-build, or scikit-build is failing to setup the environment properly when using cibuildwheel.

Here is the workflow in its entirety (this issue affects the x86_64 and aarch64 builds): https://github.com/DaAwesomeP/librealsense/actions/runs/961713465

**Comment by henryiii** [comment]
Yes, it's the wrong place, but I'm a dev for both pybind11 and scikit-build too, so it works. :) Scikit-build doesn't support FindPython natively (I'm working on that, see https://github.com/scikit-build/scikit-build/pull/516 ) , but it's really easy to work around. Just get the variables Scikit-BUILD passes (`PYTHON_EXECUTABLE`, `PYTHON_INCLUDE_DIR`, `PYTHON_LIBRARY`) and set the matching FindPython hints with those (`Python_EXECUTABLE`, `Python_INCLUDE_DIR`, `Python_LIBRARY`) near the top of your CMakeLists.

It's only working locally because it happens to be finding the Python it's called from. If you call it from a different Python, it will break locally too.

**Comment by DaAwesomeP** [comment]
Thanks for the fast reponse!

Some more Googling and I found your workaround completely: https://github.com/scikit-build/scikit-build/issues/506#issuecomment-706791791

This helps but it still complains about `Python_LIBRARIES` (see [log line 1181](https://github.com/DaAwesomeP/librealsense/runs/2888259687?check_suite_focus=true#step:4:1181)):
```
...
 [8/8] Completed 'pybind11'
    -- pybind11 v2.6.2
    -- Found PythonInterp: /opt/_internal/cpython-3.9.5/bin/python (found version "3.9.5")
    -- Found PythonLibs: libpython3.9.a
    -- Performing Test HAS_FLTO
    -- Performing Test HAS_FLTO - Success
    CMake Error at /tmp/pip-build-env-nwehiqjf/overlay/lib/python3.9/site-packages/cmake/data/share/cmake-3.20/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
      Could NOT find Python (missing: Python_LIBRARIES Interpreter Development
      Development.Module Development.Embed) (found version "3.9.5")
    Call Stack (most recent call first):
      /tmp/pip-build-env-nwehiqjf/overlay/lib/python3.9/site-packages/cmake/data/share/cmake-3.20/Modules/FindPackageHandleStandardArgs.cmake:594 (_FPHSA_FAILURE_MESSAGE)
      /tmp/pip-build-env-nwehiqjf/overlay/lib/python3.9/site-packages/cmake/data/share/cmake-3.20/Modules/FindPython.cmake:556 (find_package_handle_standard_args)
      wrappers/python/CMakeLists.txt:67 (find_package)
```

Adding `set(Python_LIBRARIES "${PYTHON_LIBRARIES}")` does not fix it, neither does `set(Python_LIBRARIES "${PYTHON_LIBRARY}")`.

Any ideas? I thought `Python_LIBRARIES` was [supposed to be automatically determined](https://cmake.org/cmake/help/latest/module/FindPythonLibs.html) in reference to `Python_LIBRARY`, `Python_INCLUDE_DIR`, and  `Python_EXECUTABLE`.

Closing since in the wrong place (though thank you very much!)

**Comment by henryiii** [comment]
Manylinux does not ship with python embedding libraries. You should not be using manylinux to make a program that embeds Python. What you probably want is to replace "Development" with "Development.Module" ("Development.Embed" is the component not supported in manylinux).

**Comment by DaAwesomeP** [comment]
Thank you very much! That was my issue for the Linux builds.

Now that I've added in macOS x86_64/arm64, the Python location variables workaround seems to fail (it can't find `Interpreter Development.Module`, same as the original issue on manylinux). Does Mac CMake look for Python differently? Should I disable the workaround on MacOS?

**Comment by henryiii** [comment]
That's weird; no it should be the same.  One thing I immediately see; your minimum required CMake version should never be set less than 2.8.12 (or 3.4, IMO), and you should have a range there because a lot of things were fixed in the last 20+ versions of CMake. I'd put at least `cmake_minimum_required(2.8.12...3.20). For the Python part, you probably require 3.15+ or 3.18+ due to FindPython. Feel free to look at https://github.com/pybind/scikit_build_example .

**Comment by henryiii** [comment]
You should do the Python stuff before pybind11 is loaded, as it will use the pre-loaded FindPython if it has already been called.
