### ISSUE TITLE
Windows does not show test output with CIBW_BUILD_VERBOSITY: 1

### ISSUE THREAD

**Issue by DaAwesomeP** [pypa/cibuildwheel#733]
Hello,

I have set `CIBW_BUILD_VERBOSITY: 1`. I am using the GitHub Action. On Linux and macOS builds I can see the standard output of my tests. On both `win32` and `win_amd64` it shows this:
```
...
  + pip install C:\Users\RUNNER~1\AppData\Local\Temp\cibuildwheel9i6u9s_7\repaired_wheel\slam3d-1.0.0-cp39-cp39-win_amd64.whl
  Processing c:\users\runner~1\appdata\local\temp\cibuildwheel9i6u9s_7\repaired_wheel\slam3d-1.0.0-cp39-cp39-win_amd64.whl
  Collecting numpy<2,>=1
    Using cached numpy-1.21.0-cp39-cp39-win_amd64.whl (14.0 MB)
  Installing collected packages: numpy, slam3d
  Successfully installed numpy-1.21.0 slam3d-1.0.0
  + cd D:\a\slam3d\slam3d
  python ./test/test.py ./test/out/test1_ParticleFilterLoc_test_out_c.csv
  
                                                             ✓ 12.97s

✓ cp39-win_amd64 finished in 66.26s
```
It also is claiming that that test is passing...which I am a bit skeptical of. Possibly my test does not pass/fail on Windows properly. My test passes by running `exit(0)` and fails with `exit(1)`. Though when I install from sdist and run directly in the GitHub Actions `windows-2019` container, this seems to work fine.

Also a side question: is it possible to extract/upload test artifacts? Where would they be stored after the cibuildwheel action finishes?

**Comment by joerick** [comment]
Hey @DaAwesomeP ! Could you post a link to the CI config you're using?

**Comment by DaAwesomeP** [comment]
My bad, I totally missed that! 

https://github.com/DaAwesomeP/slam3d/runs/2916193951?check_suite_focus=true#step:4:5142

https://github.com/DaAwesomeP/slam3d/actions/runs/972134624/workflow

**Comment by henryiii** [comment]
I think you should chain your commands with `&&`. You will not catch errors properly if you just use `\n` as a separator. You can use CIBW 2.0.0a3+'s config mode and make this a list of commands if you want. We've added a multiline example to the docs, too, in 2.0 - checkout the "latest" branch of the docs.

**Comment by henryiii** [comment]
See https://cibuildwheel.readthedocs.io/en/latest/options/#examples_6 - this works on all OS's.

**Comment by henryiii** [comment]
@joerick We probably should add multiline examples to the rest of the "COMMAND" variables. I think you mentioned that at one point.

**Comment by DaAwesomeP** [comment]
OK, I switched to `>` and `&&`, and that showed that I was never even getting to the tests (I think because my bash if/else statements aren't working, I'll try `bash -c ''`. I'll close this since that is probably the issue.

**Comment by DaAwesomeP** [comment]
It'd be nice if there was a way to choose the shell like GitHub Actions allows you to with the `run:` command (i.e. `shell: bash`). Batch scripting has different escape rules and etc., so the following command doesn't work despite trying to make it run in bash:
```
 > bash -c ' cd . && (if [[ "windows-2019" = *"windows"* ]]; then export SHARED_EXT=".exe"; else export SHARED_EXT=""; fi) && mkdir build && gcc -o build/test-windows-2019$SHARED_EXT -Iparticlefilter/include particlefilter/src/*.c test/test.c -lm && ./build/test-windows-2019$SHARED_EXT --nofail '
  
  "windows-2019" was unexpected at this time.
```

**Comment by DaAwesomeP** [comment]
Ah, I needed to use double quotes instead of single quotes. Though a shell argument would still be a nice addition. :)

**Comment by DaAwesomeP** [comment]
I seem to be very unlucky with getting Windows builds to work. 

I cannot get the Python working directory to be correct.
```
 + cd D:\a\slam3d\slam3d && python ./test/test.py ./test/out/test1_ParticleFilterLoc_test_out_c.csv
  
  C:\cibw\python\python.3.9.4\tools\python.exe: can't open file 'c:\test\test.py': [Errno 2] No such file or directory
```

```
 + cd D:\a\slam3d\slam3d && python test/test.py test/out/test1_ParticleFilterLoc_test_out_c.csv
  
  C:\cibw\python\python.3.9.4\tools\python.exe: can't open file 'c:\test\test.py': [Errno 2] No such file or directory
```


```
 + cd D:\a\slam3d\slam3d && bash -c " python test/test.py test/out/test1_ParticleFilterLoc_test_out_c.csv "
  
  C:\cibw\python\python.3.9.4\tools\python.exe: can't open file 'c:\test\test.py': [Errno 2] No such file or directory
```

**Comment by henryiii** [comment]
We intentionally run in a different directory, to ensure Python does not load your package (if you don't use `src` structure). I think you want `{package}/test/test.py {package}/test/out/test1_ParticleFilterLoc_test_out_c.csv ` see https://cibuildwheel.readthedocs.io/en/stable/options/#test-command

**Comment by DaAwesomeP** [comment]
I see. It's a bit strange since this does not affect Linux and macOS tests. It also breaks tests that load non-Python files relative to the working directory. I solved my case by adding an argument to serve as a baseline directory.

The docs could be a bit more clearer by saying "Python will always run with a different working directory no matter the shell's working directory." The way I originally interpreted it was more like "this shell/step is run in a different working directory," so as you saw I tried using `cd`.

**Comment by henryiii** [comment]
>  It also breaks tests that load non-Python files relative to the working directory.

You should not load non-Python files relative to the working directory. You should always construct absolute paths in tests, or control the working directory if the path is required, or use importlib-metadata. You should not be assuming your test file (or any Python file) is being run from a specific directory.

If that's `cd {package} && ...`, though, I'm not sure why that wouldn't work. AFAICT from a quick search, it's supposed on Windows.

**Comment by DaAwesomeP** [comment]
> If that's cd {package} && ..., though, I'm not sure why that wouldn't work. AFAICT from a quick search, it's supposed on Windows.

Yeah I tried both `cd {package}` and `cd {project}`, same issue for both.
