### ISSUE TITLE
Cross compiling Apple Silicon wheel fails

### ISSUE THREAD

**Issue by wjakob** [pypa/cibuildwheel#744]
Dear all,

I'm trying to use cibuildwheel (1.12.0) to compile MacOS x86_64 and arm64 wheels on GitHub Actions.

When specifying `CIBW_ARCHS_MACOS: x86_64 arm64`, I run into a somewhat bizarre error message that causes the build to fail. It seems to me as if the arm64 build created a wheel with the same filename as the previously built x86_64 one. Here is the relevant excerpt:

```
Building cp39-macosx_x86_64 wheel
CPython 3.9 macOS x86_64
(..)
✓ cp39-macosx_x86_64 finished in 242.92s

Building cp39-macosx_arm64 wheel
CPython 3.9 macOS arm64 - Apple Silicon
(...)
shutil.Error: Destination path 'wheelhouse/nanogui-0.1.2-cp39-cp39-macosx_10_9_x86_64.whl' already exists
```

Here is a link to the GHA configuration: [[link]](https://github.com/mitsuba-renderer/nanogui/blob/3e59cec14ca8a3176f04aff8da86ccc400a3cd4d/.github/workflows/build.yml).

Here is a link to the failing GHA run: [[link]](https://github.com/mitsuba-renderer/nanogui/runs/2961569150?check_suite_focus=true).

Any ideas would be greatly appreciated!

**Comment by henryiii** [comment]
Hi Wenzel,

scikit-build doesn't natively support Apple Silicon yet. That's high on our priority list - @YannickJadoul did some great work in https://github.com/scikit-build/scikit-build/pull/530 to make this work, but it's not in a released version yet. I'm hoping to make one more PR that makes scikit-build pick up the standard ARCHFLAGS variable, which would make this work natively without the extra tricks mentioned in https://github.com/pypa/cibuildwheel/issues/582.

Our original focus was to get `cmake` updated and out for Apple Silicon (done), and `ninja` (held up waiting for a port from KitWare). Next we'll try to get a Scikit-build update out.

If you want to try things out today, you can use the git version of Scikit-build plus the extra variable define mentioned in the issue linked above.

**Comment by wjakob** [comment]
Thank you Henry and Yannick. I'll wait for this to be officially supported then, sounds like it has almost landed.

**Comment by zoj613** [comment]
I just ran into this exact issue. Im guessing the temporary solution is to build only one of `x86_64` and `arm64`?

**Comment by henryiii** [comment]
No, it's only building the native arch (x86_64) no matter what you do, IIRC. You can use master scikit-build and manually specify CMAKE_OSX_ARCHITECTURES to do either one.

I'll probably try to make a Scikit-build release fairly soonish-sortof. I'd like to at least get MSVC 2019 support (but there is a workaround for that one) and the ability to directly pick up ARCHFLAGS in. We will need to get the CI going again on Scikit-build; it's using a tool called scikit-ci that has broken and I'd rather not have to maintain (I think @mayeut is in agreement), it's better to use standard things like nox. I'm getting a new cmake release out now, and I'll be very busy for PyHEP and SciPy over the next two weeks.

**Comment by henryiii** [comment]
FYI, master Scikit-build supports this natively now. If you can try it out, let me know if it's working :)

PS: in your pyproject.toml, you'd put:

```txt
"scikit-build @ git+https://github.com/scikit-build/scikit-build.git@master",
```

such as in https://github.com/henryiii/scikit_build_example/pull/3/files . I'd not release something with that in it, but it's a good test to make sure this is working before a release.

**Comment by zoj613** [comment]
@henryiii why wouldn't you release it? Does this approach include unwanted stuff in the wheel distribution?

**Comment by wjakob** [comment]
I tried enabling separate-architecture M1 builds on my project (https://github.com/wjakob/enoki/runs/3048249946?check_suite_focus=true). It fails in a really strange way. Any ideas? I wonder if there is any way to get a bit more detail out from CMake..

**Comment by henryiii** [comment]
I think this is the key problem:

```
    CMake Error at CMakeLists.txt:102 (message):
      When Clang is used to compile Enoki, libc++ must be available -- GCC's
      libstdc++ is not supported! (please install the libc++ development
      headers, provided e.g.  by the packages 'libc++-dev' and 'libc++abi-dev' on
      Debian/Ubuntu).
```

Guessing "Enoki" doesn't like the cross-compiling to ARM?

> why wouldn't you release it?

Because I want to fix MSVC 2019 support before releasing, along with hopefully getting some testing of the AS support? It's only been in master very recently. If there was a known problem, it wouldn't be master.

**Comment by henryiii** [comment]
Ah, that's your library. Here https://github.com/wjakob/enoki/blob/e1cc0fc51c37f5a229c42f7103ea285473c274d4/CMakeLists.txt#L87-L104 you are checking for this flag. I would not do this if `MACOSX_DEPLOYMENT_TARGET` is set. If `MACOSX_DEPLOYMENT_TARGET` is set to 10.9 or higher, Clang will always use `libc++` and does not need a flag. For Arm, it will be 11+.

**Comment by wjakob** [comment]
Amazing, that was it indeed! Thanks so much @henryiii, I can build M1 arm64-only wheels now. So cool!

**Comment by wjakob** [comment]
(Feel free to close this issue)

**Comment by henryiii** [comment]
Awesome :) Hopefully we can get a Scikit-build release out in the near future - Currently the biggest remaining blocker to me is the lack of MSVC 2019 support (CC @jcfr and @thewtex) - hopefully one of us will work it out soon(ish).

**Comment by zoj613** [comment]
@henryiii What is lacking in the support of MSVC-2019? If I remember correctly, I had no issues building wheels on `windows-2019` recently.

**Comment by henryiii** [comment]
It won't automatically pick it up like it will with 2017 or 2015. You have to manually set it up by setting the required variables, say with `ilammy/msvc-dev-cmd` on GHA, for example. It _should_ just work out the box, like setuptools, etc. And it does with an older image like `windows-2016` on GHA. (likewise for other systems or people's local machines).

**Comment by henryiii** [comment]
It's mostly due to the fact that it has a list of generators, and it doesn't include "2019" - but adding it is not quite trivial, because CMake dropped the old, silly method of adding the arch to the generator name, and now just expects users to be sensible and add `-A <arch>`. But adapting to that is the holdup.

**Comment by zoj613** [comment]
Well, is there something wrong with this setup? https://github.com/zoj613/polyagamma/blob/main/.github/workflows/release.yml

Thee github actions log says the windows wheels built successfully for `arm64`: https://github.com/zoj613/polyagamma/runs/2972155244?check_suite_focus=true

**Comment by henryiii** [comment]
There's nothing wrong with that, but I'm willing to bet (albeit not very much) that if you enabled verbose builds you would find you are using MSVC 2017 - GHA has 2015, 2017, and 2019 installed on the 2019 image (probably because they are owned by MS 😆 ). Scikit-build can't automatically find 2019, but it's happy with the 2017 that it finds.

**Comment by henryiii** [comment]
Scikit-build 0.12 is out, with Apple Silicon cross compiling and MSVC 2019 support!
