### ISSUE TITLE
Xcode 9.4.1 image deprecated by CircleCI

### ISSUE THREAD

**Issue by nsoranzo** [pypa/cibuildwheel#745]
It will be removed on September 14, 2021. The new minimum will be `10.3.0` .

See https://discuss.circleci.com/t/xcode-deprecation-notice-9-4-1-10-0-0-10-1-0-and-10-2-1/40515

**Comment by henryiii** [comment]
We do use an old image https://github.com/pypa/cibuildwheel/blob/b552fbd016bf1394c6b7de96d5bf98dde5b17730/.circleci/config.yml#L6 - @joerick or @mayeut do you know why? Never updated, or we like to use the minimum, or is there a reason? We should be fine with the newest Xcode usually.

**Comment by joerick** [comment]
> do you know why?

My experience with Xcode has historically been (I'm not sure that this is still the case) that if you're aiming for compatibility with older macOS versions, your best bet is to use the closest SDK you can get your hands on. I know that MACOSX_DEPLOYMENT_TARGET is _supposed_ to deal with this, but my experience has been that binaries built with old SDKs work with newer OSs, but sometimes building for an older OS with a new SDK causes issues.

**Comment by henryiii** [comment]
@joerick We build with the latest images on GHA and that's worked well for many packages. Apple has been very good in allowing newer templated features to still work, and to error if you try to use something that depends on the libs (like using `std::filesystem` will error if you try to target anything less than 10.15).

This is one benefit of having a controlled system - such a system likely wouldn't work as well if attempted for linux (and might be why it is not attempted).

**Comment by joerick** [comment]
Hmm. Yes maybe they have gotten better at this over the past few years. Admittedly my experience is a few years old.
