### ISSUE TITLE
Building extension with fortran

### ISSUE THREAD

**Issue by AntoineD** [pypa/cibuildwheel#763]
Hello,

in order to build an extension with fortran code, would it be possible to install a fortran compiler?
May be with `CIBW_BEFORE_BUILD_MACOS`, `CIBW_BEFORE_BUILD_WINDOWS` and `CIBW_BEFORE_BUILD_LINUX`?

**Comment by joerick** [comment]
Should be possible, yes. To install stuff on the system before build, you probably want [`CIBW_BEFORE_ALL`](https://cibuildwheel.readthedocs.io/en/stable/options/#before-all).

**Comment by AntoineD** [comment]
@joerick Do you know where I can find information about how to install stuff for each platform?

**Comment by joerick** [comment]
I do not know about Fortran compilers, sorry. But I do note that [scikit-build](https://scikit-build.readthedocs.io/en/latest/) has Fortran support, that might be worth a look!
