### ISSUE TITLE
Re-using build folder for consecutive py versions

### ISSUE THREAD

**Issue by nilsnolde** [pypa/cibuildwheel#774]
I'm just starting out with this package and love it! I've been building wheels with some C++ extensions and before I used plain `python setup.py bdist_wheel`. The way it worked for me was that the build folder was re-used since the C++ extensions don't have to be built again fully, only their Python bindings. That allowed for pretty quick multi-py-version builds if the heavy lifting has to be done only once.

I have zero clue about this codebase and not sure if that's clashing with its design or some use cases I don't know about. Would smth like that even make sense? 

FYI, I do a CMake-based build: https://github.com/gis-ops/valhalla-python/blob/gisops_python_branch/setup.py#L117

**Comment by nilsnolde** [comment]
Oh and if it didn't come out: I'd totally be up for adding (optional) support for this, if there's a chance of decreasing build time by > 50%:)

**Comment by joerick** [comment]
Hey @nilsnolde ! There might be a way to make this work, yeah. I _think_ that pip now supports something called 'in-place-builds', we have an experimental branch using trying out at #742. 

That might resolve your issue. Actually, now that I think of it, you could try this in cibuildwheel stable by adding `PIP_USE_FEATURE=in-tree-builds` to your CIBW_ENVIRONMENT. Let me know if that helps...

**Comment by nilsnolde** [comment]
Great thanks for the helpful reply @joerick ! Will definitely try it out soonish and let you know if that did the trick!

**Comment by nilsnolde** [comment]
Finally found the time to try this.

I tried your suggestion with `PIP_USE_FEATURE=in-tree-build` @joerick and it works if pip is upgraded before building (currently 21.2.x) and told to use the new feature e.g. `CIBW_BEFORE_BUILD="python -m pip install --upgrade pip && pip config set global.use-feature in-tree-build"`. While that doesn't set up the build in a temp folder it also doesn't build in a common location, still python version specific: `/project/build/temp.linux-x86_64-3.7`.

I can't 100% remember why I thought this was smth I could solve with `cibuildwheel`.. Right now I figure I have to painstakingly fiddle with the setup.py, so it can tell `wheel` how to orchestrate the build in a fixed folder, argh..
