### ISSUE TITLE
cp310 wheels are built even when CIBW_PRERELEASE_PYTHONS is False

### ISSUE THREAD

**Issue by dralley** [pypa/cibuildwheel#790]
I'm setting up a CI pipeline for HPy which will automatically build and upload the wheels on new releases - however, it seems to be building wheels for Python 3.10 despite being configured to not build wheels for pre-release Pythons. 

https://github.com/dralley/hpy/runs/3287184797?check_suite_focus=true#step:4:1340
https://github.com/dralley/hpy/pull/1/files#diff-b66cdf1c2ec3851a39891c3db9e84217fb9918b12c6d83bd387b4c0a1cea2faeR50-R56

**Comment by dralley** [comment]
3.10 is in release candidate phase, but the release isn't scheduled for another 2 months.  https://www.python.org/dev/peps/pep-0619/#schedule

**Comment by Czaki** [comment]
3.10 has stable ABI now so there is no reason to keep it in prerelease. This is an intentional change. See #786

**Comment by joerick** [comment]
@Czaki  is right, this is an intentional change. The [release notes] for 3.10.0rc1 say:

> There will be no ABI changes from this point forward in the 3.10 series and the goal is that there will be as few code changes as possible.
> 
> Call to action
> We strongly encourage maintainers of third-party Python projects to prepare their projects for 3.10 compatibility during this phase. As always, report any issues to the Python bug tracker.

[release notes]: https://www.python.org/downloads/release/python-3100rc1/

Therefore we now build 3.10 wheels by default, so that packagers can start uploading their packages to PyPI ahead of the official 3.10 release.

**Comment by joerick** [comment]
However, I can see that the name of this option is very confusing now that we're building a prerelease version! My apologies. We should probably reconsider that name. I think the aim of the name was to include alpha and beta releases of Python, but we now know that we should exclude release candidates - which most people would rightly consider 'pre-release'. Suggestions welcome!

Just riffing here, but...

> CIBW_BETA_PYTHONS, CIBW_ABI_UNSTABLE_PYTHONS, CIBW_TESTING_PYTHONS, CIBW_PREVIEW_PYTHONS

**Comment by henryiii** [comment]
FYI, I don't think alpha candidates have ever released to manylinux, so this is probably always going to be beta pythons. CIBW_BETA_PYTHONS, CIBW_ABI_UNSTABLE_PYTHONS, and CIBW_PREVIEW_PYTHONS are fine. Or CIBW_ALLOW_BETA_PYTHONS.

**Comment by joerick** [comment]
CIBW_ALLOW_BETA_PYTHONS makes sense to me.  It will also make more sense as a command line argument `--allow-beta-pythons`.
