### ISSUE TITLE
using build tags

### ISSUE THREAD

**Issue by davidism** [pypa/cibuildwheel#791]
I'd like to release a Python 3.10 RC1 wheel for MarkupSafe 2.0.1, which is already on PyPI. Since I haven't built a 3.10 wheel before, I'll be able to push it to the existing PyPI release. However, when 3.10 final comes out, I'll want to rebuild the wheel, but I'll need to build with something like `bdist_wheel --build-number 01` to allow pushing another 3.10 wheel to the same PyPI release. Is it possible to tell cibuildwheel to use a build tag? Or maybe this is just a filename convention, something I can change after downloading the builds?

**Comment by davidism** [comment]
It looks like besides the file name, `--build-number 01` does add a `Build: 01` field to the `dist-info/WHEEL` file inside the wheel, but otherwise I *think* the wheel looks the same.

**Comment by davidism** [comment]
And the `dist-info/RECORD` file would need an updated hash for `dist-info/WHEEL`.

**Comment by davidism** [comment]
I can probably do this with a script that uses `wheel unpack`, modifies the `WHEEL` `Build` field,  and then `wheel pack` to regenerate the wheel file with the correct `RECORD`.

**Comment by davidism** [comment]
I didn't know it wouldn't need to be rebuilt for that. I was also thinking that CI wouldn't really have the right information for tags, so this seems like something I should do locally with `wheel`. I'll close this, but maybe a mention of "use `wheel` to add a build number if you needed to rebuild a wheel` would be useful in the docs?

**Comment by EwoutH** [comment]
Hi everyone! I found this issue via @hugovk, who has been doing some serious work on getting Python 3.13 supported in the ecosystem. He proposed in a [blog](https://dev.to/hugovk/help-test-python-313-14j1):

> ABI breaks during the beta are infrequent and unintentional. If they happen, you can rebuild your wheels and upload them to an existing PyPI release by adding an optional [build tag](https://packaging.python.org/en/latest/specifications/binary-distribution-format/#file-format) to the filename:

When using cibuildwheel, that method would require being able to use build tags.

This is part of a larger discussing we're having on discuss.python.org, which I would like to reference: https://discuss.python.org/t/idea-tracking-abi-additions-and-changes-for-better-pre-release-wheel-management/26033/12
