### ISSUE TITLE
Fail build automatically if a dependency needs to be built

### ISSUE THREAD

**Issue by Korijn** [pypa/cibuildwheel#796]
E.g. if my build depends on numpy, I want the build to fail if there is no numpy wheel available for the build target, instead of it attempting to build numpy. How can I configure this?

**Comment by joerick** [comment]
```yaml
CIBW_BEFORE_BUILD: pip install --only-binary :all: numpy
```
should do the trick.

**Comment by henryiii** [comment]
I think you could set the environment variable `"PIP_ONLY_BINARY=numpy"` using `CIBW_ENVIRONMENT` as well., and avoid a double install (of a wheel, so not much).

**Comment by henryiii** [comment]
Ahh, yes, here's where I do that: https://github.com/scikit-hep/boost-histogram/blob/481fbd39506f7d9eaead6f13d32842af0cb1c892/.github/workflows/wheels.yml#L22

**Comment by Korijn** [comment]
Awesome, thanks!
