### ISSUE TITLE
Excessive long wheel names after update

### ISSUE THREAD

**Issue by ixje** [pypa/cibuildwheel#805]
I moved from cibuildwheel `1.1.0` with Travis-CI to `2.1.1` with Github Actions. The former setup would create a wheel name like `neo3vm-0.8.2-cp38-cp38-manylinux2010_x86_64.whl` while the latter now produces `neo3vm-0.8.2-cp38-cp38-manylinux_2_12_x86_64.manylinux2010_x86_64.whl` (note the additional `manylinux_2_12_x86_64.` after `cp38-`).

It is as if it adds a platform tag twice. Is there a way to control this?

**Comment by henryiii** [comment]
This is from auditwheel 4, which adds the "classic" platform tag (manylinux2010) for compatibility with old pip versions, as well as the "modern" manylinux_2_12 tag (which tells you exactly what the minimum glibc version is, 2.12).

If you wanted to control it, you would have to check auditwheel's docs and change the repair command from the default to whatever is needed. Though I think doing both tags is the "correct" thing to do. I'm also planning on adding a (easier) way to change the tags on an existing wheel to `wheel`.

**Comment by ixje** [comment]
Thanks for the insights. Rolling back the audit wheel version via `dependency-versions`  seems to be the easiest solution for now
