### ISSUE TITLE
Building for macOS arm64 - Apple Silicon fails with FileExistsError for cffi

### ISSUE THREAD

**Issue by viblo** [pypa/cibuildwheel#813]
Im trying to add building of macOS arm64 for a package I maintain, Pymunk. However, the build fails with a FileExistsError on a dependency. Since this error does not happen for users building "normally" on macs I think its something in cibuildwheel (to my knowledge, unfortunately I dont have a M1 to try on myself).

Im trying to build on Github actions, using joerick/cibuildwheel@v2.1.1 with a very basic workflow file:
```
    strategy:
      matrix:
        os: [macos-10.15]
...
      - name: Build wheels
        uses: joerick/cibuildwheel@v2.1.1
        env:
          CIBW_BUILD: "cp39-*"
          CIBW_ARCHS_MACOS: "x86_64 universal2 arm64"
          CIBW_TEST_COMMAND: "python -m pymunk.tests"
          CIBW_BUILD_VERBOSITY: 3
```
Full file here: https://github.com/viblo/pymunk/blob/cd5b5d5c6faa92f9a4b71e86bb257387125a7af9/.github/workflows/wheels.yml

The main part of error log: 
```
      File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/setuptools/wheel.py", line 95, in install_as_egg
        self._install_as_egg(destination_eggdir, zf)
      File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/setuptools/wheel.py", line 103, in _install_as_egg
        self._convert_metadata(zf, destination_eggdir, dist_info, egg_info)
      File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/setuptools/wheel.py", line 124, in _convert_metadata
        os.mkdir(destination_eggdir)
    FileExistsError: [Errno 17] File exists: '/private/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/pip-req-build-cyf6wxz8/.eggs/cffi-1.14.6-py3.9-macosx-11.0-arm64.egg'
    Building wheel for pymunk (setup.py): finished with status 'error'
    ERROR: Failed building wheel for pymunk
```
Full build log is here: https://github.com/viblo/pymunk/runs/3470607783?check_suite_focus=true

The library, Pymunk, has a dependency on cffi. Cffi does not provide wheels for macOS arm64, so I guess it built it first and then something breaks. 

ps. Let me take this opportunity to say that generally I think cibuildwheels works great, it has made it very easy to build wheels. Thanks!

**Comment by nitzmahone** [comment]
CFFI maintainer here- I actually just tripped over this while looking for an existing issue on `cibuildwheel`. Not sure what's going on there, but I suspect it might be a weird corner case in `pip` or `wheel` with cached intermediate builds to a shared tempdir when the same dep appears in setup_requires + install_requires (as you have with cffi). 

CFFI is actually adding wheels for Python 3.10 and MacOS arm64 this week as part of cffi's 1.15.0rc1, and I'm hoping to get some validation on them before we push them live. I'll post a notification at https://groups.google.com/g/python-cffi when they're ready- would be great if you could try a test build against `cffi == 1.15.0rc1` at that point.

**Comment by viblo** [comment]
Nice, will try it out when available 👍

**Comment by viblo** [comment]
I saw the release of the rc, and I tried to update the build pipe to use it. However, it didnt really work out, seems like cibuildwheel uses a different macos version than the cffi wheel does. I tried a couple of different ways to force it, but couldnt manage to make it use the correct one so the prebuilt wheel could be installed.

**Comment by Czaki** [comment]
@viblo Did you try to use macos 11.0 image? In your old workflow file, you use macos  10.15 and cffi to create arm wheels for macos 11.0

**Comment by viblo** [comment]
Yes, I tried with `os: [macos-11]` in the matrix using the latest cibuildwheel, 2.1.2. That should be enough? But will try some more tomorrow, maybe there's some other thing I missed.

**Comment by Czaki** [comment]
I do not have big experience, it may help, but still, it will be an x86 machine? maybe @henryiii  has more experience? 
It may be better if `cffi` will provide an `universal2` wheels.

**Comment by nitzmahone** [comment]
I did most of my initial `cffi` build testing for Apple Silicon with `universal2` wheels, but there are a lot of difficulties with that (which I'll spare you the details of), so I ended up just making 11.0_arm64 wheels in addition to the existing 10.9_x86_64 wheels. Modern pip will still happily auto-install the 10.9 x86_64 wheels on 11.0+ x86_64, so if you're not getting the new wheels when your requirement lists `cffi==1.15.0rc1`, there's probably something else going on. Unless you're trying to build a fully `universal2` environment that's totally agnostic to x86/arm64 (good luck, it's *really* hard), the wheels that are there should work for anything.

**Comment by henryiii** [comment]
You can actually merge the two into a universal2 wheel, by the way. Haven't done it, but it can be done.

Having the separate wheels does create issues when you are cross compiling, you'll get the x86 wheels when you are trying to build arm64 code. The end user will get the right wheel (if it's a dep), but you'll get the wrong one when building. Not sure if there's a way to fix that.

**Comment by nitzmahone** [comment]
Yeah, I did a bunch of that- I got really good at building fat binaries for libyaml and libffi- the really hard part is getting a clean Python extension build that behaves properly. I was able to get things that "worked", but didn't fit well into the existing wheel build toolchains. It's a little easier with `multibuild` than `cibuildwheel` just by its nature of script hooks, but it still resulted in a lot more "artisinal wheel building code" than I'd prefer to maintain. :laughing:

**Comment by nitzmahone** [comment]
> Having the separate wheels does create issues when you are cross compiling

Thinking about this a bit more- if cross-compile support assumes that all required deps are `universal2`, that seems like a bug. I ran into all sorts of nasty corner cases with real-world cross-compile support anyway that were generating unusable wheels, but most were related to the distutils/setuptools extension build behavior around inheriting the build Python's compile flags. Sometimes I was able to munge it enough to get things to behave properly, but just as often I wasn't and had to drop back to manually building extensions, which I wasn't comfortable shipping or maintaining.

**Comment by joerick** [comment]
I'd like to understand this better, I think. Apologies for asking the stupid questions! Why is cffi required as a compile-time dependency here? I thought that FFI was a run-time linking tool. Is it doing some kind of codegen too?

I'm trying to understand why the cross-compile step (running on x86_64, targeting arm64) requires the arm64 wheel to do the build.

**Comment by nitzmahone** [comment]
Ditto.

**Comment by viblo** [comment]
So, I managed to build it when just building the arm64 wheels. If I try to build for x86_64 or universal2 at the same time as arm64 it fails. Testing some more it turns out that building for x86_64 fails with os set to `macos-11`, while it works on `macos-10.15`.

Looking closer, I now see that cffi 1.15.0rc1 only provided arm64 wheels for macos-11, but the x86_64 wheels only for the 10, so it make sense that the build fails the same as when I opened this issue.

**Comment by henryiii** [comment]
x86_64 10.x wheels should work on 11 - as long as you have an up-to-date pip, that is. Reasonably recent versions of cibuildwheel should be fine, etc.

**Comment by viblo** [comment]
I should add that I just tried the very newly released `cffi-1.15.0rc2` as well, with no changes.

**Comment by nitzmahone** [comment]
Also, just for grins, I forked your project to my org where I have self-hosted M1 GHA runners and reproduced it on M1 hardware as well (https://github.com/rolpdog/pymunk/runs/3832288919) . It looks like the original issue is a setuptools/wheel problem (the same one I hit that led me to this issue when googling the traceback when I hit it elsewhere). But that said, even if this bug were fixed or worked around, since your project is using CFFI's extension builder, you'd likely need to do a lot of manual intervention to get a functional `universal2` wheel, since cffi itself has no concept of fat binaries or multi-arch builds (and probably never will). The way it works for really simple things where all the input source is multi-arch capable and the libs to link are fat binaries, it just passes two arches to clang and poops out a fat binary. But for anything where that's not the case (which likely includes your cffi extension), you'll have to manually build the two arch extensions separately, `lipo` them together, then do some surgery on the wheel build (or manually do a `bdist_wheel` on a hacked intermediate build dir) to get something that's properly tagged and usable. Or you could just ship separate x86_64 and arm64 wheels, as I've chosen to do, because very little of the tooling is capable of doing "easy" `universal2` wheels for things of any complexity.

**Comment by nitzmahone** [comment]
Long and short @joerick @henryiii - at the end of the day, I don't think this is a `cibuildwheel` bug- it's a combination of a setuptools bug (which changing to a PEP517 build can neatly avoid) and limitations of universal2 wheel builds of any complexity.

**Comment by viblo** [comment]
Great find with pep 517! I updated and tried myself and it seems to work fine.

Regarding universal2, I just followed the documentation. If they wont work no big deal for now, but great if the documentation could give some hint about the issue.

Just a final question @nitzmahone on your comment about cross compiling: Do you mean that cross compiling will work with arm64 as the target, or not at all? I tried updating the pipeline with pyproject.toml, and made a run here: https://github.com/viblo/pymunk/actions/runs/1323411442 Checking the output wheels it seems like the arm64 is the same as the one you built, but want to make sure since I cant test anything on arm64 myself.

Btw, big thanks for all the help here 👍

**Comment by nitzmahone** [comment]
I know at runtime there are some places where it (or libffi on its behalf) does arch-specific assembly trampoline generation that would most certainly not work, but I've not looked at the intermediate codegen for the extension builder to see if any of that ends up in the generated code or not. Ignorance is bliss, walking away from this one now, lalala :laughing:

**Comment by henryiii** [comment]
I just tested clang-format on M1, and it worked fine - that's the whole LLVM build cross-compiled. If you know it works, I think it's fine to produce wheels. I ran your wheel on AS, Python 3.10, and it loaded fine and the simple example in the readme worked correctly.

**Comment by viblo** [comment]
Since the conclusion was that this is most likely not a problem within cibuildwheel itself but in setuptools, and there is a workaround (use pyproject.toml), I will close this issue. Thanks for the help :)
