### ISSUE TITLE
unintentional pure wheel created for ctypes wrapper, general usage question.

### ISSUE THREAD

**Issue by AndrewAnnex** [pypa/cibuildwheel#837]
I author/maintain a package https://github.com/AndrewAnnex/SpiceyPy that wraps a C shared library using ctypes that I am trying to adapt to use cibuildwheels in https://github.com/AndrewAnnex/SpiceyPy/pull/421. I've supported building wheels for windows using a custom github workflow adapted from appveyor for a while now https://github.com/AndrewAnnex/SpiceyPy/blob/main/.github/workflows/publish-to-test-and-live-pypi.yml, but I want to upgrade things to cibuildwheel to support more platforms in a unified manner with cibuildwheels. 

Based on the documentation I have seen, my library does not fit neatly into the paradigm of cibuildwheel and my ci builds currently fail because a pure python library is being produced erroneously, so I could use some advice to work through this.  In the current builds it looks like cibuildwheel is not applying the `--plat-name` parameter for bdist_wheel, and I am not sure if there is a way to force it to/override it. I could also do some trickery https://stackoverflow.com/questions/35112511/pip-setup-py-bdist-wheel-no-longer-builds-forced-non-pure-wheels, but I would hope that cibuildwheel has the ability to do this. ~~I am about to try switching the build frontend option to see if that works as it does for windows.~~ <I misread what this actually does 

For some background, I build the shared library during install time within my setup.py with a custom script that downloads the static library distribution and runs various shell commands to build a shared library on linux/macos/windows. 

This also means that my source code is not actually dependent on the python version, as I write it to be compatible with 3.6+, so I really only need 1  build for each architecture (windows, macos, macos arm, etc), which maybe related to #569. So in the end the macos shared library for example could be used for any of the python versions on macos.

any tips would be appreciated, apologies if this is the wrong venue for general usage questions

**Comment by henryiii** [comment]
I'd look at https://github.com/scikit-build/cmake-python-distributions and https://github.com/scikit-build/ninja-python-distributions where this is done using a post-build script. I'm going to work on https://github.com/pypa/wheel/issues/407 soon, which should help make this easier (actually would have started if it wasn't for musllinux causing #799 to be bumped up in priority).

However, for your case, maybe look at https://github.com/dokempf/clang-format-wheel - this has a very simple workaround in https://github.com/dokempf/clang-format-wheel/blob/d1704c7bc4697e577201d41ea122a9f80344c668/setup.py#L7-L15.

In all cases, you should select just one version of python to build. Eventually we might have a way to run the other Python versiontests on a single Python version.

**Comment by AndrewAnnex** [comment]
@henryiii thanks for the suggestions, I think the clang example could work for my needs but I am unsure if [PEP425](https://www.python.org/dev/peps/pep-0425/#python-tag) would work for the minimum python 3.6 version I had in mind. Looking at the pep it looks like `py3` would specify any python 3 version, but that `py36` would say only python 3.6 is compatible. I think I would need a python tag like `py36.py37.py38.py39` to prevent 3.5 users from installing the package, but again maybe I am just not reading the pep carefully but I am not sure if that is supported. Alternatively, I could more closely follow that example by making a new package that just provides the compiled shared library and then refactor my main project to depend on it... arguably a more correct approach but I would hope it's not necessary.

**Comment by henryiii** [comment]
You should use the Requires.Python metadata slot (`python_requires=` in setup.py/cfg) to control this, not the Python version tag. The wheel should have no Python tags associated with it if it is not compiled against a single version of CPython. A pure Python wheel also does not use `py36.py37.py38.py39`, but just uses the above mentioned metadata slot.

**Comment by henryiii** [comment]
Also, "Python 3" means "3.6+" more or less nowadays, since 3.0 - 3.5 are end-of-life. So a human reading the wheels (pip will use Requires.Python) will assume py3 means Python 3.6+. No one expects anything to work on Python 3.0, 3.1, etc...

**Comment by AndrewAnnex** [comment]
ahh. yes I do have python_requires set in both my setup.py and the pyproject.toml I am adding in that PR. I also just spotted https://github.com/pypa/wheel/issues/336 that seems relevant to this. Pep 425 seems to imply that the abi tag specifies if the wheel is pure python (if it's set to `none`).  I am going to try overriding `get_tag` to return `"py3", "abi3"` and the default platform to see if that works.

**Comment by AndrewAnnex** [comment]
but then again, setting the abi shouldn't matter, but if I don't am I back to the issue of having a pure python wheel or does overriding the attribute in`finalize_options` fix that?

**Comment by henryiii** [comment]
You are not making a limited API / stable ABI wheel. You are making a wheel that does not depend on CPython at all, so `none` is correct for the implementation. It would / should support PyPy as well, or any other implementation of the Python language, because it does not depend on the implementation.

Your names should in the end look just like `cmake`, `ninja`, `clang-format`, or any other package that does not touch the CPython interpreter.

**Comment by AndrewAnnex** [comment]
oh yeah forgot to close this issue, I worked out the issue is really in setuptools
