### ISSUE TITLE
Codesign issue on macOS ARM from TravisCI

### ISSUE THREAD

**Issue by henryiii** [pypa/cibuildwheel#871]
When building a ARM wheel, it seems the code signature might be broken when cross-compiling (but not normal compiling, AFAICT). This happened on a TravisCI macOS build from bitbucket, which might be the problem?

See https://bitbucket.org/mrabarnett/mrab-regex/issues/399/missing-wheel-for-macosx-and-the-new-m1

**Comment by joerick** [comment]
Can this be closed @henryiii ?
