### ISSUE TITLE
Parallel build_ext support?

### ISSUE THREAD

**Issue by illume** [pypa/cibuildwheel#879]
### Description

Building a build_ext extension with C/C++/Cython/etc is slow because cibuildwheel doesn't use this distutils feature for allowing parallel builds.

Is there a way to pass pip options for this with cibuildwheel? (I looked and couldn't find any)

With python 3.5+ versions `--parallel or -j4` can be used. pip allows something like `pip install --global-option=build_ext --global-option="-j4" -vvv . --isolated --no-deps`.

As far as I know, there's no environment variable for this.
- https://github.com/python/cpython/blob/bb3e0c240bc60fe08d332ff5955d54197f79751c/Lib/distutils/command/build.py
- https://github.com/python/cpython/blob/bb3e0c240bc60fe08d332ff5955d54197f79751c/Lib/distutils/command/build_ext.py

---

If there's no built in cibuildwheels way to do this, then I'm leaning towards using a distutils extension. One that adds the options via an environment variable.

Something like this numpy one which lets you use the `NPY_NUM_BUILD_JOBS` environment variable. (Except one that sets the option, rather than implements the building itself).
```
 try:
     from numpy.distutils.ccompiler import CCompiler_compile
     import distutils.ccompiler
     distutils.ccompiler.CCompiler.compile = CCompiler_compile
 except ImportError:
     print("Numpy not found, parallel compile not available")
```

---

Ultimately I guess pip should be responsible for setting this option via an environment variable.

**Comment by Abacn** [comment]
PIP_GLOBAL_OPTION is now deprecated, and actually, get ignored:

```
  WARNING: Ignoring --global-option when building apache-beam using PEP 517
```

As a result https://github.com/pypa/cibuildwheel/blob/170e7aaeb91807dccbade786f95e8c8e4d2eda31/docs/options.md?plain=1#L834 needs to be updated

**Comment by joerick** [comment]
PR would be great, bonus points for transferring the example to `config-settings`!Sent from my phoneOn 17 Aug 2024, at 00:00, Yi Hu ***@***.***> wrote:﻿
PIP_GLOBAL_OPTION is now deprecated, and actually, get ignored:
  WARNING: Ignoring --global-option when building apache-beam using PEP 517

As a result https://github.com/pypa/cibuildwheel/blob/170e7aaeb91807dccbade786f95e8c8e4d2eda31/docs/options.md?plain=1#L834 needs to be updated
