### ISSUE TITLE
Stalling emulated CI runs.

### ISSUE THREAD

**Issue by joerick** [pypa/cibuildwheel#882]
### Description

I keep seeing the emulated tests stalling on our CI. This is an example of the output:

```
============================= test session starts ==============================
platform linux -- Python 3.9.7, pytest-6.2.5, py-1.10.0, pluggy-1.0.0
rootdir: /home/runner/work/cibuildwheel/cibuildwheel, configfile: pyproject.toml
plugins: forked-1.3.0, xdist-2.4.0, timeout-2.0.1
collected 2 items

Error: The operation was canceled.
```

They are cancelled after the job times out - 3 hours. Restarting normally fixes it.

It seems that our process is not running, as we have pytest-timeout that should cancel a test that's taking too long.

Is this only an issue in our CI? or is it an issue with GHA, or the emulation step?

### Build log

https://github.com/pypa/cibuildwheel/pull/854/checks?check_run_id=3920499554

**Comment by Czaki** [comment]
> I don't think anything that the test process is doing would be installing a signal handler, it's just waiting on a subprocess.run call AFAIK.

I do not know what happens here. When I play with Qt and calculation stuck in C code then SIGINT was ignored. It has handled first-time calculation returns from C to python.

**Comment by henryiii** [comment]
Not that it fixes anything, but https://twitter.com/hugovk/status/1450088663304581120?s=20 -> https://github.com/github/roadmap/issues/271 will be nice. :)

**Comment by joerick** [comment]
This seems to have stopped happening :)
