### ISSUE TITLE
Expose a build tool to the Docker image in Github Actions

### ISSUE THREAD

**Issue by nicholasjng** [pypa/cibuildwheel#896]
### Description

Hello cibuildwheel community,

I am trying to build a Python wheel in CI using Bazel. While `cibuildwheel` manages to locate the Bazel binary inside a `macos-latest` image, it is not able to do so for `ubuntu-latest`. 

I've read up on the documentation, and it seems that the Docker container does not pick up the Bazel binary from the action runner's PATH in the latter case. Now I'm weighing the options of 

1) using the `CIBW_ENVIRONMENT` variable to resolve the path correctly (tried this, does not seem to work),
2) installing Bazel with the before build machinery (this seems complicated too, due to Bazel's install instructions),
3) making a custom Linux docker image with Bazel preinstalled.

I attached the CI run below, and would be happy about some direction. Thank you!

### Build log

https://github.com/nicholasjng/benchmark/actions/runs/1389947096

**Comment by joaospinto** [comment]
I'm hitting this exact issue as well. @nicholasjng do you have a pointer to what you ended up doing (in case it's some open-source code)? At first sight, it doesn't seem like a great idea to have this use its own container. The host system (e.g. GitHub Actions) is already containerized. Packing platform-dependent install scripts of e.g. Bazel, LLVM, etc on `CIBW_BEFORE_ALL` isn't a good solution.
