### ISSUE TITLE
GitHub Actions Permission Error after wheel build on windows-latest

### ISSUE THREAD

**Issue by nicholasjng** [pypa/cibuildwheel#897]
### Description

I am building a Python wheel using Bazel on Windows, and I see a strange permission error after building the wheel, during a call to `shutil.rmtree` by `pip`.

The stacktrace would make it seem that `pip` tries to remove a Java DLL (presumably belonging to Bazel) but is refused by the filesystem. Is there an easy explanation / remedy for this?

### Build log

https://github.com/nicholasjng/benchmark/runs/4025912737

### CI config

https://github.com/nicholasjng/benchmark/blob/wheel-action/.github/workflows/wheels.yml

**Comment by nicholasjng** [comment]
Turns out that this is not a spurious issue, but rather it made my Windows wheel jobs fail consistently. I suspect that it is not `cibuildwheel`'s fault though, since it is `pip` that crashes the build job, and `pip` is just a build frontend choice for `cibuildwheel`.

In the end, I "solved" it by enabling `pip wheel`'s `--no-clean` option with an environment variable on Windows. I'm not sure if that is a great way to handle it, but for the time being, it gets the job done. Thank you for your input on this issue!

**Comment by joerick** [comment]
Thanks for sharing your workaround @nicholasjng !
