### ISSUE TITLE
Avoid recommending deprecated practice of calling setup.py directly

### ISSUE THREAD

**Issue by CAM-Gerlach** [pypa/cibuildwheel#898]
The [Delivering to PyPI](https://cibuildwheel.readthedocs.io/en/stable/deliver-to-pypi/#manual-method) docs and the [GitHub Actions](https://github.com/pypa/cibuildwheel/blob/main/examples/github-deploy.ym) and [Travis](https://github.com/pypa/cibuildwheel/blob/main/examples/travis-ci-test-and-deploy.yml) examples use direct invocations of setup.py, `python setup.py sdist`, and the latter even uses the truly archaic `python setup.py install`.

This will only work for legacy `setuptools`-based projects with a `setup.py`, and direct invocation of `setup.py` has long been discouraged, has been deprecated for some time, as of `setuptools` 58.3.0 formal `DeprecationWarnings` are now issued, and will eventually be removed completely. The canonical replacement for `python setup.py sdist` is `python -m build --sdist` (preceded by `python -m pip install --upgrade build`, in case it is not already installed). and for `python setup.py install`, it is of course `pip install .`.

See [here](https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html) for more info.

**Comment by CAM-Gerlach** [comment]
To clarify, as I neglected to mention it before, but I'd be happy to contribute these improvements in a PR.

Additionally, based on @henryiii suggestions on #766 in the [Scikit-HEP](https://scikit-hep.org/developer/gha_wheels) docs, `pipx run build --sdist` is even simpler as a one-liner (assuming pipx itself is installed) and ensures an isolated, up to date environment is used to build the sdist, and matches the pipx approach suggested to run `cibuildwheelitself` in CIs.

**Comment by CAM-Gerlach** [comment]
Thanks @henryiii for all the great improvements!

**Comment by henryiii** [comment]
Sure, let us know (or make a PR) if you see anything else!
