### ISSUE TITLE
Repairing cp310-(many|musl)linux_x86_64 wheel fails

### ISSUE THREAD

**Issue by animalize** [pypa/cibuildwheel#901]
### Description

If build `cp310-(many|musl)linux_x86_64` wheel like this, it fails.

Building cp36~cp39 `(many|musl)linux_x86_64` wheels are fine.
If remove the `Run test` step, It succeeds.
I guess the build directory is not cleaned up properly.

Building script:
```yaml
env:
  CIBW_BUILD: cp310-*

  job:
    name: Build cp310-musllinux_x86_64 wheel
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2

      - name: Run test
        run: |
          python setup.py install
          python -m unittest -v regex.test_regex

      - name: Install cibuildwheel & build wheels
        run: |
          python -m pip install -U cibuildwheel
          python -m cibuildwheel --output-dir wheelhouse
```
The error message, from [this run](https://github.com/animalize/mrab-regex/runs/4065431753?check_suite_focus=true):
```
Repairing wheel...
  
      + sh -c 'auditwheel repair -w /tmp/cibuildwheel/repaired_wheel /tmp/cibuildwheel/built_wheel/regex-2021.10.23-cp310-cp310-linux_x86_64.whl'
  INFO:auditwheel.main_repair:Repairing regex-2021.10.23-cp310-cp310-linux_x86_64.whl
  Traceback (most recent call last):
    File "/usr/local/bin/auditwheel", line 8, in <module>
      sys.exit(main())
    File "/opt/_internal/pipx/venvs/auditwheel/lib/python3.9/site-packages/auditwheel/main.py", line 59, in main
      rval = args.func(args, p)
    File "/opt/_internal/pipx/venvs/auditwheel/lib/python3.9/site-packages/auditwheel/main_repair.py", line 161, in execute
      out_wheel = repair_wheel(
    File "/opt/_internal/pipx/venvs/auditwheel/lib/python3.9/site-packages/auditwheel/repair.py", line 74, in repair_wheel
      raise ValueError(
  ValueError: Cannot repair wheel, because required library "libc.so.6" could not be located
  Error: Command ['sh', '-c', 'auditwheel repair -w /tmp/cibuildwheel/repaired_wheel /tmp/cibuildwheel/built_wheel/regex-2021.10.23-cp310-cp310-linux_x86_64.whl'] failed with code 1. 
```

**Comment by henryiii** [comment]
Have you tried manylinux2014? Not sure how well 2010 works with python 3.10, most libraries (like NumPy) are doing 2014 wheels for 3.10. You can use a TOML overload to set the image just for `cp31*`.

**Comment by mayeut** [comment]
From what I gathered, it seems like the build directory is not cleaned up properly & reused between builds. I'm not sure why this happens since the build is supposed to be isolated with pip < 21.3 (probably it copies the whole source folder rather than copying only files that would end up in the sdist).
I wonder if switching to `build` fixes this issue ?

**Comment by animalize** [comment]
> Have you tried manylinux2014? Not sure how well 2010 works with python 3.10, most libraries (like NumPy) are doing 2014 wheels for 3.10. You can use a TOML overload to set the image just for `cp31*`.

It create a test workflow, cp310 fails, cp39 succeeds:
https://github.com/animalize/mrab-regex/actions/runs/1487097769

**Comment by joerick** [comment]
Is this still an issue? Feel free to reopen if so.
