### ISSUE TITLE
Feature Request Please support poetry build backend

### ISSUE THREAD

**Issue by rfaircloth-splunk** [pypa/cibuildwheel#916]
### Description

I use poetry primarily please support poetry as a backend

**Comment by joerick** [comment]
You can set build backends using pyproject.toml. See this for poetry: https://python-poetry.org/docs/pyproject/#poetry-and-pep-517 

That said, I don't think that poetry supports platform wheels, so you don't need cibuildwheel. [pypa/build](https://github.com/pypa/build) is probably what you want.

**Comment by henryiii** [comment]
I'm [working on a proposal](https://iscinumpy.gitlab.io/post/scikit-build-proposal/) that would include a poetry plugin to build binaries, but as far as I know, there is no support for binaries poetry - they don't support what we do; we would support them if they chose to do so. We use pip or build to do the building, so any PEP 517 tool (like Poetry) works, just as long as it makes binary (platform) wheels.

**Comment by Anselmoo** [comment]
@henryiii Thank you very much for the detail answer!

Is there any chance to use complete `pyproject.toml` including the `[tool.poetry.dependencies]` and `[tool.poetry]`, so that __cibuildwheel__ can skip _poetry_?

**Comment by henryiii** [comment]
Poetry _is_ the build system. If you skip it, you'd just end up doing nothing at all. Currently there are a limited number of build systems that support building compiled code. setuptools/distutils, scikit-build, pyo3 (Rust), enscons. I've also seen a [pdm](https://pdm.fming.dev) example that shows how to use setuptools to do the extension compile inside pdm (pdm is very much like Poetry, except it supports standards like PEP 621 that poetry does not yet).

Poetry ideally will support compiling via plugins eventually (as I said, I'd probably be writing one for scikit-build if my proposal gets accepted), but it doesn't now.

Also, cibuildwheel will never be a build system, and any new tools should use PEP 621 configuration and not something Poetry specific.

**Comment by Anselmoo** [comment]
> Poetry _is_ the build system. If you skip it, you'd just end up doing nothing at all. Currently there are a limited number of build systems that support building compiled code. setuptools/distutils, scikit-build, pyo3 (Rust), enscons. I've also seen a [pdm](https://pdm.fming.dev) example that shows how to use setuptools to do the extension compile inside pdm (pdm is very much like Poetry, except it supports standards like PEP 621 that poetry does not yet). Meson should gain support soon, too, I think.
> 
> Poetry ideally will support compiling via plugins eventually (as I said, I'd probably be writing one for scikit-build if my proposal gets accepted), but it doesn't now.
> 
> Also, cibuildwheel will never be a build system, and any new tools should use PEP 621 configuration and not something Poetry specific.

Thx, that helps a lot!

**Comment by henryiii** [comment]
You might like https://stackoverflow.com/questions/60073711/how-to-build-c-extensions-via-poetry/60163996#60163996

There's a page on PDM about this too, https://pdm.fming.dev/pyproject/tool-pdm/#build-c-extensions

**Comment by bostonrwalker** [comment]
> I'm [working on a proposal](https://iscinumpy.gitlab.io/post/scikit-build-proposal/) that would include a Poetry plugin to build binaries, but as far as I know, there is no support for binaries in Poetry - they don't support what we do; we would support them if they chose to do so. We use pip or build to do the building, so any PEP 517 tool (like Poetry) works, just as long as it makes binary (platform) wheels.

It is possible to build platform-specific binaries using Poetry, although it is not officially supported yet (see https://github.com/python-poetry/poetry/issues/2740).

**Comment by henryiii** [comment]
That that should work just fine in cibuildwheel - we check for pyproject.toml **or** setup.py already - you don't have to have a setup.py.
