### ISSUE TITLE
Multiple Manylinux Tags

### ISSUE THREAD

**Issue by MuellerSeb** [pypa/cibuildwheel#922]
### Description

Using cibuildwheel 2.2.2 with the standard configuration, we get wheels with the following naming scheme:
```
xxx-cp38-cp38-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_12_x86_64.manylinux2010_x86_64.whl
```
I couldn't find any information about multiple manylinux tags (beside the pep600 naming for `manylinux_2_x`) on the web.
Does this simply mean, that these wheels are `manylinux1` and `manylinux2010` compatible?

Maybe a short notice about that in the docs could help.

Thanks for your help!
Sebastian

**Comment by MuellerSeb** [comment]
I guess this is answered here: https://github.com/pypa/cibuildwheel/pull/633#issuecomment-812880846

**Comment by henryiii** [comment]
Yes, this is a feature of auditwheel 4.

**Comment by henryiii** [comment]
Can this be closed?
