### ISSUE TITLE
Objective-C++ compiler not installed on this system

### ISSUE THREAD

**Issue by RoyJames** [pypa/cibuildwheel#923]
### Description

Hi,

I want to build wheels for my Python-C++ package. My pip CI has passed (see [this](https://github.com/GAMMA-UMD/pygsound/runs/4231199969?check_suite_focus=true)). But the wheel CI fails on compiling a `.mm` file (see L925 in attached log). Is this some issue related to manylinux vs objc++ support? 

### Build log

https://github.com/GAMMA-UMD/pygsound/runs/4231200177?check_suite_focus=true#step:3:925

### CI config

https://github.com/GAMMA-UMD/pygsound/blob/8cffb2a5c552e3d0a3a13378e7c30c0a4e3d3155/.github/workflows/wheels.yml

**Comment by RoyJames** [comment]
I realize that I should install dependencies inside the docker container using
`CIBW_BEFORE_BUILD_LINUX: cmake --version; yum install -y fftw-devel gcc-objc++` and have added that. However, it is still showing error related to objc++ compiler: `c++: error: language objective-c++ not recognized` and the full log is [here](https://github.com/GAMMA-UMD/pygsound/runs/4243636856?check_suite_focus=true#step:3:380). I'd appreciate it if anyone can suggest workarounds. Thanks.

**Comment by henryiii** [comment]
before-all, not before-build. And you are in manylinux, so you are using the RHEL developer toolkit compilers, so you'd have to install whatever they call it, not just plain `gcc-`. Remember you are on CentOS 5 (manylinux1), 6 (manylinux2010), or 7 (manylinux2014), so the built-in GCC is _old_.

**Comment by henryiii** [comment]
Personally, I don't see `devtoolset-9-*objc*`. Looks like Red Had never added Objective C to the dev toolset patched compilers. If you really can compile on GCC 4.4, then you could install that and make sure that was the one used when compiling.

**Comment by henryiii** [comment]
You could also use manylinux_2_24 which does not have patched compilers, just the default Debian GCC 6 ones, which should include an objective C version, I'd guess, but then you can't use it on older pips and older systems like CentOS 7.

**Comment by RoyJames** [comment]
Thanks for the insights! Switching to `manylinux_2_24` does "solve" the problem. I'm going to experiment with other solutions that have better compatibility since now I know the cause.
