### ISSUE TITLE
Prevent clean up on failure (to allow debugging)?

### ISSUE THREAD

**Issue by ixje** [pypa/cibuildwheel#930]
### Description

I use cibuildwheel with github actions using this setup (it's in a private repo so can't link it in the CI Config section)
```
      - name: Build wheels
        uses: pypa/cibuildwheel@v2.2.2
        env:
            CIBW_BEFORE_BUILD_LINUX: "python3 -m pip install cmake"
            CIBW_BUILD: "cp38-macosx_x86_64 cp38-manylinux_x86_64 cp39-macosx_x86_64 cp39-manylinux_x86_64"
```
Somewhere in the "Building wheel..."  step it fails in CMake configuring a project using pybind11. The error printed is insufficient but mentions there is a `.log` file under  `/tmp/..`. The problem is that the moment I log into the runner (1 step after building the wheels) all the buildwheel step files have been cleaned. I presume by this final step (`Running setup.py clean`) in

```
ERROR: Failed to build one or more wheels
  WARNING: You are using pip version 21.2.4; however, version 21.3.1 is available.
  You should consider upgrading via the '/opt/python/cp38-cp38/bin/python -m pip install --upgrade pip' command.
  Processing /project
  Building wheels for collected packages: neo3vm
    Building wheel for neo3vm (setup.py): started
    Building wheel for neo3vm (setup.py): finished with status 'error'
    Running setup.py clean for neo3vm
```

How do I prevent this cleanup step?

**Comment by henryiii** [comment]
I think you set PIP_NO_CLEAN? Pip "no" variables are weird, IIRC you have to set them to a false value.

**Comment by ixje** [comment]
Didn't know that was an option (or that this is a pip thing). Thanks, will give it a try.
