### ISSUE TITLE
Setting PIP options can break environment setup

### ISSUE THREAD

**Issue by henryiii** [pypa/cibuildwheel#942]
### Description

Setting a pip option, like `PIP_USE_DEPRECATED=out-of-tree-build` can break the initial setup, because this option gets applied to the original pip version (21.1 on Windows) instead of our pinned version. We should possibly ignore PIP_* variables or all environment variables during this initial setup for the pinned versions of things.

See https://github.com/pybind/cmake_example/pull/66

Example of problematic line: https://github.com/pypa/cibuildwheel/blob/f717468ff60fbd2ee76b6327596d078ad0ec13d5/cibuildwheel/macos.py#L232

### Build log

https://github.com/pybind/cmake_example/runs/4346290813?check_suite_focus=true

### CI config

https://github.com/pybind/cmake_example/blob/c06fc016af76bd0f6a637705afc5d4cbfa554f5a/.github/workflows/wheels.yml#L49

**Comment by joerick** [comment]
Hmm yes, I can see the argument. We could also defer applying CIBW_ENVIRONMENT until after our internal tools install? Not sure which is preferable though.

**Comment by henryiii** [comment]
It would be simpler to defer till after the internal tools install, since we set a few pip variables (like the version check).
