### ISSUE TITLE
Difficulties using versioneer on Linux and OSX

### ISSUE THREAD

**Issue by bashtage** [pypa/cibuildwheel#982]
### Description

I have attempting to statsmodels-wheels to cibuildwheel.  It has mostly gone smoothly, but the final snag is the loss of version information on Linux and OSX.

statsmodels uses versioneer to handle versions. The wheel building happens in its own repo with the structure

statsmodels-wheels
statsmodels-wheels/statsmodels [Git submodule]

I cd into statsmodels and run cibuildwheel.  It works as expected except that it seems to copy to files to project which then has no git information.  As a result of using versioneer, which requires building from the repo, I end up with version strings like `statsmodels-0+unknown-cp310-cp310-linux_x86_64.whl`

This does not happen in windows where I get version strings like statsmodels-0.14.0.dev0+168.g590384e8b-cp310-cp310-win_amd64.whl.

Is there some way to get cibuildwheel to operation in a full git environment on *nix like OSes?

### Build log

https://github.com/MacPython/statsmodels-wheels/runs/4714156702

### CI config

https://github.com/MacPython/statsmodels-wheels/blob/0896ec1534fc59c8ec7018845163d2f4ee5d083c/.github/workflows/build-wheels.yml

**Comment by Czaki** [comment]
If I good remember you should use 

```
      - name: Build wheels
        run: |
          echo "CIBW_BUILD: ${CIBW_BUILD}"
          python -m cibuildwheel statsmodels
```
instead of 

```
      - name: Build wheels
        run: |
          echo "CIBW_BUILD: ${CIBW_BUILD}"
          cd statsmodels
          python -m cibuildwheel --output-dir ../wheelhouse
```

because cibuildwheel copy current directory https://github.com/pypa/cibuildwheel/blob/9e18cb8656a1c3583e571736ba8eb5ed8cc68221/cibuildwheel/linux.py#L113

see package_dir CLI option in documentation https://cibuildwheel.readthedocs.io/en/stable/options/#command-line

**Comment by bashtage** [comment]
Thanks. I just self helped and say that option in the help of the command.
