### ISSUE TITLE
Caping dependecies for testing (issue with numpy 1.22 on ubuntu i686)

### ISSUE THREAD

**Issue by MuellerSeb** [pypa/cibuildwheel#993]
### Description

We had a strange issue, where our CI job for ubuntu i686 hanged for hours before it got canceled ([link](https://github.com/GeoStat-Framework/GSTools/runs/4795546313?check_suite_focus=true))
Nothing was changed on our side. The same workflow was working one month earlier ([link](https://github.com/GeoStat-Framework/GSTools/runs/4534768023?check_suite_focus=true))

This happend for py38, where I noticed (after hours of wondering), that for numpy 1.22, a zip file was downloaded and a wheel was built (before numpy 1.21.4 was downloaded with a prebuilt wheel). It seem that the built wheel for numpy 1.22 was broken, so the test suite did not start.

Numpy apparently dropped building wheels for 32bit on linux with v1.22. So I wanted to cap the numpy version for ubuntu32bit.

I got it running with this override in pyproject.toml:
```toml
[[tool.cibuildwheel.overrides]]
select = "*manylinux_i686"
# no wheels for 32 bit anymore
test-requires = "numpy<1.22"
```

Problem is just, that first numpy 1.22 is built and then downgraded before the test suite (which then succeeds).
So it would be best, to first install the `test-requires` and then install the package to be tested.

I guess I could just use `before-test = "pip install 'numpy<1.22'"` to install numpy beforehand, but I think `test-requires` describes the situation better.

Did I miss an obvious option for this situation?

Thanks for the great package,
Sebastian

### CI config

https://github.com/GeoStat-Framework/GSTools/blob/d8941c2fc76531304e59faf75d36fd95153c38d3/.github/workflows/main.yml

**Comment by MuellerSeb** [comment]
I guess my main question is: What speaks against installing `test-requires` before installing the wheel built by CIBW?

**Comment by henryiii** [comment]
Capping is not a good solution. You'll more than likely forget the cap here. A better solution is to add:

```
[tool.cibuildwheel.environment]
# this makes sure that we build only on platforms that have a corresponding numpy wheel
PIP_ONLY_BINARY = ":all:"
```

Or set it to "numpy" only (comma separated list).

**Comment by henryiii** [comment]
There's a prefer binary option too.

**Comment by MuellerSeb** [comment]
Thanks for the answer. What happens with packages that only have a source distribution?

**Comment by henryiii** [comment]
The require variant produces an error, the prefer variant installs it anyway. Though for the require version you can lost packages instead of :all:.

I usually use require on NumPy then skip tests for the platforms it is missing wheels for, guessing users on those platforms will use their system package manager for NumPy. Some people just skip those platforms entirely.

**Comment by MuellerSeb** [comment]
I went with:
```toml
environment = "PIP_PREFER_BINARY=1"
```
in pyproject.toml. Thanks for your help.
