### ISSUE TITLE
Cannot Link Static Libraries

### ISSUE THREAD

**Issue by Grey41** [pypa/cibuildwheel#995]
I have a Python C extension module which relies on static libraries. Below is my file tree, I haven't included all the files because I am trying to simplify the problem.

```
folder/
├── src/
|   ├── main.c
|   └── other.c
├── include/
|   ├── glfw3native.h
|   └── glfw3.h
├── lib/
|   └── libglfw3.a
└── setup.py
```

Below is my `setup.py` file, I have removed some unnecessary lines.

```
import setuptools

setuptools.setup(
    ext_modules = [
        setuptools.Extension(
            "Module.__init__", ["src/main.c", "src/other.c"],
            include_dirs = ["include"],
            library_dirs = ["lib"],
            libraries = ["glfw"])
    ])
```

I can successfully compile my project and generate the wheel file with the following command.

```
python setup.py bdist_wheel
```

Now I want to use `cibuildtools` to compile my project for multiple platforms.

```
cibuildwheel --platform linux
```

For some reason, the program crashes when it tries to link the libraries. Even though the library path is stated, it shows the following error.

```
cannot find -lglfw
```

Why does this happen when compiling with `cibuildwheel`? Shouldn’t it do the same thing as `bdist_wheel`?

**Comment by Czaki** [comment]
`cibuildwheel` build linux wheels in docker container. You need to install this library in `CIBW_BEFORE_ALL` step.

**Comment by Grey41** [comment]
Thank you. I've been trying to solve this problem for a while. The `CIBW_BEFORE_ALL` command also means the libraries are guaranteed to work because they are compiled on the corresponding platform.
