### ISSUE TITLE
`Unsupported architecture` bugs when cross-compiling for Apple Silicon?

### ISSUE THREAD

**Issue by motiwari** [pypa/cibuildwheel#998]
### Description

Hi, I'm running into a problem when building for Apple Silicon via Github runners: I continue to get the errors like:

```
/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/sys/cdefs.h:807:2: error: Unsupported architecture
    #error Unsupported architecture
```

I've read through the documentation [tips and tricks](https://cibuildwheel.readthedocs.io/en/stable/faq/#apple-silicon) regarding for building for M1 Macs from the runners, and verified that XCode 12.4 (>12.2) is installed on the runners. My `.yml` file very closely matches the example `.github/workflows/build_macos.yml`, but the error persists.

For more information, my `.yml` is available [here](https://github.com/ThrunGroup/BanditPAM/blob/a6d9ee41243a2292d064fa68895725bcf24c8f3f/.github/workflows/build_m1_wheel.yml) and an example error is [here](https://github.com/ThrunGroup/BanditPAM/runs/4929119849?check_suite_focus=true#step:3:917).

In case it matters, I install some dependencies in my [`pyproject.toml`](https://github.com/ThrunGroup/BanditPAM/blob/a6d9ee41243a2292d064fa68895725bcf24c8f3f/pyproject.toml#L17) via a [script](https://github.com/ThrunGroup/BanditPAM/blob/a6d9ee41243a2292d064fa68895725bcf24c8f3f/scripts/docker/cibw_before_all_macos.sh).

### Build log

https://github.com/ThrunGroup/BanditPAM/runs/4929119849?check_suite_focus=true

### CI config

https://github.com/ThrunGroup/BanditPAM/blob/a6d9ee41243a2292d064fa68895725bcf24c8f3f/.github/workflows/build_m1_wheel.yml

**Comment by motiwari** [comment]
I'm not sure, but [this thread](https://github.com/ycm-core/YouCompleteMe/issues/3770) makes me think it may be related to Apple's bundled Python version. Strangely, it looks like the bundled Python version might also still be 2.7 in XCode 12.4. Is there a command we're supposed to run on the runners to enable building on M1 Macs (perhaps something on the documentation needs to be updated)?

**Comment by henryiii** [comment]
`pip install numpy` is installing numpy into the system Python 2.7. Not sure why you want to do that in build-all? I see that `-mmacosx-version-min=10.7` is being passed, I'm pretty sure you can't target 11+ and anything less than 10.9. And you can't use anything less than about 10.12-10.14 with C++17 (which is also being passed when building)

**Comment by motiwari** [comment]
Thanks @henryiii !
- You were right that the `pip install numpy` was extraneous; I've removed it
- Does this mean that the wheels built for Apple Silicon will not work for M1 Macs running Mac OS 11+? Is there another way to build the wheels for MacOS 11+, say purchase an M1 Mac and build it locally?
- I tried adding but [`MACOSX_DEPLOYMENT_TARGET: "10.14"`](https://github.com/ThrunGroup/BanditPAM/blob/7b75f7867133c118e8aee8b350a666d36ae469dd/.github/workflows/build_m1_wheel.yml#L41) to the `.yml` but [the error persists](https://github.com/ThrunGroup/BanditPAM/runs/4929832052?check_suite_focus=true#step:3:921) -- am I missing something?

**Comment by motiwari** [comment]
Oh, I see that  `mmacosx-version-min=10.7` is still passed even when setting `MACOSX_DEPLOYMENT_TARGET`. Let me try to fix

**Comment by motiwari** [comment]
Hi @henryiii, I was able to fix -- bug was on my side. Apologies for the churn.

Last question: does your comment above mean that the wheels built for Apple Silicon will not work for M1 Macs running Mac OS 11+? Is there another way to build the wheels for MacOS 11+, say purchase an M1 Mac, install MacOS 11+, and build it locally?

**Comment by henryiii** [comment]
No, I just meant that you need to target at least 10.9+ to also be able to run on 11 & 12. (as well as to do much of anything else). 10.9 binaries work on 11 & 12.

**Comment by motiwari** [comment]
Thank you!
